export type SfiDevelopmentClass = 'PRODUCT' | 'INFRASTRUCTURE' | 'PROGRAM' | 'LAB_ONLY' | 'ABSORBED' | 'ARCHIVED';
export type SfiDevelopmentState = 'OPERATIONAL' | 'READY' | 'EXPERIMENTAL' | 'IN_DEVELOPMENT' | 'GATED' | 'DEPRECATED';

export type SfiDevelopmentEntry = {
  id: string;
  name: string;
  purpose: string;
  method: string;
  variables: string[];
  implementation: string;
  maturityEstimate: number;
  classification: SfiDevelopmentClass;
  state: SfiDevelopmentState;
  product: string;
  nextGate: string;
  absorbedInto?: string[];
};

// maturityEstimate is a planning estimate, not evidence, truth probability or scientific validation.
export const SFI_DEVELOPMENT_REGISTRY: SfiDevelopmentEntry[] = [
  {id:'longitudinal-system-friction-framework',name:'SFI · Longitudinal System Friction Framework',purpose:'Unify observation, modeling, experimentation, intervention, return, learning and authority.',method:'observe → preserve → relate → hypothesize → test → return → learn → govern',variables:['state','actor','rule','information','memory','authority','evidence','trajectory'],implementation:'Institutional cycle spans Observatory, Studio, Method Lab, Field, Evidence, Cognitive Twin and ROOT/ACP. Public end-to-end proof remains required.',maturityEstimate:86,classification:'PRODUCT',state:'READY',product:'System Friction Institute · Longitudinal Systems Infrastructure',nextGate:'Run and publish one governed real case through the complete cycle.'},
  {id:'mihm',name:'Modelo Integral Homeostático Multinodal — MIHM',purpose:'Represent the multinodal structural state of an identified object.',method:'Meta-framework selects an instrument from object, question, temporality and evidence.',variables:['IHG','NTI','LDI','XI','PHI_FAMILY','F_s'],implementation:'Canonical method family with executable registry and method-scoped Phi semantics.',maturityEstimate:90,classification:'PRODUCT',state:'OPERATIONAL',product:'MIHM Structural State Engine',nextGate:'Accumulate cross-case calibration and externally reproducible examples.'},
  {id:'method-resolver',name:'MIHM Method Selection Resolver',purpose:'Prevent applying the wrong instrument to an object merely because variables overlap.',method:'object + temporality + evidence + purpose → method',variables:['object_type','temporal_scope','method','READY','AMBIGUOUS','BLOCKED'],implementation:'Executable resolver and registry.',maturityEstimate:86,classification:'INFRASTRUCTURE',state:'OPERATIONAL',product:'SFI Method Resolver',nextGate:'Reflect the resolver in the next methods-book edition and validate ambiguous-object cases.'},
  {id:'phi-family',name:'Familia Φ',purpose:'Keep method-specific homeostatic states semantically distinct.',method:'One Phi per instrument; no implicit averaging or cross-method substitution.',variables:['PHI_H','PHI_S','PHI_F','PHI_W','PHI_SFI'],implementation:'Canonical contracts and registry; c_field is explicitly not another Phi.',maturityEstimate:88,classification:'INFRASTRUCTURE',state:'OPERATIONAL',product:'MIHM Structural State Engine · Phi family',nextGate:'Calibration evidence per instrument.'},
  {id:'mop-h',name:'MOP-H',purpose:'Observe human/system configuration and run a minimum reversible perturbation with return.',method:'baseline → prior hypothesis → reversible intervention → window → return → contrast',variables:['IHG','NTI','LDI','GO','EPSILON','PHI_H'],implementation:'Stable method; public MOP-H surface and Field cycle use governed return windows.',maturityEstimate:90,classification:'PRODUCT',state:'OPERATIONAL',product:'SFI Field Case · Human/System Friction',nextGate:'Close and publish a complete real Field case with observed return.'},
  {id:'scorefriction',name:'ScoreFriction',purpose:'Measure formal, semantic, memetic or longitudinal friction/continuity of a delimited object.',method:'Multimodal object analysis with method-specific feature extraction.',variables:['feature_vectors','IHG','NTI','LDI','XI','PHI_S','F_s'],implementation:'Present in MIHM registry and public ScoreFriction surface; product trajectory integration remains partial.',maturityEstimate:80,classification:'PRODUCT',state:'READY',product:'ScoreFriction / Digital Product Trajectory Intelligence',nextGate:'Join provenance + trajectory + return into one operational product pipeline.'},
  {id:'worldspect',name:'World Spectrum Vector / WorldSpect',purpose:'Introduce exogenous context without converting context into causality.',method:'Longitudinal multi-domain source aggregation with freshness and confidence.',variables:['WSI','NTI','source_freshness','confidence','dominant_signal','PHI_W','world_trajectory'],implementation:'Stable instrument consumed by Observatory; executable contract uses 10 domains.',maturityEstimate:86,classification:'PRODUCT',state:'OPERATIONAL',product:'SFI Observatory Intelligence · World Vector',nextGate:'Improve source coverage/freshness and calibrate domain aggregation.'},
  {id:'ppoi',name:'PPOI',purpose:'Maintain phenomena/cases that cannot be reduced to a point observation.',method:'Accumulated evidence + current/rival hypothesis + longitudinal recalibration.',variables:['PPOI_composite','PHI_F','trajectory','evidence_span'],implementation:'Runtime contract exists; external case corpus remains limited.',maturityEstimate:68,classification:'PROGRAM',state:'EXPERIMENTAL',product:'PPOI Longitudinal Case Observatory',nextGate:'Freeze protocol definition and run multiple comparable persistent-phenomenon cases.'},
  {id:'diol-sf',name:'DIOL-SF',purpose:'Reconstruct and follow a phenomenon longitudinally without rewriting the original record.',method:'identify → baseline/model → diagnose → intervene → longitudinal observation',variables:['T0..Tn','evidence','changes','rival_interpretations','windows'],implementation:'Stable in book/Atlas; needs a reusable runtime/report contract.',maturityEstimate:66,classification:'PROGRAM',state:'READY',product:'SFI Longitudinal Diagnostic',nextGate:'Bind DIOL-SF explicitly to Field/Atlas return reports and validate on two domains.'},
  {id:'inference-trace',name:'Método SFI de Inferencia',purpose:'Reduce explanatory space without converting interpretation into fact.',method:'preconditions → facts/inferences → rivals → discriminating evidence',variables:['premises','unknowns','rival_hypotheses','confidence','discriminating_observation'],implementation:'Logic exists across Cognitive Twin and Method Lab; standalone benchmark not stabilized.',maturityEstimate:60,classification:'INFRASTRUCTURE',state:'IN_DEVELOPMENT',product:'SFI Inference Trace',nextGate:'Create a benchmark of rival-hypothesis discrimination and failure cases.'},
  {id:'minimal-field-perturbation',name:'Perturbación Mínima de Campo',purpose:'Gain information with the minimum reversible change.',method:'baseline → objective/hypothesis → invariants → risk → minimum change → reobserve',variables:['degrees_of_freedom','risk','reversibility','window','return'],implementation:'Operationally embedded in MOP-H/Field rather than a separate product.',maturityEstimate:76,classification:'INFRASTRUCTURE',state:'READY',product:'SFI Minimal Intervention Protocol',nextGate:'Formalize intervention-size and stopping criteria across Field cases.'},
  {id:'return-contrast',name:'Observación y Contraste de Resultados',purpose:'Prevent post-hoc reinterpretation after outcome is known.',method:'frozen prediction → execution → observation → residual → rivals → persistence',variables:['expected','observed','residual','absolute_error','squared_error','persistence'],implementation:'Field/AMV support outcome and prediction-error concepts; report-level standard is incomplete.',maturityEstimate:74,classification:'INFRASTRUCTURE',state:'READY',product:'SFI Return & Contrast Report',nextGate:'Make the contrast report mandatory for every completed Field/experimental return.'},
  {id:'trajectory-dynamics',name:'Dinámica de Trayectorias',purpose:'Distinguish state, direction and transformation.',method:'longitudinal series + attractor + change detection',variables:['position','velocity','deviation','persistence','context'],implementation:'Used across longitudinal program and Observatory; unified trajectory engine remains incomplete.',maturityEstimate:58,classification:'PROGRAM',state:'IN_DEVELOPMENT',product:'SFI Trajectory Engine',nextGate:'Freeze common trajectory schema and validate change-point/attractor inference.'},
  {id:'regime-transition',name:'Regime Transition Program',purpose:'Detect when the effective operating rules of a system change.',method:'Longitudinal configuration analysis rather than one universal threshold.',variables:['actor_composition','human_agent_ratio','latency','semantic_convergence','novelty','selection_pressure','feedback_loop_length','attention','propagation','memory','authority'],implementation:'Institutional program domain; not yet a calibrated scientific model.',maturityEstimate:48,classification:'PROGRAM',state:'EXPERIMENTAL',product:'SFI Regime Transition Observatory',nextGate:'Define ingestion contract, labeled historical transitions and negative controls.'},
  {id:'threshold-calibration',name:'Thresholds & Calibration',purpose:'Determine when a signal justifies state transition, block or action.',method:'Versioned thresholds + explicit error evaluation.',variables:['FP','FN','precision','sensitivity','temporal_stability','error_cost'],implementation:'Canon requires calibration; historical Atlas thresholds are not universal defaults.',maturityEstimate:76,classification:'INFRASTRUCTURE',state:'READY',product:'SFI Calibration & Threshold Assurance',nextGate:'Persist threshold version/evaluation history and cross-case error rates.'},
  {id:'evidence-provenance',name:'Evidence + Provenance Layer',purpose:'Separate reality, record, derivation, inference and simulation.',method:'Append-only ledger + typed relationships + hashes/lineage.',variables:['source','acquisition','observed_at','ingested_at','hash','lineage','class','confidence'],implementation:'Canonical evidence/graph, hashes, lineage and epistemic classes are core runtime infrastructure.',maturityEstimate:94,classification:'INFRASTRUCTURE',state:'OPERATIONAL',product:'SFI Evidence Ledger',nextGate:'External timestamp/anchor option and public verification tooling for selected artifacts.'},
  {id:'atlas',name:'Atlas / Reference Bank',purpose:'Preserve cases, precedents, predictions, outcomes and genealogy.',method:'Longitudinal navigation over cases/objects and their evidence relations.',variables:['case_code','class','cohort','T0','prediction','intervention','return','outcome','error','model_version'],implementation:'Atlas corpus and reference-bank concepts exist; operational case linkage is active but not complete for all historical artifacts.',maturityEstimate:88,classification:'PRODUCT',state:'OPERATIONAL',product:'SFI Atlas · Longitudinal Reference Bank',nextGate:'Backfill high-value historical objects into canonical case/evidence relations.'},
  {id:'library',name:'Library / Repository',purpose:'Durable, addressable documentary corpus.',method:'Versioned publication + manifest + provenance.',variables:['document_id','version','source','status','lineage'],implementation:'Public repository/library surfaces and materials exist.',maturityEstimate:92,classification:'PRODUCT',state:'OPERATIONAL',product:'SFI Library',nextGate:'Complete manifests/status for the canonical publication corpus.'},
  {id:'observatory',name:'Observatory',purpose:'Present current/longitudinal public state without exposing private material.',method:'WorldSpect → evidence → temporal resolution → trajectory',variables:['domains','sources','freshness','signal_state','trajectory','confidence'],implementation:'Public surface intentionally exposes THIN/DEGRADED states instead of fabricating completeness.',maturityEstimate:87,classification:'PRODUCT',state:'OPERATIONAL',product:'SFI Observatory Intelligence',nextGate:'Complete source health and publish one longitudinal regime/case view with observed returns.'},
  {id:'studio',name:'Studio',purpose:'Analyze objects, design interventions and simulate before touching reality.',method:'intake → MIHM → projection → intervention design → simulation → forecast',variables:['object_features','MIHM_state','attractor','scenarios','intervention_candidates','forecast'],implementation:'Authenticated functional surface with capability inventory; external closed-case evidence is the main deficit.',maturityEstimate:80,classification:'PRODUCT',state:'READY',product:'SFI System Intervention Studio',nextGate:'Close external cases that traverse Studio → Field → return.'},
  {id:'field',name:'FIELD',purpose:'Execute governed intervention and capture real return.',method:'case → hypothesis → hash → intervention → return → evidence → contrast',variables:['baseline','hypothesis','intervention','return_window','evidence','outcome'],implementation:'Operational schema/API supports cases, evidence, MOP-H, MIHM, hypotheses, interventions, returns and outcomes.',maturityEstimate:88,classification:'PRODUCT',state:'OPERATIONAL',product:'SFI Field Case · Applied System Diagnosis',nextGate:'Complete and publish at least one end-to-end return with evidence.'},
  {id:'method-lab',name:'Method Lab',purpose:'Test methods/models without contaminating canon or observed reality.',method:'claim/null → run → replay → holdout → counterfactual → calibration → report',variables:['datasetHash','parametersHash','seed','commit','provider_model','resultHash','validation_level'],implementation:'Shared laboratory apparatus; protocols remain SIMULATED until later observed support; promotion is ROOT/ACP-gated.',maturityEstimate:78,classification:'PRODUCT',state:'READY',product:'SFI Method Lab',nextGate:'Run/import institutional executions for each registered protocol and expose reproducible reports.'},
  {id:'chronos',name:'CHRONOS / Cognitive Olympics',purpose:'Test cognitive constitutions under sealed temporal conditions.',method:'historical sealed → shadow world → prospective',variables:['temporal_cutoff','holdout','model','seed','outcome','leakage_boundary'],implementation:'Implemented benchmark harness and Method Lab registration; no external validation yet.',maturityEstimate:64,classification:'LAB_ONLY',state:'EXPERIMENTAL',product:'SFI CHRONOS',nextGate:'Run preregistered pilot, preserve contamination controls and publish benchmark protocol.'},
  {id:'crl',name:'Cognitive Relational Lab — CRL',purpose:'Separate cognitive signal from extraction-operator artifact.',method:'blind reconstruction → contrast → divergence → candidate learning',variables:['founder_response','model_reconstruction','twin_reconstruction','divergence','counterexamples'],implementation:'Method Lab protocol; persistence model requires attributable ROOT/ACP governance decision before production schema is treated as approved.',maturityEstimate:60,classification:'LAB_ONLY',state:'GATED',product:'Cognitive Relational Lab',nextGate:'Resolve CRL persistence through ROOT/ACP and execute retrospective contrast run.'},
  {id:'ct-reentry',name:'Cognitive Twin Reentry',purpose:'Test whether Twin functions survive changes of engine/context.',method:'founder holdout + engine swap + mutation + prospective return',variables:['model','provider','memory_state','holdout','evaluation','lineage'],implementation:'Governed lineage/reentry apparatus exists; validation remains laboratory-gated.',maturityEstimate:64,classification:'LAB_ONLY',state:'EXPERIMENTAL',product:'Cognitive Twin Reentry Protocol',nextGate:'Run same-task/same-history comparisons across multiple model substrates.'},
  {id:'cognitive-twin',name:'Cognitive Twin / PERENNE',purpose:'Turn recurrent cognitive operations into traceable institutional memory.',method:'capture → pattern → contrast → rule/constraint/exception → transfer → return',variables:['CDT','CognitivePattern','Rule','Constraint','Exception','lineage'],implementation:'Persistent memory/decision/evaluation/run infrastructure and governed deliberation exist; independent scientific benchmark remains pending.',maturityEstimate:74,classification:'INFRASTRUCTURE',state:'EXPERIMENTAL',product:'SFI Cognitive Twin',nextGate:'Accumulate real longitudinal epochs and validate useful transfer beyond context/retrieval baselines.'},
  {id:'ct-a01-lineage',name:'CT-A01 / Agent Lineage',purpose:'Treat one cognitive instance as a longitudinal experimental subject, not a digital person.',method:'genesis → heartbeat → snapshot → fork/mutation → holdout → prospective return → lineage',variables:['model','seed','architecture','memory_baseline','biography','context','lineage_hash'],implementation:'Genesis, hash-chain, journal, snapshots, registered-not-running forks, mutation candidates and exportable checkpoints exist; individuation remains unproven.',maturityEstimate:52,classification:'PROGRAM',state:'EXPERIMENTAL',product:'Agent Lineage Observatory / Longitudinal Individuation Protocol',nextGate:'Start controlled A/B biographies and preregister BPA/CLS/rollback/transplant experiments.'},
  {id:'amv-runtime',name:'AMV / Cognitive Runtime',purpose:'Coordinate observation, evidence, hypothesis, prediction gating, intervention and learning.',method:'Phased governed agent pipeline.',variables:['evidence','model_state','prediction','intervention','error','calibration_corpus'],implementation:'Converged agent registry/passports and runtime evidence separate declared, bound and observed execution.',maturityEstimate:84,classification:'INFRASTRUCTURE',state:'OPERATIONAL',product:'SFI Cognitive Runtime',nextGate:'Resolve shared degraded dependencies and accumulate stable run/return evidence.'},
  {id:'root-acp',name:'ROOT / ACP',purpose:'Sovereign authority over approval, preparation, realization, conflict, rollback and promotion.',method:'proposal → evidence → design approval → prepare → realize → return → promote',variables:['permission','proposal','evidence','tests','risk','authority','rollback','decision'],implementation:'Single lifecycle, governance health, conflict routing, promotion receipts and institutional readiness are implemented on the convergence branch.',maturityEstimate:96,classification:'INFRASTRUCTURE',state:'READY',product:'ROOT Governance Plane',nextGate:'Merge/verify convergence, resolve CRL decision and operate the first complete promotion/return receipt.'},
  {id:'agent-assurance',name:'Agent Governance & Operational Assurance',purpose:'Audit the difference among declared, executable, executed and authorized agent behavior.',method:'capabilities + permissions + audit + execution evidence + lineage + governance',variables:['agent_id','capability','input_output','provider_model','permissions','mutations','evidence','authorization'],implementation:'Strong internally via passports/ROOT/runtime; not packaged/tested on external agents.',maturityEstimate:80,classification:'PRODUCT',state:'READY',product:'SFI Agent Governance & Operational Assurance',nextGate:'Create an external adapter and evaluate a non-SFI agent system.'},
  {id:'fad',name:'Field Audio Dynamics — FAD',purpose:'Study identity and trajectory of sound objects.',method:'technical + perceptual analysis + invariants + longitudinal contrast',variables:['audio_features','MIHM_context','invariants'],implementation:'Studio audio analysis exists; general method validation is insufficient.',maturityEstimate:50,classification:'LAB_ONLY',state:'EXPERIMENTAL',product:'FAD · Cultural Systems / Audio Dynamics',nextGate:'Define falsifiable invariants and evaluate a multi-object audio corpus.'},
  {id:'cross-domain-coherence',name:'Coherencia Transdimensional',purpose:'Evaluate which identity survives a domain change.',method:'source → invariants → functional mapping → loss → attractor contrast',variables:['invariants','roles','mappings','loss','transferability'],implementation:'Concept exists; no dedicated benchmark/runtime contract.',maturityEstimate:40,classification:'LAB_ONLY',state:'IN_DEVELOPMENT',product:'SFI Cross-Domain Coherence Test',nextGate:'Build Method Lab benchmark with positive/negative transfer controls.'},
  {id:'mop-s',name:'MOP-S',purpose:'Separate stages where a signal survives or degrades.',method:'acquisition → signal → publication → visualization → recovery/recording → traceability',variables:['A','S','P','V','G','T','carrier','detector','hash','transformations'],implementation:'Experimental MEDIA/CHANNEL/BOUNDARY family and P0-A/B/C are registered; no recurring service yet.',maturityEstimate:58,classification:'LAB_ONLY',state:'EXPERIMENTAL',product:'SFI Signal Persistence Lab',nextGate:'Execute P0-A/B/C with controlled corpus, detector metrics and transformation matrix.'},
  {id:'artifact-provenance',name:'Sistema esteganográfico de observación',purpose:'Insert authorized markers to study persistence and transformation of SFI-owned/consented artifacts.',method:'marker embedding → publication → transformation → detection → lineage',variables:['marker_id','carrier','amplitude_redundancy','detector','hash','transformation'],implementation:'Ethically bounded as artifact provenance; not a person-tracking system. Operational marker pipeline is incomplete.',maturityEstimate:38,classification:'LAB_ONLY',state:'IN_DEVELOPMENT',product:'SFI Artifact Provenance Lab',nextGate:'Implement authorized marker registry/detector benchmark and cross-platform transformation study.'},
  {id:'digital-ecosystem-observatory',name:'Digital Ecosystem Observatory',purpose:'Observe human-agent-platform ecologies and regime transitions.',method:'graph + longitudinal propagation + regime analysis',variables:['human_agent_ratio','ranking_pressure','mutation','latency','propagation','decay_revival'],implementation:'Program domain of Observatory, not a parallel app; ingestion/dataset are still missing.',maturityEstimate:30,classification:'PROGRAM',state:'IN_DEVELOPMENT',product:'Digital Ecosystem Observatory',nextGate:'Define lawful ingestion contracts and a longitudinal ecosystem dataset.'},
  {id:'digital-product-trajectory',name:'Digital Product / Artifact Trajectory Intelligence',purpose:'Track how an object/product changes while moving across platforms.',method:'provenance graph + trajectory + mutation + return',variables:['parent_child','hash','marker','copy_remix','semantic_drift','propagation_path'],implementation:'Pieces exist across ScoreFriction, MOP-S, provenance, Atlas and Observatory; one pipeline is not yet assembled.',maturityEstimate:42,classification:'PRODUCT',state:'IN_DEVELOPMENT',product:'SFI Digital Product Trajectory Intelligence',nextGate:'Assemble object registration → detection → graph → trajectory → intervention → return pipeline.'},
  {id:'directed-autonomous-growth',name:'Directed Autonomous Growth',purpose:'Allow adaptive experimentation inside explicit human authority.',method:'human attractor/constraints → agents observe/simulate/propose/allowed execution → return → ROOT',variables:['attractor','budget','constraints','forbidden_actions','permissions','outcome','strategy_mutation'],implementation:'Governance model and agent infrastructure exist; demonstrated autonomous growth outcome does not.',maturityEstimate:44,classification:'PROGRAM',state:'EXPERIMENTAL',product:'SFI Adaptive Growth Field',nextGate:'Run a bounded live experiment with budget, prohibited actions, stop rules and observed return.'},
  {id:'configuration-response-library',name:'Biblioteca de Configuraciones y Respuestas',purpose:'Recover functional precedents rather than only files.',method:'configuration matching + precedent retrieval',variables:['configuration','intervention','outcome','exception','stopping_condition','transferability'],implementation:'Function overlaps Atlas/Reference Bank and Cognitive Twin memory.',maturityEstimate:68,classification:'ABSORBED',state:'READY',product:'SFI Reference Bank + Cognitive Twin Memory',nextGate:'Do not build a parallel product; complete typed precedent retrieval in the absorbing systems.',absorbedInto:['atlas','cognitive-twin']},
  {id:'protocol-registry',name:'SFI Protocol Registry / Methods Corpus',purpose:'Make methods versioned, auditable and eventually replicable objects.',method:'internal → experimental → validated → replicated → reference',variables:['object','inputs','outputs','procedure','falsification','failure_modes','validation','version','evidence'],implementation:'Canonical corpus and multiple executable registries exist; a single cross-method development registry is now being constituted.',maturityEstimate:72,classification:'INFRASTRUCTURE',state:'READY',product:'SFI Methods & Protocol Registry',nextGate:'Bind every method to owner, status, version, validation evidence, product class and next gate.'},
  {id:'sfi-qom',name:'SFI-QOM',purpose:'Reveal operational and authority gaps at intake.',method:'Questionnaire / gap extraction.',variables:['NTI_gap','LDI_oculto','Capa_0_incoherencia','Runway'],implementation:'Useful intake concept but not a primary methodology.',maturityEstimate:40,classification:'ABSORBED',state:'READY',product:'Field Intake / Operational Observation Questionnaire',nextGate:'Absorb questions into Field intake; do not market separately.',absorbedInto:['field']},
  {id:'ucap',name:'UCAP / capacidad–energía–entropía',purpose:'Represent reserve/capacity and cost of maintaining state.',method:'Experimental Mathcore track.',variables:['C_i','E_i','L_i','K_i','R_i','M_i','UCAP','runway'],implementation:'Historical/experimental presence; not in primary MIHM registry.',maturityEstimate:34,classification:'LAB_ONLY',state:'IN_DEVELOPMENT',product:'MIHM Capacity Research Track',nextGate:'Define units, identifiability and empirical calibration before any product/KPI use.'},
  {id:'isomorphism-gap',name:'Brecha de isomorfismo / Cognitive Field',purpose:'Represent difference between intended and executed configuration.',method:'Vector/graph state comparison.',variables:['Delta_iso','CC=(V,E,W)','S(t+1)=F(S(t),I(t),O(t))'],implementation:'Historically strong but must not be confused with canonical F_s.',maturityEstimate:32,classification:'LAB_ONLY',state:'IN_DEVELOPMENT',product:'SFI Structural Divergence Lab',nextGate:'Create explicit object model and benchmark against simpler state-distance baselines.'},
  {id:'olc',name:'OLC / Operador Lingüístico de Colapso',purpose:'Observe how a formulation reduces explanatory degrees of freedom.',method:'Linguistic operator classification.',variables:['OLC-D','OLC-N','OLC-P','fingerprints','pre_post_state'],implementation:'Narratively developed; not a current registered MIHM instrument.',maturityEstimate:34,classification:'LAB_ONLY',state:'IN_DEVELOPMENT',product:'Linguistic Constraint Analyzer',nextGate:'Keep inside Method Lab until inter-rater/behavioral validity is demonstrated.'},
  {id:'r16-r18',name:'R16 / R17 / R18 históricos',purpose:'Historical governance/distribution/channel-restoration policies.',method:'Legacy policy cluster.',variables:['hashes','policy_class','channel_restoration'],implementation:'Function is superseded by ROOT/ACP governance and permissions.',maturityEstimate:80,classification:'ABSORBED',state:'DEPRECATED',product:'ROOT/ACP Governance Policies',nextGate:'Preserve genealogy only; prevent a second constitutional policy system.',absorbedInto:['root-acp']},
  {id:'external-resonance-engine',name:'External Resonance Engine / bridges N12',purpose:'Historical attempt to integrate external signals by APIs/heuristics.',method:'External APIs + heuristic processing.',variables:['news','social','sentiment','solar_lunar_geomagnetic'],implementation:'Contains historical code/stubs and simulated geomagnetic data; superseded by WorldSpect architecture.',maturityEstimate:12,classification:'ARCHIVED',state:'DEPRECATED',product:'ARCHIVE / DEPRECATED',nextGate:'Preserve as technical genealogy; never use as evidence-producing current methodology.',absorbedInto:['worldspect']},
];

export function summarizeSfiDevelopmentRegistry() {
  const byClass = Object.fromEntries(['PRODUCT','INFRASTRUCTURE','PROGRAM','LAB_ONLY','ABSORBED','ARCHIVED'].map(key => [key, SFI_DEVELOPMENT_REGISTRY.filter(item => item.classification === key).length]));
  const byState = Object.fromEntries(['OPERATIONAL','READY','EXPERIMENTAL','IN_DEVELOPMENT','GATED','DEPRECATED'].map(key => [key, SFI_DEVELOPMENT_REGISTRY.filter(item => item.state === key).length]));
  return { total: SFI_DEVELOPMENT_REGISTRY.length, byClass, byState };
}
