import type { SfiAgentPassport } from '@/lib/sfi/cognitive-runtime/agentPassports';

export function AgentPassportsConsole({ data }: { data: { generatedAt: string; runtimeStatus: string; counts: Record<string, number>; passports: SfiAgentPassport[] } }) {
  return <section style={{ background: '#070706', color: '#eee7d7', padding: 20, fontFamily: 'ui-monospace,SFMono-Regular,Menlo,monospace' }}>
    <header style={{ borderBottom: '1px solid #6c5a2d', paddingBottom: 18 }}><span style={{ color: '#bba365', fontSize: 11, letterSpacing: '.16em' }}>SFI · ROOT · AGENT AUTHORITY</span><h2 style={{ margin: '7px 0' }}>PASAPORTES DE AGENTES</h2><p style={{ color: '#958c7b', maxWidth: 1040 }}>Esta vista no confunde registro con operación. Cada pasaporte declara qué lee, qué escribe, qué ejecuta y qué evidencia persistida demuestra su ejecución. Una fuente faltante degrada el contrato; una tabla vacía no se convierte en actividad ficticia.</p></header>
    <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(160px,1fr))', gap: 10, margin: '16px 0' }}>{Object.entries(data.counts).map(([key, value]) => <article key={key} style={card}><small style={muted}>{key.toUpperCase()}</small><strong style={{ fontSize: 24, color: '#d8c488' }}>{value}</strong></article>)}</section>
    <section style={{ display: 'grid', gap: 10 }}>{data.passports.map((passport) => <article key={`${passport.namespace}:${passport.id}`} style={card}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 14, alignItems: 'baseline', flexWrap: 'wrap' }}><div><small style={muted}>{passport.namespace.toUpperCase()} · {passport.id} · {passport.layer} · {passport.authorityLevel}</small><h3 style={{ margin: '5px 0', fontSize: 16 }}>{passport.name}</h3></div><strong style={{ color: passport.lifecycle === 'OPERATIONAL' ? '#8fba92' : passport.lifecycle === 'MISSING' ? '#d27e7e' : passport.lifecycle === 'DEGRADED' ? '#d58a72' : '#d8b768' }}>{passport.lifecycle}</strong></div><p style={{ color: '#b5ad9c', lineHeight: 1.6, fontSize: 12 }}>{passport.purpose}</p><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 8 }}><Metric label="Executor enlazado" value={passport.executorBound ? 'Sí' : 'No'} /><Metric label="Última ejecución" value={passport.latestExecutionAt ?? 'No observada'} /><Metric label="Fuentes declaradas disponibles" value={`${passport.observedTables.length}/${passport.sourceTables.length}`} /><Metric label="Aprobación humana" value={passport.humanApprovalRequired ? 'Requerida para acción gobernada' : 'No para análisis interno'} /></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(260px,1fr))', gap: 9, marginTop: 12 }}><ContractList label="LEE" values={passport.reads} empty="Ninguna lectura declarada" /><ContractList label="ESCRIBE" values={passport.writes} empty="Ninguna escritura declarada" /><ContractList label="EJECUTA" values={passport.executes} empty="Ningún executor declarado" /><ContractList label="EVIDENCIA DE EJECUCIÓN" values={passport.executionEvidence} empty="Sin ejecución persistida atribuible" /></div>{passport.missingTables.length ? <ContractList label="DEPENDENCIAS NO DISPONIBLES" values={passport.missingTables} empty="" bad /> : null}{passport.warnings.length ? <p style={{ ...muted, color: '#caa176', marginTop: 12 }}>{passport.warnings.join(' · ')}</p> : null}</article>)}</section>
  </section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div style={{ borderTop: '1px solid #29251b', paddingTop: 7 }}><small style={muted}>{label}</small><div style={{ fontSize: 11, marginTop: 4 }}>{value}</div></div>; }
function ContractList({ label, values, empty, bad = false }: { label: string; values: string[]; empty: string; bad?: boolean }) { return <div style={{ border: `1px solid ${bad ? '#5f3027' : '#29251b'}`, background: bad ? '#120c09' : '#090908', padding: 10 }}><small style={{ ...muted, color: bad ? '#c98773' : '#9d8654' }}>{label}</small>{values.length ? <ul style={{ margin: '7px 0 0', paddingLeft: 18, color: bad ? '#cf9a87' : '#c2b9a9', fontSize: 10, lineHeight: 1.6 }}>{values.map((value) => <li key={value}>{value}</li>)}</ul> : <p style={{ ...muted, margin: '7px 0 0' }}>{empty}</p>}</div>; }
const card = { border: '1px solid #29251b', background: '#0d0c09', padding: 15 } as const;
const muted = { color: '#8f8878', fontSize: 10, lineHeight: 1.5 } as const;
