import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { buildTaskGraph } from './taskGraphBuilder';
import { selectCognitiveAutomations } from './automationSelector';
import { evaluateCapabilityRequest, type SfiCapabilityRequest } from './capabilityBroker';
import { requestCognitiveCapability, type SfiCapabilityRuntimeInput } from './capabilityRuntime';
import {
  SFI_ADAPTIVE_MAX_CAPABILITY_INVOCATIONS, activeTaskGraphNodeForCapability, contextWithTaskGraph,
  executeAdaptiveCapabilityRequestsForNode, reserveTaskGraphInvocation, resumeWaitingAdaptiveCapabilities,
  startPlannedTaskGraphNode, taskGraphFromContext, transitionTaskGraphNode, validateTaskGraphInvocationBudget,
} from './adaptiveTaskGraphRuntime';
import type { KernelContext } from './kernelContext';
function ctx(overrides: Partial<KernelContext> = {}): KernelContext { return { cycleId:'trajectory-r3',logbookId:'logbook-r3',taskId:'task-r3',currentEvent:'SFI_TASK_CREATED',evidence:[],hypotheses:[],contradictions:[],simulations:[],predictions:[],risks:[],opportunities:[],metadata:{},...overrides }; }
function plan(mode:'explicit'|'auto'='explicit', agents:string[]=[]){ return {taskId:'task-r3',requiredAgents:agents,executionOrder:['meta_orchestrator',...agents],missingInputs:[],readiness:1,selectionMode:mode,selectionReasons:Object.fromEntries(agents.map(id=>[id,['test']]))}; }
function graphCtx(){ const graph=buildTaskGraph(plan()); const root=activeTaskGraphNodeForCapability(graph,'meta_orchestrator')!; assert.equal(startPlannedTaskGraphNode(graph,root.nodeId),true); transitionTaskGraphNode(graph,root.nodeId,'COMPLETED'); return {graph,root,context:contextWithTaskGraph(ctx(),graph)}; }
function req(root:string, overrides:Partial<SfiCapabilityRequest>={}):SfiCapabilityRequest{return{requestId:'request-r3',trajectoryId:'trajectory-r3',parentStepId:root,requestedByCapabilityId:'meta_orchestrator',requestedCapabilityId:'risk_agent',reason:'bounded adaptive request',requiredInputs:[],availableEvidenceRefs:[],requestedOutputs:['RECOMMENDATION'],urgency:'NORMAL',requestedAt:'2026-09-06T15:00:00.000Z',...overrides};}
function runtime(counter:{n:number}){let e=0;return async(input:SfiCapabilityRuntimeInput)=>requestCognitiveCapability(input,{readHistory:async()=>[],appendEvent:async()=>({ok:true as const,eventId:`event-${++e}`}),executeAgent:async(agentId,context)=>{counter.n++;return{agentId,executed:true,context,executedAt:'2026-09-06T15:01:00.000Z'}}});}
test('ADMIT creates child with request/parent lineage and executes only after Broker admission; DENY never executes',async()=>{const {root,context}=graphCtx(),c={n:0};const r=req(root.nodeId);const admitted=await executeAdaptiveCapabilityRequestsForNode({context:{...context,metadata:{...context.metadata,capabilityRequests:[r]}},parentNodeId:root.nodeId,parentCapabilityId:'meta_orchestrator',requestCapability:runtime(c)});const child=admitted.graph.nodes.find(n=>n.requestId===r.requestId)!;assert.equal(c.n,1);assert.equal(child.state,'COMPLETED');assert.equal(child.parentNodeId,root.nodeId);assert.ok(child.ancestorNodeIds.includes(root.nodeId));assert.equal(child.brokerDisposition,'ADMIT');const denied=req(root.nodeId,{requestId:'denied',requestedCapabilityId:'not_registered'});const d={n:0};const out=await executeAdaptiveCapabilityRequestsForNode({context:{...context,metadata:{...context.metadata,capabilityRequests:[denied]}},parentNodeId:root.nodeId,parentCapabilityId:'meta_orchestrator',requestCapability:runtime(d)});assert.equal(d.n,0);assert.equal(out.graph.nodes.some(n=>n.requestId==='denied'),false);});
test('EVIDENCE_REQUIRED waits, valid evidence reevaluates and supersedes prior waiting lineage',async()=>{const {root,context}=graphCtx(),c={n:0};const r=req(root.nodeId,{requestedCapabilityId:'reality_calibration'});const first=await executeAdaptiveCapabilityRequestsForNode({context:{...context,metadata:{...context.metadata,capabilityRequests:[r]}},parentNodeId:root.nodeId,parentCapabilityId:'meta_orchestrator',requestCapability:runtime(c)});const waiting=first.graph.nodes.find(n=>n.requestId===r.requestId)!;assert.equal(waiting.state,'WAITING_EVIDENCE');assert.equal(c.n,0);const withEvidence={...first.context,evidence:[...first.context.evidence,{id:'return-1',source:'observed-return',confidence:1,payload:{epistemicClass:'RETURN'}}]};const resumed=await resumeWaitingAdaptiveCapabilities({context:withEvidence,requestCapability:runtime(c)});const old=resumed.graph.nodes.find(n=>n.nodeId===waiting.nodeId)!;const replacement=resumed.graph.nodes.find(n=>n.supersedesNodeId===waiting.nodeId)!;assert.equal(c.n,1);assert.equal(old.state,'SUPERSEDED');assert.equal(old.supersededByNodeId,replacement.nodeId);assert.equal(replacement.state,'COMPLETED');});
test('HUMAN_AUTHORITY_REQUIRED remains WAITING_AUTHORITY; synthetic receipt/role/email metadata cannot unlock',async()=>{const {root,context}=graphCtx(),c={n:0};const r=req(root.nodeId,{requestedCapabilityId:'project_execution_manager'});const spoof={requestId:r.requestId,receiptId:'synthetic',authorizedBy:'founder',authorizedAt:'2026-09-06T15:02:00.000Z'};const first=await executeAdaptiveCapabilityRequestsForNode({context:{...context,metadata:{...context.metadata,capabilityRequests:[r],humanAuthorityReceipt:spoof,authorizedBy:'human@example.com'}},parentNodeId:root.nodeId,parentCapabilityId:'meta_orchestrator',requestCapability:runtime(c)});const waiting=first.graph.nodes.find(n=>n.requestId===r.requestId)!;assert.equal(waiting.state,'WAITING_AUTHORITY');assert.equal(c.n,0);const decision=evaluateCapabilityRequest({request:r,context:{...context,metadata:{...context.metadata,humanAuthorityReceipt:spoof}},depth:1,remainingInvocationBudget:1,humanAuthorityReceipt:spoof});assert.equal(decision.disposition,'HUMAN_AUTHORITY_REQUIRED');assert.equal(decision.executionAllowed,false);assert.ok(decision.reasons.includes('NO_AUTHORITATIVE_HUMAN_AUTHORITY_REENTRY_OWNER'));const resumed=await resumeWaitingAdaptiveCapabilities({context:first.context,requestCapability:runtime(c)});assert.equal(resumed.graph.nodes.find(n=>n.nodeId===waiting.nodeId)?.state,'WAITING_AUTHORITY');assert.equal(c.n,0);});
test('absolute invocation ceiling validates load/reservation: 25th allowed, 26th blocked, corrupt restored budgets rejected',()=>{const g=buildTaskGraph(plan()),root=activeTaskGraphNodeForCapability(g,'meta_orchestrator')!;assert.equal(SFI_ADAPTIVE_MAX_CAPABILITY_INVOCATIONS,25);g.invocationBudget={max:25,used:24,remaining:1};assert.deepEqual(validateTaskGraphInvocationBudget(g),[]);assert.equal(reserveTaskGraphInvocation(g,root.nodeId),true);assert.deepEqual(g.invocationBudget,{max:25,used:25,remaining:0});assert.equal(reserveTaskGraphInvocation(g,root.nodeId),false);for(const b of [{max:26,used:0,remaining:26},{max:25,used:3,remaining:23},{max:25,used:-1,remaining:26}]){const bad=buildTaskGraph(plan());bad.invocationBudget=b;assert.throws(()=>taskGraphFromContext({...ctx(),metadata:{taskGraph:bad}}),/TASK_GRAPH_INVOCATION_BUDGET_INVALID/);assert.throws(()=>reserveTaskGraphInvocation(bad,bad.nodes[0].nodeId),/TASK_GRAPH_INVOCATION_BUDGET_INVALID/);}const strict=buildTaskGraph(plan());strict.invocationBudget={max:10,used:7,remaining:3};assert.equal(taskGraphFromContext({...ctx(),metadata:{taskGraph:strict}})?.invocationBudget.used,7);});
test('checkpoint production path persists taskGraph in epistemic_events payload and restore path retains budget/history',()=>{const cycle=fs.readFileSync(path.join(process.cwd(),'src/lib/sfi/cognitive-runtime/cognitiveCycle.ts'),'utf8');assert.match(cycle,/eventName:\s*SFI_UNIVERSAL_COGNITIVE_CHECKPOINT/);assert.match(cycle,/context:\s*checkpointContextProjection\(input\.context\)/);assert.match(cycle,/const storedContext = row\(payload\.context\)/);assert.match(cycle,/mergeCheckpointContext\(context, checkpoint\.context\)/);assert.match(cycle,/taskGraphFromContext\(currentContext\)/);const g=buildTaskGraph(plan(['risk_agent']));g.invocationBudget={max:25,used:9,remaining:16};const node=g.nodes.find(n=>n.capabilityId==='risk_agent')!;transitionTaskGraphNode(g,node.nodeId,'SUPERSEDED',{supersededByNodeId:'replacement'});const persisted=JSON.parse(JSON.stringify({...ctx(),metadata:{taskGraph:g}})) as KernelContext;const restored=taskGraphFromContext(persisted)!;assert.deepEqual(restored.invocationBudget,{max:25,used:9,remaining:16});assert.equal(restored.nodes.find(n=>n.nodeId===node.nodeId)?.state,'SUPERSEDED');assert.equal(restored.nodes.find(n=>n.nodeId===node.nodeId)?.supersededByNodeId,'replacement');});
test('EXPLICIT/AUTO remain compatible',()=>{const explicit=selectCognitiveAutomations({...ctx(),metadata:{requestedAgents:['risk_agent']}});const auto=selectCognitiveAutomations(ctx());assert.equal(explicit.mode,'explicit');assert.ok(explicit.automationIds.includes('risk_agent'));assert.equal(auto.mode,'auto');});
