import type { SfiRegisteredCognitiveAgent, SfiRuntimeModeState } from './types';

const worldVectorTables = ['world_vector_observations', 'worldspect_snapshots'];
const evidenceTables = ['epistemic_events', 'root_evidence_entries', 'sfi_evidence_ledger'];
const memoryTables = ['sfi_amv_memory', 'sfi_graph_nodes', 'graph_nodes'];
const predictionTables = ['sfi_predictive_runs', 'sfi_predictive_learning_events'];
const governanceTables = ['action_proposals', 'logbook_mutations', 'root_audit_events'];
export const SFI_FIELD_TABLES = ['field_cases', 'field_events', 'field_participant_windows'];

export const SFI_COGNITIVE_AGENT_REGISTRY: SfiRegisteredCognitiveAgent[] = [
  {
    id: 'meta_orchestrator',
    name: 'MetaOrchestratorAgent',
    purpose: 'Plan the minimum cognitive task graph required to answer a systemic question.',
    domain: 'governance',
    layer: 'decide',
    listensTo: ['sfi.question.received', 'SFI_TASK_REQUESTED'],
    emits: ['SFI_TASK_CREATED'],
    readsMemory: ['epistemic_events', 'sfi_amv_memory', 'sfi_graph_nodes', 'sfi_predictive_runs'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'contract_coverage', calibration: 'requires downstream reality calibration' },
    authorityLevel: 'advisor',
    simulationAllowed: false,
    humanApprovalRequired: false,
    sourceTables: [...evidenceTables, ...memoryTables, ...predictionTables],
    route: '/api/root/cognitive-runtime',
    operationalMode: false,
    missingCapability: false,
  },
  {
    id: 'temporal_resolver',
    name: 'TemporalResolverAgent',
    purpose: 'Resolve the time coordinate, T0 cutoff, return window, and observable outcome horizon.',
    domain: 'temporal',
    layer: 'reconstruct',
    listensTo: ['SFI_TASK_CREATED', 'phenomenon.registered', 'prediction.created'],
    emits: ['SFI_TEMPORAL_COORDINATE_RESOLVED'],
    readsMemory: ['epistemic_events', 'sfi_predictive_runs', 'field_events'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'timestamp_coverage', calibration: 'prediction outcome windows' },
    authorityLevel: 'analyst',
    simulationAllowed: false,
    humanApprovalRequired: false,
    sourceTables: ['epistemic_events', 'sfi_predictive_runs', 'field_events'],
    route: null,
    operationalMode: false,
    missingCapability: false,
  },
  {
    id: 'evidence_hunter',
    name: 'EvidenceHunterAgent',
    purpose: 'Identify missing evidence required by a task without fabricating observations.',
    domain: 'evidence',
    layer: 'observe',
    listensTo: ['SFI_TASK_CREATED', 'SFI_TEMPORAL_COORDINATE_RESOLVED'],
    emits: ['SFI_EVIDENCE_REQUIREMENT_DECLARED'],
    readsMemory: ['root_evidence_entries', 'sfi_evidence_ledger', 'epistemic_events'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'source_presence_and_lineage', calibration: 'evidence ledger verification' },
    authorityLevel: 'observer',
    simulationAllowed: false,
    humanApprovalRequired: false,
    sourceTables: evidenceTables,
    route: '/api/root/evidence',
    operationalMode: false,
    missingCapability: false,
  },
  {
    id: 'historical_scout',
    name: 'HistoricalScoutAgent',
    purpose: 'Declare historical sources needed for reconstruction from INEGI, DOF, papers, news, archives, and datasets.',
    domain: 'evidence',
    layer: 'reconstruct',
    listensTo: ['SFI_TASK_CREATED', 'SFI_EVIDENCE_REQUIREMENT_DECLARED'],
    emits: ['SFI_HISTORICAL_SOURCE_SET_DECLARED'],
    readsMemory: ['root_evidence_entries', 'sfi_reference_cases', 'epistemic_events'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'source_manifest_completeness', calibration: 'reference case outcomes' },
    authorityLevel: 'observer',
    simulationAllowed: false,
    humanApprovalRequired: false,
    sourceTables: ['root_evidence_entries', 'sfi_reference_cases', 'epistemic_events'],
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
  {
    id: 'phenotype_resolver',
    name: 'PhenotypeResolverAgent',
    purpose: 'Match historical configurations by structure, not by surface similarity.',
    domain: 'evidence',
    layer: 'reconstruct',
    listensTo: ['SFI_HISTORICAL_SOURCE_SET_DECLARED', 'SFI_CONTEXT_COORDINATE_BUILT'],
    emits: ['SFI_PHENOTYPE_RESOLVED'],
    readsMemory: ['sfi_phenomena', 'sfi_reference_cases', 'sfi_graph_nodes', 'graph_nodes'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'configuration_overlap', calibration: 'closed reference cases' },
    authorityLevel: 'analyst',
    simulationAllowed: false,
    humanApprovalRequired: false,
    sourceTables: ['sfi_phenomena', 'sfi_reference_cases', 'sfi_graph_nodes', 'graph_nodes'],
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
  {
    id: 'context_builder',
    name: 'ContextBuilderAgent',
    purpose: 'Build temporal coordinates with actors, forces, constraints, vectors, and tensions.',
    domain: 'evidence',
    layer: 'reconstruct',
    listensTo: ['SFI_TEMPORAL_COORDINATE_RESOLVED', 'SFI_PHENOTYPE_RESOLVED'],
    emits: ['SFI_CONTEXT_COORDINATE_BUILT'],
    readsMemory: ['epistemic_events', 'sfi_graph_nodes', 'field_cases'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'field_slot_completeness', calibration: 'post outcome reconstruction review' },
    authorityLevel: 'analyst',
    simulationAllowed: false,
    humanApprovalRequired: false,
    sourceTables: ['epistemic_events', 'sfi_graph_nodes', 'field_cases'],
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
  {
    id: 'social_field_simulator',
    name: 'SocialFieldSimulator',
    purpose: 'Estimate social state S=f(P,C,T,I) when population, trust, cultural trend, and interaction evidence exists.',
    domain: 'simulation',
    layer: 'simulate',
    listensTo: ['SFI_CONTEXT_COORDINATE_BUILT'],
    emits: ['SFI_SOCIAL_FIELD_SIMULATED'],
    readsMemory: ['epistemic_events', 'sfi_graph_nodes', 'field_cases'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'bounded_variable_coverage', calibration: 'observed social return' },
    authorityLevel: 'analyst',
    simulationAllowed: true,
    humanApprovalRequired: false,
    sourceTables: ['epistemic_events', 'sfi_graph_nodes', 'field_cases'],
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
  {
    id: 'economic_field_simulator',
    name: 'EconomicFieldSimulator',
    purpose: 'Estimate economic state E=f(K,L,R,M) from capital, labor, resources, and market evidence.',
    domain: 'simulation',
    layer: 'simulate',
    listensTo: ['SFI_CONTEXT_COORDINATE_BUILT'],
    emits: ['SFI_ECONOMIC_FIELD_SIMULATED'],
    readsMemory: ['epistemic_events', 'root_evidence_entries', 'field_cases'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'bounded_variable_coverage', calibration: 'observed economic return' },
    authorityLevel: 'analyst',
    simulationAllowed: true,
    humanApprovalRequired: false,
    sourceTables: ['epistemic_events', 'root_evidence_entries', 'field_cases'],
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
  {
    id: 'policy_simulator',
    name: 'PolicySimulator',
    purpose: 'Estimate policy state P=f(G,R,B,A) before any governed intervention is approved.',
    domain: 'simulation',
    layer: 'simulate',
    listensTo: ['SFI_CONTEXT_COORDINATE_BUILT', 'SFI_GOVERNANCE_REVIEW_REQUESTED'],
    emits: ['SFI_POLICY_FIELD_SIMULATED'],
    readsMemory: ['action_proposals', 'root_audit_events', 'epistemic_events'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'governance_constraint_coverage', calibration: 'decision audit outcomes' },
    authorityLevel: 'analyst',
    simulationAllowed: true,
    humanApprovalRequired: false,
    sourceTables: ['action_proposals', 'root_audit_events', 'epistemic_events'],
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
  {
    id: 'cultural_simulator',
    name: 'CulturalSimulator',
    purpose: 'Estimate cultural state C=f(N,S,A,T) from narrative, symbols, attention, and transmission.',
    domain: 'simulation',
    layer: 'simulate',
    listensTo: ['SFI_CONTEXT_COORDINATE_BUILT', 'world_vector.observed'],
    emits: ['SFI_CULTURAL_FIELD_SIMULATED'],
    readsMemory: ['world_vector_observations', 'worldspect_snapshots', 'sfi_amv_memory'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'world_vector_alignment', calibration: 'prediction calibration residuals' },
    authorityLevel: 'analyst',
    simulationAllowed: true,
    humanApprovalRequired: false,
    sourceTables: [...worldVectorTables, 'sfi_amv_memory'],
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
  {
    id: 'psychological_simulator',
    name: 'PsychologicalSimulator',
    purpose: 'Estimate psychological state Psi=f(D,F,M,R) with explicit desire, fear, memory, and reward evidence.',
    domain: 'simulation',
    layer: 'simulate',
    listensTo: ['SFI_CONTEXT_COORDINATE_BUILT', 'moph.session.observed'],
    emits: ['SFI_PSYCHOLOGICAL_FIELD_SIMULATED'],
    readsMemory: ['sfi_moph_sessions', 'sfi_amv_memory', 'epistemic_events'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'declared_object_and_trace_coverage', calibration: 'MOP-H return checks' },
    authorityLevel: 'analyst',
    simulationAllowed: true,
    humanApprovalRequired: false,
    sourceTables: ['sfi_moph_sessions', 'sfi_amv_memory', 'epistemic_events'],
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
  {
    id: 'trajectory_agent',
    name: 'TrajectoryAgent',
    purpose: 'Compare baseline, observed drift, and possible trajectory loss without changing source data.',
    domain: 'temporal',
    layer: 'project',
    listensTo: ['SFI_CONTEXT_COORDINATE_BUILT', 'SFI_FIELD_SIMULATION_COMPLETED'],
    emits: ['SFI_TRAJECTORY_ASSESSED'],
    readsMemory: ['sfi_predictive_runs', 'sfi_predictive_learning_events', 'epistemic_events'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'time_series_and_residual_coverage', calibration: 'prediction outcome residuals' },
    authorityLevel: 'analyst',
    simulationAllowed: true,
    humanApprovalRequired: false,
    sourceTables: predictionTables,
    route: null,
    operationalMode: false,
    missingCapability: false,
  },
  {
    id: 'reality_calibration',
    name: 'RealityCalibrationAgent',
    purpose: 'Return every prediction to observed outcome, error, model adjustment, and next prediction readiness.',
    domain: 'evidence',
    layer: 'learn',
    listensTo: ['prediction.outcome.recorded', 'SFI_TRAJECTORY_ASSESSED'],
    emits: ['SFI_REALITY_CALIBRATED'],
    readsMemory: ['sfi_predictive_runs', 'sfi_predictive_learning_events', 'epistemic_events'],
    writesMemory: ['sfi_predictive_learning_events', 'epistemic_events'],
    confidenceModel: { method: 'absolute_error', calibration: 'model weight update audit' },
    authorityLevel: 'analyst',
    simulationAllowed: false,
    humanApprovalRequired: false,
    sourceTables: predictionTables,
    route: '/api/predictive-engine/runs/[id]/outcome',
    operationalMode: false,
    missingCapability: false,
  },
  {
    id: 'risk_agent',
    name: 'RiskAgent',
    purpose: 'Identify downside, missing evidence, and governance blockers before action.',
    domain: 'governance',
    layer: 'decide',
    listensTo: ['SFI_TRAJECTORY_ASSESSED', 'SFI_POLICY_FIELD_SIMULATED'],
    emits: ['SFI_RISK_DECLARED'],
    readsMemory: ['action_proposals', 'sfi_evidence_ledger', 'root_audit_events'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'blocker_count_and_severity', calibration: 'decision audit outcomes' },
    authorityLevel: 'advisor',
    simulationAllowed: true,
    humanApprovalRequired: false,
    sourceTables: governanceTables,
    route: null,
    operationalMode: false,
    missingCapability: false,
  },
  {
    id: 'opportunity_agent',
    name: 'OpportunityAgent',
    purpose: 'Identify upside windows only after evidence and risk states are declared.',
    domain: 'governance',
    layer: 'decide',
    listensTo: ['SFI_RISK_DECLARED', 'SFI_TRAJECTORY_ASSESSED'],
    emits: ['SFI_OPPORTUNITY_DECLARED'],
    readsMemory: ['sfi_graph_nodes', 'sfi_amv_memory', 'action_proposals'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'evidence_supported_windowing', calibration: 'observed return windows' },
    authorityLevel: 'advisor',
    simulationAllowed: true,
    humanApprovalRequired: false,
    sourceTables: ['sfi_graph_nodes', 'sfi_amv_memory', 'action_proposals'],
    route: null,
    operationalMode: false,
    missingCapability: false,
  },
  {
    id: 'multi_stakeholder_bootstrap',
    name: 'MultiStakeholderBootstrapAgent',
    purpose: 'Simulate operator, participant, and system divergence before a governed intervention proceeds.',
    domain: 'governance',
    layer: 'decide',
    listensTo: ['SFI_OPPORTUNITY_DECLARED', 'SFI_RISK_DECLARED'],
    emits: ['SFI_MULTI_STAKEHOLDER_SIMULATED'],
    readsMemory: ['action_proposals', 'field_cases', 'sfi_moph_sessions', 'epistemic_events'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'stakeholder_divergence_delta', calibration: 'post intervention outcomes' },
    authorityLevel: 'advisor',
    simulationAllowed: true,
    humanApprovalRequired: true,
    sourceTables: ['action_proposals', 'field_cases', 'sfi_moph_sessions', 'epistemic_events'],
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
  {
    id: 'project_execution_manager',
    name: 'ProjectExecutionManagerAgent',
    purpose: 'Manage coherence across objectives, dependencies, agents, missing evidence, and risk.',
    domain: 'governance',
    layer: 'act',
    listensTo: ['SFI_TASK_CREATED', 'SFI_MULTI_STAKEHOLDER_SIMULATED', 'root.action.completed'],
    emits: ['SFI_PROJECT_EXECUTION_STATE_DECLARED'],
    readsMemory: ['action_proposals', 'logbook_mutations', 'root_audit_events', 'epistemic_events'],
    writesMemory: ['epistemic_events'],
    confidenceModel: { method: 'dependency_and_blocker_coverage', calibration: 'audit closure rate' },
    authorityLevel: 'advisor',
    simulationAllowed: true,
    humanApprovalRequired: true,
    sourceTables: governanceTables,
    route: null,
    operationalMode: false,
    missingCapability: true,
  },
];

export const SFI_COGNITIVE_RUNTIME_MODES: Array<Omit<SfiRuntimeModeState, 'status' | 'readsMemory' | 'writesMemory' | 'warning'>> = [
  {
    id: 'passive_field_observation',
    name: 'Passive Field Observation Layer',
    principle: 'Observe does not modify.',
    emits: ['SFI_FIELD_STATE_OBSERVED'],
  },
];

export const SFI_LAYER_QUESTIONS: Record<SfiRegisteredCognitiveAgent['layer'], string> = {
  observe: 'What is happening?',
  reconstruct: 'What historical context is missing?',
  simulate: 'What changes if a variable changes?',
  understand: 'What connections exist?',
  project: 'What trajectory is forming?',
  decide: 'Should it be done?',
  act: 'How does it execute under governance?',
  learn: 'What returned from reality?',
};

export const SFI_RUNTIME_SOURCE_TABLES = [
  ...new Set(SFI_COGNITIVE_AGENT_REGISTRY.flatMap((agent) => agent.sourceTables).concat(SFI_FIELD_TABLES)),
].sort();
