import { AMV_DEFAULT_POLICY } from '../../core/amvDecisionPolicy'
import { AMV_EVIDENCE_TRUST_LEVELS } from '../../core/evidenceTypes'
import { AMV_FIELD_OPERATORS } from '../../core/fieldOperatorTypes'
import { AMV_FOCUS_VARIABLES } from '../../core/focusVariableTypes'
import { AMV_OBSERVABLE_OBJECTS } from '../../core/observableObjectTypes'
import { AMV_OBSERVATION_MODES } from '../../core/observationModes'
import { AMV_OUTPUT_MODES } from '../../core/outputModeTypes'
import { AMV_REPORT_REGIMES } from '../../core/regimeTypes'
import type { AmvDashboardSpec } from '../../core/dashboardSpecTypes'

export const rootDashboardSpec = {
  id: 'root.dashboard',
  instrumentId: 'root.instrument',
  scope: 'root',
  title: 'ROOT como instrumento AMV',
  visibleFormat: ['evento', 'resultado', 'efecto', 'ventana', 'ruta_unica'],
  lanes: ['field', 'attractor', 'ejector', 'wsv', 'mihm', 'governance', 'logbook', 'amv'],
  observationModes: [...AMV_OBSERVATION_MODES],
  fieldOperators: [...AMV_FIELD_OPERATORS],
  outputModes: [...AMV_OUTPUT_MODES],
  reportRegimes: [...AMV_REPORT_REGIMES],
  observableObjects: [...AMV_OBSERVABLE_OBJECTS],
  focusVariables: [...AMV_FOCUS_VARIABLES],
  evidenceTrust: [...AMV_EVIDENCE_TRUST_LEVELS],
  instrument: {
    id: 'root.instrument',
    name: 'ROOT',
    ontologicalQuestion: 'Que esta pasando con mi sistema hoy, que lo sostiene, que lo contamina y que debo hacer?',
    observedObject: 'Observatorio Personal Raiz de Aptymok',
    scope: 'root',
    observationModes: [...AMV_OBSERVATION_MODES],
    fieldOperators: [...AMV_FIELD_OPERATORS],
    outputModes: [...AMV_OUTPUT_MODES],
    reportRegimes: [...AMV_REPORT_REGIMES],
    observableObjects: [...AMV_OBSERVABLE_OBJECTS],
    focusVariables: [...AMV_FOCUS_VARIABLES],
    evidenceTrust: [...AMV_EVIDENCE_TRUST_LEVELS],
    archiveLayers: ['sfi_archive', 'living_observatory', 'attractor', 'sandbox', 'technical_audit'],
    sources: [
      {
        id: 'rootFieldState',
        label: 'Estado del Campo ROOT',
        trust: 'degraded',
        reason: 'Depende de contexto visible y seed local; no consulta Supabase en este runtime.',
      },
      {
        id: 'rootMihmTranslator',
        label: 'Lectura MIHM basal',
        trust: 'derived',
        reason: 'Declara objeto basal cuando no hay objeto focal nuevo.',
      },
      {
        id: 'rootGovernanceTranslator',
        label: 'Lectura de gobernanza ROOT',
        trust: 'derived',
        reason: 'Traduce riesgo de accion desde el mensaje y el contexto visible.',
      },
    ],
    tables: [
      {
        id: 'context.seed',
        label: 'Contexto visible recibido por AMV',
        purpose: 'Sostener lectura sin escribir ni leer tablas productivas desde Fase 14.',
        trust: 'derived',
        access: 'read',
      },
    ],
    metrics: [
      {
        id: 'sourceState',
        label: 'Confiabilidad de fuente',
        meaning: 'Indica si la lectura viene observada o degradada.',
        source: 'rootFieldState',
        requiredEvidence: 'Contexto visible con sourceState observado.',
      },
      {
        id: 'risk',
        label: 'Riesgo operativo',
        meaning: 'Define si AMV observa, pide cierre o congela ejecucion.',
        source: 'rootScope.decide',
        requiredEvidence: 'Mensaje del usuario, gobernanza y eyectores detectados.',
      },
      {
        id: 'mihmBaseline',
        label: 'MIHM basal',
        meaning: 'Declara el objeto observado cuando no existe lectura focal nueva.',
        source: 'rootMihmTranslator',
        requiredEvidence: 'Objeto, nodo y baseline declarados o fallback basal.',
      },
    ],
    requiredAgents: [
      'amv',
      'longitudinal',
      'cognitive-twin',
      'metrics',
      'auditor',
      'moph',
    ],
    allowedActions: [
      {
        id: 'root.observe',
        label: 'Observar evidencia visible',
        consequence: 'AMV conserva ruta unica y no ejecuta cambios.',
        risk: 'low',
        requiresRootApproval: false,
      },
      {
        id: 'root.close',
        label: 'Cerrar con criterio verificable',
        consequence: 'AMV puede recomendar cierre, pero no lo ejecuta.',
        risk: 'medium',
        requiresRootApproval: true,
      },
      {
        id: 'root.freeze',
        label: 'Congelar riesgo',
        consequence: 'AMV bloquea recomendacion de ejecucion hasta revision humana.',
        risk: 'hard_stop',
        requiresRootApproval: true,
      },
    ],
    prohibitedActions: [
      {
        id: 'root.write_database',
        label: 'Escribir en Supabase',
        consequence: 'Fuera de Fase 14; requiere autorizacion explicita y fase propia.',
        risk: 'hard_stop',
        requiresRootApproval: true,
      },
      {
        id: 'root.spawn_chat',
        label: 'Crear otro chat',
        consequence: 'Duplicaria AMV y contaminaria la interfaz ROOT.',
        risk: 'high',
        requiresRootApproval: true,
      },
      {
        id: 'root.create_dashboard_clone',
        label: 'Crear dashboard paralelo',
        consequence: 'Romperia el contrato de instrumento por spec.',
        risk: 'high',
        requiresRootApproval: true,
      },
    ],
    panels: [
      {
        id: 'root.field',
        title: 'Estado del Campo',
        question: 'Como esta el sistema hoy?',
        observationMode: 'focus',
        fieldOperators: ['signal', 'pattern', 'latency', 'coherence', 'dissonance'],
        outputModes: ['field_reading', 'briefing', 'early_warning'],
        reportRegimes: ['contemplative', 'saturated', 'dissonant'],
        observableObjects: ['persona', 'ecosistema', 'senal', 'evidencia', 'decision', 'accion'],
        focusVariables: ['riesgo', 'latencia', 'deuda', 'ejecucion'],
        evidenceTrust: ['verified', 'declared', 'inferred'],
        observes: 'Regimen, senales vivas y degradacion visible.',
        sources: ['rootFieldState'],
        metrics: ['sourceState'],
        actions: ['root.observe'],
        risk: 'medium',
        minimumEvidence: 'Contexto visible con fuente declarada.',
        emptyState: 'Sin lectura suficiente; usar con cautela.',
      },
      {
        id: 'root.attractor',
        title: 'Atractor',
        question: 'Hacia donde tiende el sistema?',
        observationMode: 'focus',
        fieldOperators: ['attractor', 'threshold', 'pattern', 'closure'],
        outputModes: ['attractor_map', 'field_reading', 'decision_record'],
        reportRegimes: ['emergent_attractor', 'coupling'],
        observableObjects: ['fenomeno', 'decision', 'accion', 'evidencia', 'cluster'],
        focusVariables: ['protoatractor', 'eyector', 'deuda', 'ejecucion'],
        evidenceTrust: ['verified', 'declared', 'inferred'],
        observes: 'Propuestas visibles y peso direccional disponible.',
        sources: ['rootAttractorState', 'rootTwinProposalTranslator'],
        metrics: ['risk'],
        actions: ['root.observe', 'root.close'],
        risk: 'medium',
        minimumEvidence: 'Propuesta o evidencia direccional con origen visible.',
        emptyState: 'Sin atractor observado.',
      },
      {
        id: 'root.ejector',
        title: 'Eyectores',
        question: 'Que esta contaminando o expulsando energia?',
        observationMode: 'focus',
        fieldOperators: ['ejector', 'contamination', 'threshold', 'dissonance', 'closure'],
        outputModes: ['ejector_map', 'risk_register', 'early_warning'],
        reportRegimes: ['active_ejector', 'dissonant', 'extractive'],
        observableObjects: ['fenomeno', 'senal', 'decision', 'accion', 'red'],
        focusVariables: ['eyector', 'riesgo', 'latencia', 'friccion_institucional'],
        evidenceTrust: ['verified', 'declared', 'inferred', 'audit'],
        observes: 'Riesgo, cierre pendiente y hard stop operativo.',
        sources: ['rootEjectorDetector'],
        metrics: ['risk'],
        actions: ['root.freeze', 'root.close'],
        risk: 'high',
        minimumEvidence: 'Senal de riesgo, bloqueo, cierre o override.',
        emptyState: 'Sin eyector dominante declarado.',
      },
      {
        id: 'root.wsv',
        title: 'WorldSpect',
        question: 'Como esta el mundo observado?',
        observationMode: 'worldspect',
        fieldOperators: ['signal', 'phenomenon', 'cluster', 'pattern'],
        outputModes: ['field_reading', 'policy_memo', 'scenario_matrix'],
        reportRegimes: ['contemplative', 'saturated', 'proto_critical'],
        observableObjects: ['institucion', 'campana', 'red', 'municipio', 'ecosistema', 'fenomeno'],
        focusVariables: ['cultural', 'friccion_institucional', 'riesgo'],
        evidenceTrust: ['verified', 'declared', 'inferred'],
        observes: 'Confiabilidad de la lectura externa visible.',
        sources: ['rootWsvTranslator'],
        metrics: ['sourceState'],
        actions: ['root.observe'],
        risk: 'medium',
        minimumEvidence: 'Lectura WorldSpect con estado y timestamp si existe.',
        emptyState: 'No hay lectura WorldSpect suficiente.',
      },
      {
        id: 'root.mihm',
        title: 'MIHM',
        question: 'Que objeto esta siendo observado homeostaticamente?',
        observationMode: 'mihm',
        fieldOperators: ['phenomenon', 'coherence', 'latency', 'memory'],
        outputModes: ['field_reading', 'phenomenon_card', 'creative_brief'],
        reportRegimes: ['contemplative', 'ghost', 'coupling'],
        observableObjects: ['persona', 'cancion', 'demo', 'artista', 'senal', 'documento'],
        focusVariables: ['ritmo', 'genero', 'letra', 'densidad_emocional', 'energia_corporal', 'latencia'],
        evidenceTrust: ['verified', 'declared', 'inferred'],
        observes: 'Objeto, nodo, baseline y regimen basal.',
        sources: ['rootMihmTranslator'],
        metrics: ['mihmBaseline'],
        actions: ['root.observe'],
        risk: 'low',
        minimumEvidence: 'Objeto observado declarado o fallback basal Aptymok / n_0.',
        emptyState: 'MIHM basal sin evidencia nueva.',
      },
      {
        id: 'root.governance',
        title: 'Gobernanza',
        question: 'Que requiere revision humana antes de actuar?',
        observationMode: 'audit',
        fieldOperators: ['verification', 'threshold', 'intervention', 'closure'],
        outputModes: ['audit_report', 'risk_register', 'decision_record', 'intervention_plan'],
        reportRegimes: ['proto_critical', 'dissonant', 'active_ejector'],
        observableObjects: ['decision', 'accion', 'documento', 'evidencia', 'institucion'],
        focusVariables: ['friccion_institucional', 'riesgo', 'ejecucion'],
        evidenceTrust: ['verified', 'declared', 'audit', 'unknown'],
        observes: 'Zero Trust, Risk Management y necesidad de aprobacion raiz.',
        sources: ['rootGovernanceTranslator'],
        metrics: ['risk'],
        actions: ['root.freeze'],
        risk: 'hard_stop',
        minimumEvidence: 'Accion con impacto, publicacion, schema, migracion u override.',
        emptyState: 'Sin bloqueo de gobernanza visible.',
      },
      {
        id: 'root.logbook',
        title: 'Bitacora',
        question: 'Que registro visible sostiene la lectura?',
        observationMode: 'audit',
        fieldOperators: ['memory', 'verification', 'debt', 'latency'],
        outputModes: ['evidence_packet', 'audit_report', 'decision_record'],
        reportRegimes: ['ghost', 'contemplative', 'saturated'],
        observableObjects: ['documento', 'evidencia', 'decision', 'accion', 'senal'],
        focusVariables: ['latencia', 'deuda', 'ejecucion', 'riesgo'],
        evidenceTrust: ['verified', 'declared', 'audit', 'unknown'],
        observes: 'Eventos recientes y ausencia de registro.',
        sources: ['rootLogbookTranslator'],
        metrics: ['sourceState'],
        actions: ['root.observe'],
        risk: 'medium',
        minimumEvidence: 'Evento reciente con origen visible.',
        emptyState: 'No exigir seleccion; si no hay registro, declarar ausencia.',
      },
      {
        id: 'root.amv',
        title: 'AMV',
        question: 'Que propone, duda o cuestiona el interlocutor?',
        observationMode: 'focus',
        fieldOperators: ['attractor', 'ejector', 'verification', 'closure', 'intervention'],
        outputModes: ['briefing', 'field_reading', 'decision_record', 'intervention_plan'],
        reportRegimes: ['emergent_attractor', 'active_ejector', 'dissonant'],
        observableObjects: ['persona', 'decision', 'accion', 'evidencia', 'fenomeno'],
        focusVariables: ['riesgo', 'ejecucion', 'deuda', 'protoatractor', 'eyector'],
        evidenceTrust: ['verified', 'declared', 'inferred', 'unknown'],
        observes: 'Evento, resultado, efecto, ventana y ruta unica.',
        sources: ['rootScope.decide'],
        metrics: ['risk'],
        actions: ['root.observe', 'root.close', 'root.freeze'],
        risk: 'medium',
        minimumEvidence: 'Mensaje del usuario y contexto visible del scope root.',
        emptyState: 'AMV no cambia ruta sin evidencia suficiente.',
      },
    ],
    risk: 'medium',
    minimumEvidence: 'Contexto visible, fuente declarada y politica de respuesta AMV.',
    amvBriefing: 'ROOT observa el sistema raiz de Aptymok. AMV traduce, pregunta y propone ruta unica; no ejecuta, no escribe y no crea superficies paralelas.',
    responsePolicy: {
      ...AMV_DEFAULT_POLICY,
      visibleStructure: ['evento', 'resultado', 'efecto', 'ventana', 'ruta_unica'],
      forbiddenClaims: [
        'accion ejecutada sin testigo',
        'evidencia externa no observada',
        'metricas inventadas',
        'segunda ruta dominante',
      ],
      uncertaintyLabel: 'sin lectura suficiente',
    },
  },
  panels: [
    {
      id: 'root.field',
      title: 'Estado del Campo',
      question: 'Como esta el sistema hoy?',
      observationMode: 'focus',
      fieldOperators: ['signal', 'pattern', 'latency', 'coherence', 'dissonance'],
      outputModes: ['field_reading', 'briefing', 'early_warning'],
      reportRegimes: ['contemplative', 'saturated', 'dissonant'],
      observableObjects: ['persona', 'ecosistema', 'senal', 'evidencia', 'decision', 'accion'],
      focusVariables: ['riesgo', 'latencia', 'deuda', 'ejecucion'],
      evidenceTrust: ['verified', 'declared', 'inferred'],
      observes: 'Regimen, senales vivas y degradacion visible.',
      sources: ['rootFieldState'],
      metrics: ['sourceState'],
      actions: ['root.observe'],
      risk: 'medium',
      minimumEvidence: 'Contexto visible con fuente declarada.',
      emptyState: 'Sin lectura suficiente; usar con cautela.',
      lane: 'field',
      order: 10,
      renderMode: 'summary',
    },
    {
      id: 'root.attractor',
      title: 'Atractor',
      question: 'Hacia donde tiende el sistema?',
      observationMode: 'focus',
      fieldOperators: ['attractor', 'threshold', 'pattern', 'closure'],
      outputModes: ['attractor_map', 'field_reading', 'decision_record'],
      reportRegimes: ['emergent_attractor', 'coupling'],
      observableObjects: ['fenomeno', 'decision', 'accion', 'evidencia', 'cluster'],
      focusVariables: ['protoatractor', 'eyector', 'deuda', 'ejecucion'],
      evidenceTrust: ['verified', 'declared', 'inferred'],
      observes: 'Propuestas visibles y peso direccional disponible.',
      sources: ['rootAttractorState', 'rootTwinProposalTranslator'],
      metrics: ['risk'],
      actions: ['root.observe', 'root.close'],
      risk: 'medium',
      minimumEvidence: 'Propuesta o evidencia direccional con origen visible.',
      emptyState: 'Sin atractor observado.',
      lane: 'attractor',
      order: 20,
      renderMode: 'evidence',
    },
    {
      id: 'root.ejector',
      title: 'Eyectores',
      question: 'Que esta contaminando o expulsando energia?',
      observationMode: 'focus',
      fieldOperators: ['ejector', 'contamination', 'threshold', 'dissonance', 'closure'],
      outputModes: ['ejector_map', 'risk_register', 'early_warning'],
      reportRegimes: ['active_ejector', 'dissonant', 'extractive'],
      observableObjects: ['fenomeno', 'senal', 'decision', 'accion', 'red'],
      focusVariables: ['eyector', 'riesgo', 'latencia', 'friccion_institucional'],
      evidenceTrust: ['verified', 'declared', 'inferred', 'audit'],
      observes: 'Riesgo, cierre pendiente y hard stop operativo.',
      sources: ['rootEjectorDetector'],
      metrics: ['risk'],
      actions: ['root.freeze', 'root.close'],
      risk: 'high',
      minimumEvidence: 'Senal de riesgo, bloqueo, cierre o override.',
      emptyState: 'Sin eyector dominante declarado.',
      lane: 'ejector',
      order: 30,
      renderMode: 'action',
    },
    {
      id: 'root.wsv',
      title: 'WorldSpect',
      question: 'Como esta el mundo observado?',
      observationMode: 'worldspect',
      fieldOperators: ['signal', 'phenomenon', 'cluster', 'pattern'],
      outputModes: ['field_reading', 'policy_memo', 'scenario_matrix'],
      reportRegimes: ['contemplative', 'saturated', 'proto_critical'],
      observableObjects: ['institucion', 'campana', 'red', 'municipio', 'ecosistema', 'fenomeno'],
      focusVariables: ['cultural', 'friccion_institucional', 'riesgo'],
      evidenceTrust: ['verified', 'declared', 'inferred'],
      observes: 'Confiabilidad de la lectura externa visible.',
      sources: ['rootWsvTranslator'],
      metrics: ['sourceState'],
      actions: ['root.observe'],
      risk: 'medium',
      minimumEvidence: 'Lectura WorldSpect con estado y timestamp si existe.',
      emptyState: 'No hay lectura WorldSpect suficiente.',
      lane: 'wsv',
      order: 40,
      renderMode: 'evidence',
    },
    {
      id: 'root.mihm',
      title: 'MIHM',
      question: 'Que objeto esta siendo observado homeostaticamente?',
      observationMode: 'mihm',
      fieldOperators: ['phenomenon', 'coherence', 'latency', 'memory'],
      outputModes: ['field_reading', 'phenomenon_card', 'creative_brief'],
      reportRegimes: ['contemplative', 'ghost', 'coupling'],
      observableObjects: ['persona', 'cancion', 'demo', 'artista', 'senal', 'documento'],
      focusVariables: ['ritmo', 'genero', 'letra', 'densidad_emocional', 'energia_corporal', 'latencia'],
      evidenceTrust: ['verified', 'declared', 'inferred'],
      observes: 'Objeto, nodo, baseline y regimen basal.',
      sources: ['rootMihmTranslator'],
      metrics: ['mihmBaseline'],
      actions: ['root.observe'],
      risk: 'low',
      minimumEvidence: 'Objeto observado declarado o fallback basal Aptymok / n_0.',
      emptyState: 'MIHM basal sin evidencia nueva.',
      lane: 'mihm',
      order: 50,
      renderMode: 'summary',
    },
    {
      id: 'root.governance',
      title: 'Gobernanza',
      question: 'Que requiere revision humana antes de actuar?',
      observationMode: 'audit',
      fieldOperators: ['verification', 'threshold', 'intervention', 'closure'],
      outputModes: ['audit_report', 'risk_register', 'decision_record', 'intervention_plan'],
      reportRegimes: ['proto_critical', 'dissonant', 'active_ejector'],
      observableObjects: ['decision', 'accion', 'documento', 'evidencia', 'institucion'],
      focusVariables: ['friccion_institucional', 'riesgo', 'ejecucion'],
      evidenceTrust: ['verified', 'declared', 'audit', 'unknown'],
      observes: 'Zero Trust, Risk Management y necesidad de aprobacion raiz.',
      sources: ['rootGovernanceTranslator'],
      metrics: ['risk'],
      actions: ['root.freeze'],
      risk: 'hard_stop',
      minimumEvidence: 'Accion con impacto, publicacion, schema, migracion u override.',
      emptyState: 'Sin bloqueo de gobernanza visible.',
      lane: 'governance',
      order: 60,
      renderMode: 'audit',
    },
    {
      id: 'root.logbook',
      title: 'Bitacora',
      question: 'Que registro visible sostiene la lectura?',
      observationMode: 'audit',
      fieldOperators: ['memory', 'verification', 'debt', 'latency'],
      outputModes: ['evidence_packet', 'audit_report', 'decision_record'],
      reportRegimes: ['ghost', 'contemplative', 'saturated'],
      observableObjects: ['documento', 'evidencia', 'decision', 'accion', 'senal'],
      focusVariables: ['latencia', 'deuda', 'ejecucion', 'riesgo'],
      evidenceTrust: ['verified', 'declared', 'audit', 'unknown'],
      observes: 'Eventos recientes y ausencia de registro.',
      sources: ['rootLogbookTranslator'],
      metrics: ['sourceState'],
      actions: ['root.observe'],
      risk: 'medium',
      minimumEvidence: 'Evento reciente con origen visible.',
      emptyState: 'No exigir seleccion; si no hay registro, declarar ausencia.',
      lane: 'logbook',
      order: 70,
      renderMode: 'evidence',
    },
    {
      id: 'root.amv',
      title: 'AMV',
      question: 'Que propone, duda o cuestiona el interlocutor?',
      observationMode: 'focus',
      fieldOperators: ['attractor', 'ejector', 'verification', 'closure', 'intervention'],
      outputModes: ['briefing', 'field_reading', 'decision_record', 'intervention_plan'],
      reportRegimes: ['emergent_attractor', 'active_ejector', 'dissonant'],
      observableObjects: ['persona', 'decision', 'accion', 'evidencia', 'fenomeno'],
      focusVariables: ['riesgo', 'ejecucion', 'deuda', 'protoatractor', 'eyector'],
      evidenceTrust: ['verified', 'declared', 'inferred', 'unknown'],
      observes: 'Evento, resultado, efecto, ventana y ruta unica.',
      sources: ['rootScope.decide'],
      metrics: ['risk'],
      actions: ['root.observe', 'root.close', 'root.freeze'],
      risk: 'medium',
      minimumEvidence: 'Mensaje del usuario y contexto visible del scope root.',
      emptyState: 'AMV no cambia ruta sin evidencia suficiente.',
      lane: 'amv',
      order: 80,
      renderMode: 'summary',
    },
  ],
  defaultMihm: {
    object: 'Aptymok',
    node: 'n_0',
    baseline: 'MIHM basal',
  },
} satisfies AmvDashboardSpec
