export const SFI_DT_EXP_001_FREEZE = {
  contract: 'SFI-DT-EXP-001-FREEZE-1.0',
  protocol: 'SFI-DT-1.0',
  status: 'EXPERIMENTALLY_FROZEN',
  registrationStatus: 'AWAITING_NATURALISTIC_TARGET',
  sourceLegacyPr: 220,
  portPolicy: 'SCIENTIFIC_CONTRACT_ONLY',
  claimBoundary: {
    nSubjects: 1,
    allowsPopulationGeneralization: false,
    allowsPhenomenalClaims: false,
    allowsIdentityEquivalenceClaims: false,
    allowsCausalSuperiorityClaims: false,
  },
  primaryEndpoint: 'validated_structural_fidelity',
  primaryContrast: 'CT_FULL-B5_RULE_STRUCTURE',
  arms: [
    'B0_BASE',
    'B1_RAW_HISTORY',
    'B2_MEMORY',
    'B3_CDT',
    'B4_PATTERNS',
    'B5_RULE_STRUCTURE',
    'CT_FULL',
  ],
  armDefinitions: {
    B0_BASE: 'current case + admissible current evidence',
    B1_RAW_HISTORY: 'B0 + temporally admissible raw history',
    B2_MEMORY: 'B1 + verified/canonical memory',
    B3_CDT: 'B2 + prior admissible Decision Transfer traces',
    B4_PATTERNS: 'B3 + recurrent patterns',
    B5_RULE_STRUCTURE: 'B4 + approved rule/constraint/exception structure',
    CT_FULL: 'B5 + governed operating-state/context machinery',
  },
  structuralWeights: {
    disposition: 0.45,
    operations: 0.25,
    relevantVariables: 0.15,
    rejectedConditions: 0.05,
    decisionChangeCues: 0.10,
  },
  epistemicBoundary: {
    validatingClasses: ['OBSERVED', 'VERIFIED_CONTRAST'],
    diagnosticOnlyClasses: ['SIMULATED', 'DERIVED', 'INFERRED'],
    missingEmpiricalBoundaryMetric: null,
    blockedMeansInsufficientEvidence: true,
    simulationCanSatisfyValidationGate: false,
    automaticRulePromotion: false,
    automaticMemoryMutation: false,
  },
  confirmatoryExecution: {
    targetMustBeRegisteredPreReveal: true,
    targetMustOccurAfterCutoff: true,
    contextMustBeFrozenPreReveal: true,
    evidencePoolMustBeFrozenBeforeScoring: true,
    manualEvidenceCountsAllowed: false,
    requiresCurrentContextReceipt: true,
    requiresCurrentTimingProof: true,
    executionStateWithoutRegisteredTarget: 'BLOCKED',
  },
  targetRegistration: {
    state: 'PENDING_PRE_TARGET_REGISTRATION',
    targetTraceId: null,
    targetCommitmentSha256: null,
    cutoffAt: null,
    registeredAt: null,
  },
} as const;

export type SfiDecisionTransferExperimentFreeze = typeof SFI_DT_EXP_001_FREEZE;
