import type { RootSovereignState, RootRow } from '@/lib/root/sovereign/rootSovereignState';
import type { RootSelection } from '../sovereignTypes';
import { CalibrationMatrix } from '../visual/CalibrationMatrix';
import { PredictionIntervalPlot } from '../visual/PredictionIntervalPlot';
import { PredictionTimeline } from '../visual/PredictionTimeline';

export function RootPredictionsView({ state, onSelect }: { state: RootSovereignState; onSelect: (selection: RootSelection) => void }) {
  const select = (kind: string, row: RootRow, source: string) => onSelect({ kind, id: String(row.id ?? row.hypothesis_id ?? 'SIN ID'), title: String(row.subject ?? row.prediccion_explicita ?? row.name ?? 'Prediction'), source, observedAt: typeof row.updated_at === 'string' ? row.updated_at : typeof row.created_at === 'string' ? row.created_at : null, confidence: typeof row.confidence === 'number' ? row.confidence : typeof row.probabilidad_estimativa === 'number' ? row.probabilidad_estimativa : null, evidenceIds: Array.isArray(row.evidence_ids) ? row.evidence_ids as string[] : [], warning: null, data: row });
  return <section className="rs-view"><div className="rs-view-title"><span>PREDICTIONS</span><h1>PREDICTIVE ENGINE</h1><p>Modelos calibrados y contrato manual legacy permanecen separados.</p></div>{state.predictions.error ? <div className="rs-source-warning">FUENTE DEGRADADA · {state.predictions.error}</div> : null}<div className="rs-prediction-grid"><article><header>INTERVAL PLOT</header><PredictionIntervalPlot runs={state.predictions.data.runs} /></article><article><header>DUE TIMELINE</header><PredictionTimeline runs={state.predictions.data.runs} /></article><article><header>CALIBRATION MATRIX</header><CalibrationMatrix models={state.predictions.data.models} /></article><article><header>RUNS / OUTCOMES</header><div className="rs-card-list">{state.predictions.data.runs.map((run) => <button type="button" key={String(run.id)} onClick={() => select('predictive run', run, 'sfi_predictive_runs')}><span>{String(run.status ?? 'SIN DATO')}</span><strong>{String(run.subject ?? run.id)}</strong><em>{String(run.due_at ?? 'SIN VENTANA').slice(0, 16)}</em></button>)}</div></article></div><div className="rs-view-title secondary"><span>LEGACY</span><h2>MANUAL PROBABILITY CONTRACT</h2></div><div className="rs-card-list horizontal">{state.predictions.data.legacyEntries.length ? state.predictions.data.legacyEntries.map((entry) => <button type="button" key={String(entry.id)} onClick={() => select('legacy prediction', entry, 'sfi_prediction_entries')}><span>LEGACY · {String(entry.estado_observacion ?? 'SIN DATO')}</span><strong>{String(entry.prediccion_explicita ?? entry.hypothesis_id)}</strong><em>{typeof entry.probabilidad_estimativa === 'number' ? `HUMAN P ${entry.probabilidad_estimativa}` : 'NO MEDIDO'}</em></button>) : <div className="rs-empty"><b>SIN PREDICCIONES LEGACY</b></div>}</div></section>;
}
