import type { FieldPattern } from './patternModel';

export const criticalSystemsPatterns: FieldPattern[] = [
  {
    id: 'cs-000-sistemas-que-no-pueden-fallar',
    nombre: 'Sistemas que no pueden permitirse fallar',
    palabra: 'Umbral',
    oracion_visible: 'El sistema parece estable, pero ya acumula falla.',
    que_detecta: 'Degradacion silenciosa en sistemas criticos con narrativa oficial estable.',
    que_lo_activa: ['sistema critico', 'no puede fallar', 'estabilidad aparente', 'degradacion silenciosa'],
    nodos_relacionados: ['friccion_sistemica', 'trazabilidad', 'mihm', 'bitacora'],
    accion_sugerida: 'Separar umbral oficial de umbral real',
    nivel_friccion: 5,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-001-decisiones-que-nadie-tomo',
    nombre: 'Decisiones que nadie tomo',
    palabra: 'Acumulacion',
    oracion_visible: 'Nadie decidio, pero el sistema avanzo igual.',
    que_detecta: 'Cristalizacion de decisiones por acumulacion de omisiones.',
    que_lo_activa: ['nadie decidio', 'zona gris', 'se acumulo', 'se volvio decision'],
    nodos_relacionados: ['bitacora', 'trazabilidad', 'deuda_decision', 'gobernanza'],
    accion_sugerida: 'Registrar la decision implicita',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-002-costo-real-de-adoptable',
    nombre: 'Costo real de adoptable',
    palabra: 'Adoptable',
    oracion_visible: 'Lo adoptable desplazo a lo mejor.',
    que_detecta: 'Soluciones superiores bloqueadas por friccion institucional.',
    que_lo_activa: ['adoptable', 'solucion superior', 'no se puede implementar', 'viable politicamente'],
    nodos_relacionados: ['friccion_sistemica', 'incentivos', 'operacion', 'mihm'],
    accion_sugerida: 'Comparar costo tecnico contra costo institucional',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-003-compliance-como-narrativa',
    nombre: 'Compliance como narrativa',
    palabra: 'Narrativa',
    oracion_visible: 'La metrica cumple. La seguridad no.',
    que_detecta: 'Uso de cumplimiento formal para cubrir riesgo operativo real.',
    que_lo_activa: ['compliance', 'cumplimiento', 'metrica', 'seguridad real', 'auditoria'],
    nodos_relacionados: ['metricas', 'seguridad', 'trazabilidad', 'riesgo'],
    accion_sugerida: 'Separar cumplimiento formal de seguridad efectiva',
    nivel_friccion: 5,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-004-dinero-como-estructura-temporal',
    nombre: 'Dinero como estructura temporal',
    palabra: 'Tiempo',
    oracion_visible: 'El dinero define cuanto tiempo puede sostenerse la incertidumbre.',
    que_detecta: 'Relacion entre recursos, margen de maniobra y duracion de incertidumbre.',
    que_lo_activa: ['presupuesto', 'dinero', 'tiempo', 'sostenibilidad', 'incertidumbre'],
    nodos_relacionados: ['project_manager', 'ejecucion', 'riesgo', 'mihm'],
    accion_sugerida: 'Calcular horizonte de maniobra',
    nivel_friccion: 3,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-005-escritura-sin-intencion-visible',
    nombre: 'Escritura sin intencion visible',
    palabra: 'Precision',
    oracion_visible: 'El texto debe mostrar funcion, no autoridad.',
    que_detecta: 'Documentacion con exceso de forma y poca intencion operativa.',
    que_lo_activa: ['documento', 'texto', 'redaccion', 'no se entiende', 'demasiado', 'publicar'],
    nodos_relacionados: ['document_layer', 'field_layer', 'trazabilidad', 'amv'],
    accion_sugerida: 'Eliminar frases que no cambian accion',
    nivel_friccion: 2,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-006-sistemas-de-alerta-que-nadie-revisa',
    nombre: 'Sistemas de alerta que nadie revisa',
    palabra: 'Alerta',
    oracion_visible: 'La alerta existe, pero nadie la usa.',
    que_detecta: 'Dashboards o senales sin revision operativa real.',
    que_lo_activa: ['dashboard', 'alerta', 'nadie revisa', 'indicador', 'monitor'],
    nodos_relacionados: ['bitacora', 'riesgo', 'operacion', 'mihm'],
    accion_sugerida: 'Asignar responsable de revision',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-007-contexto-perdido',
    nombre: 'Contexto perdido',
    palabra: 'Contexto',
    oracion_visible: 'La decision quedo separada de su razon.',
    que_detecta: 'Perdida de relevancia entre decision, registro y ejecucion.',
    que_lo_activa: ['contexto', 'no recuerdo por que', 'registro incompleto', 'se perdio'],
    nodos_relacionados: ['memoria', 'bitacora', 'trazabilidad', 'ct'],
    accion_sugerida: 'Reconstruir origen antes de ejecutar',
    nivel_friccion: 3,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-008-personas-en-alta-incertidumbre',
    nombre: 'Personas en alta incertidumbre',
    palabra: 'Incertidumbre',
    oracion_visible: 'La persona opera sin reglas suficientes.',
    que_detecta: 'Operadores actuando en entornos ambiguos sin marco estable.',
    que_lo_activa: ['no se que hacer', 'incertidumbre', 'sin reglas', 'ambiguo'],
    nodos_relacionados: ['ct', 'amv', 'project_manager', 'mihm'],
    accion_sugerida: 'Definir una regla minima de accion',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-009-deuda-de-decision',
    nombre: 'Deuda de decision',
    palabra: 'Deuda',
    oracion_visible: 'No decidir tambien genera costo.',
    que_detecta: 'Costo acumulado por posponer problemas que ya requieren definicion.',
    que_lo_activa: ['despues', 'pendiente', 'no decidir', 'lo vemos luego', 'posponer', 'publicar'],
    nodos_relacionados: ['project_manager', 'bitacora', 'ruta', 'ct'],
    accion_sugerida: 'Cerrar una decision minima',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-010-incentivos-bien-disenados-que-fallan',
    nombre: 'Incentivos bien disenados que fallan',
    palabra: 'Incentivo',
    oracion_visible: 'El incentivo produce lo contrario de lo esperado.',
    que_detecta: 'Sistemas optimizados formalmente que generan resultados opuestos.',
    que_lo_activa: ['incentivo', 'objetivo', 'resultado opuesto', 'optimizacion'],
    nodos_relacionados: ['metricas', 'proxy_objetivo', 'gobernanza', 'riesgo'],
    accion_sugerida: 'Comparar incentivo contra conducta real',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-011-alarmas-silenciosas',
    nombre: 'Alarmas silenciosas',
    palabra: 'Silencio',
    oracion_visible: 'La metrica no grita, pero ya avisa.',
    que_detecta: 'Senales debiles de falla ocultas bajo estabilidad aparente.',
    que_lo_activa: ['alarma', 'silenciosa', 'estable', 'no se ve', 'senal debil'],
    nodos_relacionados: ['alertas', 'mihm', 'riesgo', 'bitacora'],
    accion_sugerida: 'Revisar senales debiles',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-012-umbrales-oficiales-vs-reales',
    nombre: 'Umbrales oficiales vs. reales',
    palabra: 'Brecha',
    oracion_visible: 'El limite oficial no coincide con el limite real.',
    que_detecta: 'Diferencia entre tolerancia declarada y capacidad operativa efectiva.',
    que_lo_activa: ['umbral', 'oficial', 'real', 'limite', 'capacidad'],
    nodos_relacionados: ['mihm', 'ucap', 'metricas', 'riesgo'],
    accion_sugerida: 'Actualizar umbral real',
    nivel_friccion: 5,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-013-anatomia-de-la-narrativa-institucional',
    nombre: 'Anatomia de la narrativa institucional',
    palabra: 'Ficcion',
    oracion_visible: 'La historia institucional sostiene lo que la operacion ya no sostiene.',
    que_detecta: 'Narrativas usadas para preservar coherencia aparente.',
    que_lo_activa: ['narrativa', 'institucional', 'discurso', 'apariencia', 'reputacion'],
    nodos_relacionados: ['coherencia', 'compliance', 'trazabilidad', 'riesgo'],
    accion_sugerida: 'Separar relato de evidencia',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-014-lo-no-documentado',
    nombre: 'Lo no documentado',
    palabra: 'Vacio',
    oracion_visible: 'Lo que no se documenta tambien decide.',
    que_detecta: 'Responsabilidad operativa invisible por ausencia de registro.',
    que_lo_activa: ['no documentado', 'no quedo registro', 'nadie lo escribio', 'vacio'],
    nodos_relacionados: ['bitacora', 'trazabilidad', 'r16_origen', 'responsabilidad'],
    accion_sugerida: 'Registrar lo implicito',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-015-degradacion-progresiva',
    nombre: 'Degradacion progresiva',
    palabra: 'Desgaste',
    oracion_visible: 'El sistema no cayo. Se fue apagando.',
    que_detecta: 'Fallo gradual sin evento unico de ruptura.',
    que_lo_activa: ['degradacion', 'progresiva', 'desgaste', 'cada vez peor'],
    nodos_relacionados: ['mihm', 'latencia', 'riesgo', 'seguimiento'],
    accion_sugerida: 'Medir tendencia, no solo estado',
    nivel_friccion: 5,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-016-operadores-criticos',
    nombre: 'Operadores criticos',
    palabra: 'Operador',
    oracion_visible: 'La operacion depende de personas bajo saturacion.',
    que_detecta: 'Personas clave sosteniendo sistemas criticos sin soporte suficiente.',
    que_lo_activa: ['operador', 'critico', 'saturado', 'guardia', 'responsable'],
    nodos_relacionados: ['ct', 'supervision', 'riesgo', 'mihm'],
    accion_sugerida: 'Identificar carga real del operador',
    nivel_friccion: 4,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-017-riesgo-institucional',
    nombre: 'Riesgo institucional',
    palabra: 'Riesgo',
    oracion_visible: 'El miedo a mostrar el problema aumenta el problema.',
    que_detecta: 'Bloqueo de transparencia por costo institucional percibido.',
    que_lo_activa: ['riesgo institucional', 'transparencia', 'miedo', 'exposicion'],
    nodos_relacionados: ['trazabilidad', 'gobernanza', 'compliance', 'bitacora'],
    accion_sugerida: 'Definir que debe mostrarse y que debe protegerse',
    nivel_friccion: 5,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-018-costo-politico-de-corregir',
    nombre: 'Costo politico de corregir',
    palabra: 'Costo',
    oracion_visible: 'Corregir cuesta mas que sostener el error.',
    que_detecta: 'Bloqueo de accion util por costo politico o reputacional.',
    que_lo_activa: ['costo politico', 'corregir', 'reputacion', 'no conviene'],
    nodos_relacionados: ['gobernanza', 'riesgo', 'compliance', 'decisiones'],
    accion_sugerida: 'Calcular costo de no corregir',
    nivel_friccion: 5,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-019-retroalimentacion-invertida',
    nombre: 'Retroalimentacion invertida',
    palabra: 'Inversion',
    oracion_visible: 'La alerta castiga a quien la reporta.',
    que_detecta: 'Sistemas donde reportar problemas produce penalizacion.',
    que_lo_activa: ['alerta', 'penaliza', 'reportar', 'castigo', 'feedback'],
    nodos_relacionados: ['alertas', 'supervision', 'gobernanza', 'operadores'],
    accion_sugerida: 'Proteger al nodo que reporta',
    nivel_friccion: 5,
    capa_visible: 'FIELD_LAYER',
  },
  {
    id: 'cs-020-ficcion-institucional',
    nombre: 'Ficcion institucional',
    palabra: 'Ficcion',
    oracion_visible: 'El sistema opera para parecer funcional.',
    que_detecta: 'Supervivencia narrativa de sistemas que ya no cumplen su funcion real.',
    que_lo_activa: ['ficcion institucional', 'parece funcionar', 'demasiado grande', 'narrativa'],
    nodos_relacionados: ['coherencia', 'compliance', 'riesgo', 'mihm'],
    accion_sugerida: 'Comparar funcion declarada contra funcion real',
    nivel_friccion: 5,
    capa_visible: 'FIELD_LAYER',
  },
  ...[
    ['021', 'Reconocimiento de limites', 'Limite', 'El sistema ya no puede sostener lo que promete.', 'Detecta el punto donde la utilidad real se agoto.', 'Marcar limite operativo'],
    ['022', 'Resiliencia silenciosa', 'Resiliencia', 'El sistema se adapta sin mostrarlo.', 'Detecta soporte invisible no reflejado en metricas.', 'Registrar adaptacion no visible'],
    ['023', 'Incentivos perversos', 'Desvio', 'El sistema premia lo que lo dana.', 'Detecta recompensas que producen deterioro.', 'Redisenar incentivo'],
    ['024', 'Diagnostico temprano', 'Anticipacion', 'La falla aparece antes del colapso.', 'Detecta senales previas a ocultacion o ruptura.', 'Registrar senal temprana'],
    ['025', 'Responsabilidad distribuida', 'Responsabilidad', 'Todos participan, nadie responde.', 'Detecta dilucion de autoridad en decisiones compartidas.', 'Asignar responsable verificable'],
    ['026', 'Metricas vs. realidad', 'Medicion', 'El numero no coincide con lo que ocurre.', 'Detecta separacion entre indicador y operacion.', 'Validar metrica contra campo'],
    ['027', 'Documentacion explicita', 'Registro', 'Lo implicito necesita forma.', 'Detecta conocimiento operativo sin documento.', 'Documentar sin exponer de mas'],
    ['028', 'Patrones repetibles', 'Repeticion', 'Esto ya ocurrio antes.', 'Detecta recurrencia util para anticipacion.', 'Nombrar patron'],
    ['029', 'Decisiones omitidas', 'Omision', 'La ausencia de decision ya produjo efecto.', 'Detecta vacios que alteran resultados.', 'Registrar omision'],
    ['030', 'Deuda de claridad', 'Claridad', 'Falta definir el problema.', 'Detecta costo por ambiguedad sostenida.', 'Definir el problema en una linea'],
    ['031', 'Senales precarias', 'Senal', 'La alerta apenas sobrevive al ruido.', 'Detecta senales debiles en entornos saturados.', 'Aislar senal'],
    ['032', 'Sobrecarga de informacion', 'Sobrecarga', 'Hay datos, pero no direccion.', 'Detecta exceso de informacion que impide decision.', 'Reducir entradas'],
    ['033', 'Silencio operativo', 'Silencio', 'La omision se volvio metodo.', 'Detecta falta sistematica de respuesta.', 'Forzar registro minimo'],
    ['034', 'Dependencias ocultas', 'Dependencia', 'Algo depende de algo que nadie declaro.', 'Detecta vinculos criticos no documentados.', 'Mapear dependencia'],
    ['035', 'Friccion cognitiva', 'Confusion', 'La decision se frena por falta de claridad.', 'Detecta carga mental que bloquea accion.', 'Reducir decision a un paso'],
    ['036', 'Convergencia de fallos', 'Convergencia', 'Varios errores apuntan al mismo punto.', 'Detecta alineacion de fallos multiples.', 'Priorizar nodo comun'],
    ['037', 'Propagacion sistemica', 'Propagacion', 'El error empezo a moverse.', 'Detecta efecto domino entre subsistemas.', 'Cortar propagacion'],
    ['038', 'Redundancia ilusoria', 'Redundancia', 'El respaldo existe, pero no respalda.', 'Detecta soportes formales que fallan en practica.', 'Probar redundancia real'],
    ['039', 'Reglas no escritas', 'Regla', 'La operacion sigue normas que nadie declaro.', 'Detecta normativa implicita.', 'Nombrar regla real'],
    ['040', 'Persistencia de error', 'Persistencia', 'La falla ya forma parte del sistema.', 'Detecta errores integrados como infraestructura.', 'Separar error de proceso'],
    ['041', 'Coordinacion fragmentada', 'Fragmentacion', 'Cada parte opera sin ver a las demas.', 'Detecta desalineacion entre subsistemas.', 'Alinear punto de coordinacion'],
    ['042', 'Politica de decision', 'Autoridad', 'No esta claro quien puede decidir.', 'Detecta asignacion opaca de autoridad.', 'Definir autoridad minima'],
    ['043', 'Interdependencia critica', 'Interdependencia', 'Una parte puede arrastrar a otra.', 'Detecta dependencia cruzada de alto riesgo.', 'Marcar nodo critico'],
    ['044', 'Retroalimentacion estructural', 'Ciclo', 'El sistema amplifica su propio error.', 'Detecta ciclos de refuerzo negativo.', 'Interrumpir ciclo'],
    ['045', 'Incentivos institucionales', 'Meta', 'La meta individual contradice la meta del sistema.', 'Detecta conflicto entre objetivos locales y globales.', 'Realinear objetivo'],
    ['046', 'Transparencia parcial', 'Parcialidad', 'Solo una parte de la verdad esta visible.', 'Detecta visibilidad selectiva.', 'Completar contexto necesario'],
    ['047', 'Consolidacion de errores', 'Norma', 'El error se volvio normal.', 'Detecta fallas convertidas en practica estandar.', 'Reclasificar como riesgo'],
    ['048', 'Sistema de sancion implicita', 'Sancion', 'El sistema castiga informacion util.', 'Detecta penalizacion indirecta de verdad operativa.', 'Proteger senal'],
    ['049', 'Barreras operativas', 'Barrera', 'El procedimiento bloquea la accion util.', 'Detecta procesos que impiden ejecucion.', 'Eliminar paso innecesario'],
    ['050', 'Mapeo de riesgos', 'Mapa', 'El riesgo necesita ubicacion.', 'Detecta nodos criticos y conexiones vulnerables.', 'Ubicar riesgo'],
    ['051', 'Arquitectura de resiliencia', 'Diseno', 'La resiliencia debe estar disenada.', 'Detecta ausencia de soporte ante falla.', 'Disenar soporte minimo'],
    ['052', 'Alarmas escalonadas', 'Escala', 'No todas las alertas pesan igual.', 'Detecta falta de prioridad entre senales.', 'Asignar nivel de alerta'],
    ['053', 'Documentacion compartida', 'Compartir', 'La informacion critica debe ser visible para quien actua.', 'Detecta aislamiento documental.', 'Compartir registro util'],
    ['054', 'Protocolos de contingencia', 'Contingencia', 'La crisis necesita pasos previos.', 'Detecta ausencia de procedimiento ante degradacion.', 'Crear protocolo minimo'],
    ['055', 'Supervision de operadores', 'Supervision', 'Supervisar no es invadir.', 'Detecta falta de control funcional.', 'Definir senal de desempeno'],
    ['056', 'Evaluacion de umbrales', 'Revision', 'Los limites deben revisarse.', 'Detecta umbrales obsoletos.', 'Actualizar umbral'],
    ['057', 'Optimizacion de flujos', 'Flujo', 'La friccion vive entre pasos.', 'Detecta perdida entre subsistemas.', 'Reducir transicion'],
    ['058', 'Persistencia normativa', 'Normativa', 'La regla sobrevive aunque cambie el contexto.', 'Detecta normas heredadas no revisadas.', 'Revisar regla vigente'],
    ['059', 'Resiliencia politica', 'Adaptacion', 'El sistema necesita resistir presion institucional.', 'Detecta fragilidad ante costo politico.', 'Separar presion de decision'],
    ['060', 'Indicadores de alerta temprana', 'Indicador', 'El fallo grande avisa antes.', 'Detecta senales anticipatorias.', 'Activar monitoreo temprano'],
    ['061', 'Integracion de patrones', 'Integracion', 'Los patrones deben operar juntos.', 'Detecta observaciones aisladas sin sistema.', 'Consolidar patron'],
    ['062', 'Memoria institucional', 'Memoria', 'Lo critico debe poder recordarse.', 'Detecta perdida de decisiones historicas.', 'Registrar memoria funcional'],
    ['063', 'Aprendizaje silencioso', 'Aprendizaje', 'El sistema aprendio sin decirlo.', 'Detecta adaptacion no explicita.', 'Hacer visible aprendizaje'],
    ['064', 'Sistemas de alerta automatizados', 'Automatizacion', 'La alerta debe sostenerse sin vigilancia constante.', 'Detecta monitoreo dependiente de atencion humana.', 'Automatizar senal minima'],
    ['065', 'Prediccion de fallos', 'Prediccion', 'El historial permite anticipar ruptura.', 'Detecta patrones predictivos.', 'Generar escenario'],
    ['066', 'Evaluacion de impacto', 'Impacto', 'Cada decision mueve otros nodos.', 'Detecta consecuencias sobre subsistemas.', 'Evaluar impacto'],
    ['067', 'Redundancia estrategica', 'Soporte', 'El respaldo debe funcionar cuando importa.', 'Detecta soporte efectivo.', 'Validar soporte'],
    ['068', 'Optimizacion de protocolos', 'Protocolo', 'El protocolo debe reducir friccion.', 'Detecta pasos inutiles o faltantes.', 'Ajustar protocolo'],
    ['069', 'Escalamiento de riesgos', 'Escalamiento', 'Algunos riesgos ya requieren intervencion.', 'Detecta cambio de nivel de riesgo.', 'Escalar decision'],
    ['070', 'Validacion cruzada de metricas', 'Validacion', 'Una metrica sola no basta.', 'Detecta necesidad de contraste entre datos.', 'Cruzar evidencia'],
    ['071', 'Consolidacion de responsabilidades', 'Asignacion', 'El vacio de autoridad debe cerrarse.', 'Detecta responsabilidad sin dueno.', 'Asignar dueno'],
    ['072', 'Documentacion evolutiva', 'Evolucion', 'El registro debe cambiar con el sistema.', 'Detecta documentacion estatica ante operacion cambiante.', 'Actualizar registro'],
    ['073', 'Transparencia operativa', 'Visibilidad', 'Debe verse lo necesario para actuar.', 'Detecta opacidad que bloquea ejecucion.', 'Mostrar lo necesario'],
    ['074', 'Automatizacion de decisiones', 'Regla', 'Lo repetible puede codificarse.', 'Detecta decisiones recurrentes que admiten regla.', 'Codificar regla'],
    ['075', 'Simulacion de escenarios', 'Simulacion', 'Antes de ejecutar, se puede probar.', 'Detecta necesidad de prever efectos.', 'Simular escenario'],
    ['076', 'Indicadores compuestos', 'Compuesto', 'Una sola senal no describe el sistema.', 'Detecta necesidad de metrica agregada.', 'Construir indicador compuesto'],
    ['077', 'Gestion de dependencias', 'Dependencias', 'Las conexiones criticas requieren control.', 'Detecta interacciones vulnerables.', 'Controlar dependencia'],
    ['078', 'Resiliencia integrada', 'Integrada', 'La resiliencia debe atravesar el sistema.', 'Detecta soportes aislados.', 'Integrar soporte'],
    ['079', 'Retroalimentacion continua', 'Continuidad', 'El sistema debe ajustarse mientras opera.', 'Detecta falta de ciclo de mejora.', 'Abrir ciclo de ajuste'],
    ['080', 'Coordinacion interdepartamental', 'Coordinacion', 'Las partes deben poder hablarse.', 'Detecta friccion entre areas.', 'Crear puente operativo'],
    ['081', 'Estandarizacion de practicas', 'Estandar', 'Lo repetible debe tener forma comun.', 'Detecta variacion innecesaria.', 'Estandarizar practica'],
    ['082', 'Optimizacion de comunicacion', 'Comunicacion', 'La senal debe perder menos en transito.', 'Detecta perdida de informacion relevante.', 'Reducir ruido de canal'],
    ['083', 'Diagnostico preventivo', 'Prevencion', 'La falla debe verse antes de doler.', 'Detecta riesgo antes de degradacion evidente.', 'Diagnosticar antes'],
    ['084', 'Alertas contextuales', 'Contexto', 'La alerta debe saber donde aparece.', 'Detecta senales sin prioridad contextual.', 'Contextualizar alerta'],
    ['085', 'Evaluacion de proxy vs. objetivo', 'Proxy', 'El proxy reemplazo al objetivo.', 'Detecta desviacion entre medicion y proposito.', 'Comparar proxy con objetivo'],
    ['086', 'Control de redundancia', 'Duplicacion', 'No todo respaldo ayuda.', 'Detecta duplicacion inutil.', 'Eliminar redundancia falsa'],
    ['087', 'Monitoreo de operadores', 'Monitoreo', 'El operador necesita senal, no vigilancia vacia.', 'Detecta supervision sin utilidad.', 'Definir monitoreo util'],
    ['088', 'Ajuste de incentivos', 'Ajuste', 'El incentivo debe alinearse con el sistema.', 'Detecta objetivos mal acoplados.', 'Ajustar incentivo'],
    ['089', 'Consolidacion de umbrales', 'Umbral', 'El limite debe quedar claro.', 'Detecta umbrales dispersos o contradictorios.', 'Consolidar umbral'],
    ['090', 'Validacion de resiliencia', 'Prueba', 'La resiliencia debe probarse.', 'Detecta soporte no validado.', 'Probar tolerancia'],
    ['091', 'Prediccion de efectos domino', 'Domino', 'Un error puede activar otros.', 'Detecta propagacion futura probable.', 'Anticipar propagacion'],
    ['092', 'Planificacion de contingencia', 'Plan', 'La contingencia se prepara antes.', 'Detecta ausencia de plan ante degradacion.', 'Planear respuesta'],
    ['093', 'Registro de decisiones omitidas', 'Omision', 'Lo omitido debe quedar visible.', 'Detecta decisiones evitadas.', 'Registrar vacio'],
    ['094', 'Evaluacion de impactos politicos', 'Presion', 'La presion institucional altera la decision.', 'Detecta riesgo politico de actuar.', 'Separar presion de evidencia'],
    ['095', 'Retroalimentacion estructural avanzada', 'Control', 'Los ciclos complejos necesitan control.', 'Detecta realimentacion de segundo orden.', 'Controlar ciclo'],
    ['096', 'Indicadores de eficiencia', 'Eficiencia', 'La operacion debe medirse contra realidad.', 'Detecta eficiencia narrativa sin eficacia real.', 'Medir operacion real'],
    ['097', 'Mapeo de dependencias criticas', 'Critico', 'Algunos nodos sostienen demasiado.', 'Detecta nodos esenciales y conexiones de riesgo.', 'Mapear nodo critico'],
    ['098', 'Sintesis operativa', 'Sintesis', 'Los patrones deben verse juntos.', 'Detecta dispersion de observaciones.', 'Consolidar tablero unico'],
    ['099', 'Estandares de operacion', 'Estandar', 'Lo auditable debe poder repetirse.', 'Detecta falta de procedimiento reproducible.', 'Definir estandar'],
    ['100', 'Ecosistema integrado', 'Ecosistema', 'El sistema ya puede operar como conjunto.', 'Detecta integracion suficiente de patrones, memoria y accion.', 'Cerrar integracion operativa'],
  ].map(([num, nombre, palabra, oracion, detecta, accion]) => ({
    id: `cs-${num}-${nombre.toLowerCase()
      .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')}`,
    nombre,
    palabra,
    oracion_visible: oracion,
    que_detecta: detecta,
    que_lo_activa: [nombre.toLowerCase(), palabra.toLowerCase(), detecta.toLowerCase()],
    nodos_relacionados: ['mihm', 'bitacora', 'trazabilidad', 'campo_cognitivo'],
    accion_sugerida: accion,
    nivel_friccion: num === '100' || Number(num) >= 61 ? 3 : 4,
    capa_visible: 'FIELD_LAYER',
  } as FieldPattern)),
];
