export const APEX_PILOT_CONTRACT = 'SFI-APEX-SOCIOTECHNICAL-PILOT-1.0' as const;

export type ApexPilotTrack = 'GAME_DEVELOPMENT' | 'LIVE_OPERATIONS' | 'SYSTEM_ADMINISTRATION';

export const APEX_SOCIOTECHNICAL_PILOT = {
  contractVersion: APEX_PILOT_CONTRACT,
  name: 'Apex Sociotechnical Field Pilot',
  institutionalHome: 'SFI Method Lab',
  parentProtocolId: 'sociotechnical_simulation',
  externalParty: 'Apex',
  status: 'PROPOSED_PARTNER_PILOT',
  purpose: 'Test whether the existing SFI apparatus can observe a bounded Apex sociotechnical system, identify a falsifiable friction hypothesis, simulate alternatives without contaminating evidence, execute at most one explicitly authorized reversible intervention, and measure a real return.',
  notASeparateLab: true,
  tracks: ['GAME_DEVELOPMENT','LIVE_OPERATIONS','SYSTEM_ADMINISTRATION'] as ApexPilotTrack[],
  requiredInputs: [
    'bounded system/object and owner',
    'baseline period and return window',
    'authorized operational evidence',
    'actor/role map without unnecessary personal data',
    'workflow or dependency graph',
    'one measurable friction claim',
    'one rival explanation',
    'explicit intervention authority and rollback owner',
  ],
  primaryObservables: [
    'handoff_latency',
    'rework_rate',
    'decision_bottleneck_time',
    'blocked_work_time',
    'information_loss_events',
    'incident_or_build_failure_rate',
    'recovery_time',
    'intervention_fidelity',
    'delivery_or_release_predictability',
  ],
  cycle: [
    'OBSERVE_BASELINE',
    'PRESERVE_EVIDENCE',
    'BUILD_RELATION_GRAPH',
    'MIHM_METHOD_RESOLUTION',
    'FREEZE_PRIMARY_AND_RIVAL_HYPOTHESES',
    'STUDIO_DESIGN_INTERVENTION',
    'METHOD_LAB_SIMULATE_A_B_C',
    'ROOT_ACP_REVIEW',
    'FIELD_EXECUTE_ONE_REVERSIBLE_INTERVENTION_IF_AUTHORIZED',
    'WAIT_RETURN_WINDOW',
    'CAPTURE_OBSERVED_RETURN',
    'RETURN_CONTRAST',
    'CT_CANDIDATE_LEARNING',
    'ROOT_ACP_DECISION',
    'ATLAS_CASE_RECORD',
  ],
  minimumExperiment: {
    baseline: 'A: observed current process with no SFI intervention',
    simulatedCounterfactual: 'B: proposed minimum intervention simulated in Method Lab',
    rivalCounterfactual: 'C: alternative intervention or null-compatible explanation',
    fieldRule: 'Only B or another ROOT/partner-approved reversible intervention may enter Field; simulated C remains simulated unless separately authorized.',
  },
  authorityBoundary: {
    automaticExternalExecution: false,
    rootApprovalRequired: true,
    apexHumanApprovalRequiredForOperationalChange: true,
    budgetAuthorityImplicit: false,
    credentialExpansionAllowed: false,
    irreversibleChangeAllowed: false,
  },
  successCriteria: [
    'one immutable Studio→Field handoff identity',
    'prediction sealed before outcome visibility',
    'observed return captured after the declared cutoff',
    'return contrast includes residual/error and rival interpretation',
    'result can be negative without protocol relabeling',
    'Apex-specific evidence remains scoped to authorized use',
    'SFI Total Proof stages traversed without treating simulation as observation',
  ],
  scientificClaimBoundary: 'A successful pilot demonstrates an operational end-to-end SFI case on one bounded sociotechnical system. It does not by itself validate MIHM, causal generalization, regime-transition theory, or Cognitive Twin individuation.',
} as const;
