import type { MethodLabProtocolDefinition, MethodLabProtocolId } from './contracts';

export const METHOD_LAB_PROTOCOLS: MethodLabProtocolDefinition[] = [
  {
    id: 'chronos_olympics',
    name: 'SFI CHRONOS / Cognitive Olympics',
    purpose: 'Evaluate cognitive constitutions under sealed historical, shadow-world and prospective temporal conditions.',
    version: '2026-08-11.chronos.v1',
    implementationPath: 'scripts/cognitive-olympics',
    executionSurface: '/root/method-lab',
    persistence: ['local append-only .sfi-cl ledger', 'optional sfi_lab_analyses summary after governed import'],
    epistemicClass: 'SIMULATED',
    maximumValidationLevel: 'PROSPECTIVE',
    promotionRequiresRoot: true,
    canonicalMutationAllowed: false,
    externalExecutionAllowed: false,
  },
  {
    id: 'cognitive_relational_lab',
    name: 'Cognitive Relational Lab',
    purpose: 'Observe founder-model and founder-Cognitive-Twin coupling through blind reconstruction, contrast and divergence before candidate learning.',
    version: '2026-08-11.crl.v1',
    implementationPath: 'src/lib/cognitive-lab',
    executionSurface: '/root/method-lab',
    persistence: ['cognitive relational session/event store', 'sfi_lab_analyses summary'],
    epistemicClass: 'SIMULATED',
    maximumValidationLevel: 'RETROSPECTIVE',
    promotionRequiresRoot: true,
    canonicalMutationAllowed: false,
    externalExecutionAllowed: false,
  },
  {
    id: 'ct_reentry',
    name: 'Cognitive Twin Reentry',
    purpose: 'Evaluate reintroduced Cognitive Twin functions, decision-structure transfer, counterfactual boundaries and governed mutations against founder holdout, engine swaps and prospective returns.',
    version: '2026-08-15.ct-reentry.v1.1',
    implementationPath: 'src/lib/cognitive-twin',
    executionSurface: '/root/method-lab',
    persistence: ['sfi_cognitive_twin_runs', 'sfi_cognitive_twin_evaluations', 'sfi_lab_analyses'],
    epistemicClass: 'SIMULATED',
    maximumValidationLevel: 'PROSPECTIVE',
    promotionRequiresRoot: true,
    canonicalMutationAllowed: false,
    externalExecutionAllowed: false,
  },
  {
    id: 'sociotechnical_simulation',
    name: 'Sociotechnical Simulation',
    purpose: 'Run bounded social/coordination/resource/information perturbation scenarios and compare predicted return signals with later observations.',
    version: '2026-08-11.sociotechnical.v1',
    implementationPath: 'src/lib/sfi/cognitive-runtime',
    executionSurface: '/root/method-lab',
    persistence: ['sfi_lab_analyses', 'epistemic_events'],
    epistemicClass: 'SIMULATED',
    maximumValidationLevel: 'PROSPECTIVE',
    promotionRequiresRoot: true,
    canonicalMutationAllowed: false,
    externalExecutionAllowed: false,
  },
  {
    id: 'economic_simulation',
    name: 'Observable Economic Simulation',
    purpose: 'Evaluate economic state transitions from explicit capital, labor, resource, market and world-context evidence with observable outcome variables.',
    version: '2026-08-11.economic.v1',
    implementationPath: 'src/lib/sfi/cognitive-runtime',
    executionSurface: '/root/method-lab',
    persistence: ['sfi_lab_analyses', 'world_source_observations', 'epistemic_events'],
    epistemicClass: 'SIMULATED',
    maximumValidationLevel: 'PROSPECTIVE',
    promotionRequiresRoot: true,
    canonicalMutationAllowed: false,
    externalExecutionAllowed: false,
  },
];

export function methodLabProtocol(id: MethodLabProtocolId) {
  return METHOD_LAB_PROTOCOLS.find((item) => item.id === id) ?? null;
}
