'use client';

import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, Building2, CheckCircle2, Database, FileUp, Globe2, KeyRound, Loader2, Network, Orbit, PlugZap, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
import './institute-field.css';

type Tenant={id:string;key:string;name:string;type:'PERSONAL'|'CLIENT'|'INTERNAL'|'RESEARCH';role:string;status:string};
type CaseRecord={id:string;tenantId:string;serviceProfileId:string;subject:string;scope:string;status:string;updatedAt:string};
type ServiceProfile={id:string;label:string;acceptedSubjects:readonly string[];requiredSources:readonly string[];requiredAnalyses:readonly string[];metricProfile:readonly string[]};
type WorldSummary={observedAt:string|null;regime:string;wsv:number|null;tension:number|null;confidence:number|null;warning:string|null};
type Props={authenticated:boolean;initialTenants:Tenant[];initialCases:CaseRecord[];profiles:ServiceProfile[];world:WorldSummary};
type Need={id:string;title:string;description:string;profileId:string;subject:string;personal:boolean;organization:boolean};

const NEEDS:Need[]=[
{id:'system',title:'Entender un sistema',description:'Relaciones, fricción, dependencia y trayectoria antes de intervenir.',profileId:'SYSTEM_OBSERVATORY',subject:'SYSTEM',personal:true,organization:true},
{id:'helpdesk',title:'Observar una operación',description:'Tickets, activos, SLA, recurrencia y trayectoria de servicio.',profileId:'SERVICE_OBSERVABILITY',subject:'HELP_DESK',personal:false,organization:true},
{id:'ai-governance',title:'Gobernar IA',description:'Modelo, contexto, autoridad, decisiones, riesgo y retornos verificables.',profileId:'AI_GOVERNANCE_ASSURANCE',subject:'AI_SYSTEM',personal:false,organization:true},
{id:'ai-adoption',title:'Introducir IA',description:'Observar el proceso, localizar fricción y medir valor real antes de automatizar.',profileId:'AI_ADOPTION_INTEGRATION',subject:'ORGANIZATION',personal:false,organization:true},
{id:'warranty',title:'Contratos y garantías',description:'Obligaciones, activos, proveedor, eventos, tiempos y cumplimiento observable.',profileId:'CONTRACT_WARRANTY_ASSURANCE',subject:'CONTRACT',personal:false,organization:true},
{id:'tender',title:'Evaluar una licitación',description:'Requisitos congelados, evidencia trazable, contradicción y determinabilidad.',profileId:'TENDER_ASSURANCE',subject:'TENDER',personal:false,organization:true},
{id:'memory',title:'Memoria institucional',description:'Relaciones y retornos longitudinales dentro del tenant, sin herencia institucional indebida.',profileId:'ENTERPRISE_MEMORY',subject:'ORGANIZATION',personal:false,organization:true},
{id:'cognitive',title:'Reconstruir conocimiento experto',description:'Evidencia autorizada convertida en representación cognitiva falsable.',profileId:'COGNITIVE_RECONSTRUCTION',subject:'PERSON',personal:true,organization:true},
{id:'research',title:'Investigar un fenómeno',description:'Protocolo explícito cuando el caso no cabe en un perfil predefinido.',profileId:'CUSTOM_RESEARCH',subject:'PHENOMENON',personal:true,organization:true},
];

function dateLabel(value:string|null){if(!value)return'sin observación';const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(d):value}
function slug(value:string){return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,54)||'workspace'}

export function InstituteWorkspace({authenticated,initialTenants,initialCases,profiles,world}:Props){
 const[tenants,setTenants]=useState(initialTenants);const[cases,setCases]=useState(initialCases);const[track,setTrack]=useState<'PERSONAL'|'ORGANIZATION'>('PERSONAL');
 const[tenantId,setTenantId]=useState(initialTenants.find(t=>t.type!=='PERSONAL')?.id??'');const[selectedNeed,setSelectedNeed]=useState<Need>(NEEDS[0]);
 const[subject,setSubject]=useState('');const[scope,setScope]=useState('');const[selectedCaseId,setSelectedCaseId]=useState('');const[uploadSourceType,setUploadSourceType]=useState('');
 const[newOrgName,setNewOrgName]=useState('');const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
 const[connectionOpen,setConnectionOpen]=useState(false);const[connectionType,setConnectionType]=useState('API');const[connectionTarget,setConnectionTarget]=useState('');const[connectionBaseUrl,setConnectionBaseUrl]=useState('');const[connectionNotes,setConnectionNotes]=useState('');const fileInput=useRef<HTMLInputElement|null>(null);

 const personalTenantIds=useMemo(()=>new Set(tenants.filter(t=>t.type==='PERSONAL').map(t=>t.id)),[tenants]);
 const visibleCases=useMemo(()=>cases.filter(c=>track==='ORGANIZATION'?Boolean(tenantId)&&c.tenantId===tenantId:personalTenantIds.has(c.tenantId)),[cases,track,tenantId,personalTenantIds]);
 const availableNeeds=useMemo(()=>NEEDS.filter(n=>track==='PERSONAL'?n.personal:n.organization),[track]);
 const profile=profiles.find(p=>p.id===selectedNeed.profileId)??null;const selectedCase=visibleCases.find(c=>c.id===selectedCaseId)??null;const caseProfile=profiles.find(p=>p.id===selectedCase?.serviceProfileId)??null;
 const currentTenant=tenants.find(t=>t.id===selectedCase?.tenantId)??null;

 useEffect(()=>{if(!visibleCases.some(c=>c.id===selectedCaseId))setSelectedCaseId(visibleCases[0]?.id??'')},[visibleCases,selectedCaseId]);
 useEffect(()=>{const required=caseProfile?.requiredSources??[];if(!required.includes(uploadSourceType))setUploadSourceType(required[0]??'DECLARED_BY_PROTOCOL')},[caseProfile,uploadSourceType]);

 async function refreshTenants(){const r=await fetch('/api/cases/tenants',{credentials:'include',cache:'no-store'});const b=await r.json().catch(()=>null)as{ok?:boolean;tenants?:Tenant[]}|null;if(r.ok&&b?.ok)setTenants(b.tenants??[])}
 async function refreshCases(){const r=await fetch('/api/cases',{credentials:'include',cache:'no-store'});const b=await r.json().catch(()=>null)as{ok?:boolean;cases?:CaseRecord[]}|null;if(r.ok&&b?.ok)setCases(b.cases??[])}
 function switchTrack(next:'PERSONAL'|'ORGANIZATION'){setTrack(next);setSelectedNeed(NEEDS.find(n=>next==='PERSONAL'?n.personal:n.organization)??NEEDS[0]);setMessage(null)}

 async function createOrganization(){if(!newOrgName.trim())return;setBusy('tenant');setMessage(null);try{const r=await fetch('/api/cases/tenants',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantKey:`client:${slug(newOrgName)}:${Date.now().toString(36)}`,name:newOrgName.trim(),tenantType:'CLIENT',metadata:{onboarding:'FIELD',selfProvisioned:true}})});const b=await r.json().catch(()=>null)as{ok?:boolean;tenant?:Record<string,unknown>;error?:string;details?:string}|null;if(!r.ok||!b?.ok||!b.tenant)throw new Error(b?.details??b?.error??`HTTP ${r.status}`);await refreshTenants();setTenantId(String(b.tenant.id));setNewOrgName('');setMessage('Workspace organizacional creado. Sus casos, fuentes, memoria y reportes quedan aislados por tenant.')}catch(e){setMessage(e instanceof Error?e.message:'No fue posible crear el workspace.')}finally{setBusy(null)}}

 async function createCase(){if(!subject.trim()||!scope.trim()){setMessage('Describe el sistema o fenómeno y qué necesitas entender.');return}if(track==='ORGANIZATION'&&!tenantId){setMessage('Selecciona o crea una organización.');return}setBusy('case');setMessage(null);try{const now=new Date().toISOString();const r=await fetch('/api/cases',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantId:track==='ORGANIZATION'?tenantId:null,serviceProfileId:selectedNeed.profileId,subject:subject.trim(),scope:scope.trim(),systemBoundaryRef:{id:`boundary:${slug(subject)}:${Date.now().toString(36)}`,version:'1.0',hash:null},temporalWindow:{mode:selectedNeed.profileId==='SERVICE_OBSERVABILITY'?'RETROLONGITUDINAL':'LONGITUDINAL',basis:'OBSERVED_TIME',start:null,end:null,cutoff:now,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',reconstructionAsOf:null,horizon:null}})});const b=await r.json().catch(()=>null)as{ok?:boolean;case?:CaseRecord;error?:string;details?:string}|null;if(!r.ok||!b?.ok||!b.case)throw new Error(b?.details??b?.error??`HTTP ${r.status}`);await Promise.all([refreshTenants(),refreshCases()]);setSelectedCaseId(b.case.id);setSubject('');setScope('');setMessage('Observación abierta. SFI ya conoce el contrato; ahora necesita fuentes reales.')}catch(e){setMessage(e instanceof Error?e.message:'No fue posible abrir la observación.')}finally{setBusy(null)}}

 async function uploadFiles(input:FileList|File[]){if(!selectedCase){setMessage('Selecciona un caso.');return}const list=Array.from(input);if(!list.length)return;setBusy('upload');setMessage(null);try{for(const file of list){const data=new FormData();data.set('file',file);data.set('sourceType',uploadSourceType||'DECLARED_BY_PROTOCOL');const r=await fetch(`/api/cases/${encodeURIComponent(selectedCase.id)}/sources/upload`,{method:'POST',credentials:'include',body:data});const b=await r.json().catch(()=>null)as{ok?:boolean;error?:string;details?:string}|null;if(!r.ok||!b?.ok)throw new Error(b?.details??b?.error??`HTTP ${r.status}`)}setMessage(`${list.length} archivo(s) registrados como ${uploadSourceType}. SOURCE ≠ EVIDENCE; el análisis debe producir la evidencia.`)}catch(e){setMessage(e instanceof Error?e.message:'No fue posible incorporar los archivos.')}finally{setBusy(null)}}

 async function requestConnection(){if(!selectedCase||!connectionTarget.trim()){setMessage('Selecciona un caso y una fuente requerida.');return}setBusy('connection');setMessage(null);try{const r=await fetch(`/api/cases/${encodeURIComponent(selectedCase.id)}/sources/connections`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetSourceType:connectionTarget.trim(),connectionType,baseUrl:connectionBaseUrl.trim()||null,notes:connectionNotes.trim()||null,requestedMode:'READ_ONLY_OBSERVATION'})});const b=await r.json().catch(()=>null)as{ok?:boolean;error?:string;details?:string}|null;if(!r.ok||!b?.ok)throw new Error(b?.details??b?.error??`HTTP ${r.status}`);setConnectionOpen(false);setConnectionTarget('');setConnectionBaseUrl('');setConnectionNotes('');setMessage('Solicitud registrada. No contiene secretos y no cuenta como fuente activa hasta verificar conectividad.')}catch(e){setMessage(e instanceof Error?e.message:'No fue posible registrar la conexión.')}finally{setBusy(null)}}

 return <main className="if-shell"><div className="if-grid" aria-hidden="true"/>
  <header className="if-topbar"><Link href="/" className="if-mark"><span>SFI</span><small>SYSTEM FRICTION INSTITUTE</small></Link><nav><Link href="/observatory">OBSERVATORY</Link>{authenticated?<Link href="/root">DIRECTOR</Link>:<Link href="/login">ACCESS</Link>}</nav></header>
  <section className="if-hero"><div className="if-eyebrow"><Orbit size={14}/> FIELD · INSTITUTIONAL INTAKE</div><h1>Observa un sistema.<br/><em>Después decide.</em></h1><p>FIELD es la frontera de entrada. Personas y organizaciones no comparten memoria: cada sistema entra dentro de un tenant explícito. Archivos y conexiones son fuentes; SFI conserva la separación entre fuente, registro, evidencia, inferencia, intervención y retorno.</p><div className="if-world"><span>WORLD</span><b>{world.regime||'MISSING'}</b><span>{dateLabel(world.observedAt)}</span>{world.warning?<i>{world.warning}</i>:null}</div></section>
  {!authenticated?<section className="if-public"><article><UserRound/><span>PERSONA</span><h2>Quiero entender un sistema propio o un fenómeno que observo.</h2><p>SFI abre un tenant personal, solicita evidencia proporcional y ejecuta métodos sin convertir inferencia en autoridad.</p></article><article><Building2/><span>ORGANIZACIÓN</span><h2>Quiero observar una operación, proceso, institución o sistema de IA.</h2><p>SFI crea un tenant aislado, pide fuentes y conexiones de lectura y construye trayectoria antes de proponer intervención.</p></article><div className="if-public-actions"><Link href="/signup">ABRIR WORKSPACE <ArrowRight/></Link><Link href="/login">YA TENGO ACCESO</Link></div></section>:
  <div className="if-workspace"><aside className="if-rail"><span className="if-section-number">01</span><h2>Quién está entrando</h2><button className={track==='PERSONAL'?'active':''} onClick={()=>switchTrack('PERSONAL')}><UserRound/> Persona <small>tenant personal</small></button><button className={track==='ORGANIZATION'?'active':''} onClick={()=>switchTrack('ORGANIZATION')}><Building2/> Organización <small>tenant aislado</small></button>{track==='ORGANIZATION'?<div className="if-org-picker"><label>ORGANIZACIÓN</label><select value={tenantId} onChange={e=>setTenantId(e.target.value)}><option value="">Seleccionar…</option>{tenants.filter(t=>t.type!=='PERSONAL').map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><div className="if-inline"><input value={newOrgName} onChange={e=>setNewOrgName(e.target.value)} placeholder="Nueva organización"/><button onClick={()=>void createOrganization()} disabled={busy==='tenant'}>{busy==='tenant'?<Loader2 className="spin"/>:'+'}</button></div></div>:<p className="if-note">El tenant personal se crea al abrir el primer caso. Nunca hereda datos de una organización ni los entrega a otra.</p>}</aside>
   <section className="if-main"><div className="if-step"><span className="if-section-number">02</span><div><h2>Qué necesitas que SFI haga</h2><p>La necesidad selecciona un contrato existente; no crea otra arquitectura.</p></div></div><div className="if-needs">{availableNeeds.map(n=><button key={n.id} className={selectedNeed.id===n.id?'active':''} onClick={()=>setSelectedNeed(n)}><span>{n.title}</span><small>{n.description}</small></button>)}</div><div className="if-profile"><div><span>PROTOCOLO</span><strong>{profile?.label??selectedNeed.profileId}</strong></div><div><span>FUENTES REQUERIDAS</span><strong>{profile?.requiredSources.join(' · ')||'DECLARED_BY_PROTOCOL'}</strong></div><div><span>ANÁLISIS</span><strong>{profile?.requiredAnalyses.join(' · ')||'DECLARED_BY_PROTOCOL'}</strong></div></div>
    <div className="if-case-create"><label>SISTEMA / OBJETO / FENÓMENO<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Ej. Mesa de Ayuda institucional"/></label><label>QUÉ NECESITAS ENTENDER<textarea value={scope} onChange={e=>setScope(e.target.value)} rows={3} placeholder="Ej. Recurrencia, fricción, trayectorias anómalas y relación ticket-activo-SLA-proveedor."/></label><button className="if-primary" onClick={()=>void createCase()} disabled={busy==='case'}>{busy==='case'?<Loader2 className="spin"/>:<Sparkles/>} ABRIR OBSERVACIÓN</button></div>
    <div className="if-step if-step-space"><span className="if-section-number">03</span><div><h2>Conecta el mundo</h2><p>Los casos mostrados pertenecen exclusivamente al tenant seleccionado.</p></div></div><select className="if-case-select" value={selectedCaseId} onChange={e=>setSelectedCaseId(e.target.value)}><option value="">Seleccionar caso…</option>{visibleCases.map(c=><option key={c.id} value={c.id}>{c.subject} · {c.serviceProfileId}</option>)}</select>
    {selectedCase&&caseProfile?.requiredSources.length?<select className="if-case-select" value={uploadSourceType} onChange={e=>setUploadSourceType(e.target.value)}><option value="">Tipo de fuente…</option>{caseProfile.requiredSources.map(s=><option key={s} value={s}>{s}</option>)}</select>:null}
    <div className="if-source-grid"><button className="if-drop" disabled={!selectedCase||busy==='upload'} onClick={()=>fileInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void uploadFiles(e.dataTransfer.files)}}>{busy==='upload'?<Loader2 className="spin"/>:<FileUp/>}<strong>ARRASTRAR FUENTES</strong><span>CSV · XLSX · JSON · PDF · imágenes · audio · video · documentos</span><small>Privado · tenant/case scoped · SOURCE ≠ EVIDENCE.</small></button><input ref={fileInput} hidden multiple type="file" onChange={e=>e.target.files&&void uploadFiles(e.target.files)}/><button className="if-connect" disabled={!selectedCase} onClick={()=>setConnectionOpen(true)}><PlugZap/><strong>SOLICITAR CONEXIÓN</strong><span>API · base de datos · export recurrente · webhook de entrada</span><small>Lectura por defecto. Escritura externa sólo con gobernanza.</small></button></div>
    {selectedCase?<div className="if-run-card"><div><span>CASO ACTIVO</span><strong>{selectedCase.subject}</strong><small>{currentTenant?.name??'Personal SFI Workspace'} · {selectedCase.status}</small></div><div className="if-run-flow"><span><Database/> SOURCE</span><ArrowRight/><span><Network/> EVIDENCE</span><ArrowRight/><span><Globe2/> ANALYSIS</span><ArrowRight/><span><ShieldCheck/> GOVERNANCE</span><ArrowRight/><span><CheckCircle2/> RETURN</span></div><Link href="/field/protocol">EJECUTAR PROTOCOLO DE INTERVENCIÓN <ArrowRight/></Link></div>:null}{message?<div className="if-message">{message}</div>:null}
   </section></div>}
  <section className="if-principles"><article><span>OBSERVACIÓN ANTES QUE OPINIÓN</span><p>La realidad precede al relato.</p></article><article><span>EVIDENCIA ANTES QUE AFIRMACIÓN</span><p>Toda proposición debe poder perder contra el mundo.</p></article><article><span>REVERSIBILIDAD ANTES QUE EJECUCIÓN</span><p>La intervención conserva una ruta de retorno.</p></article><article><span>AUTORIDAD EXPLÍCITA</span><p>Autonomía interna no significa autoridad externa.</p></article></section>
  {connectionOpen?<div className="if-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setConnectionOpen(false)}}><section className="if-modal"><button className="if-close" onClick={()=>setConnectionOpen(false)}>×</button><span>CONEXIÓN DE FUENTE</span><h2>¿Qué debe observar SFI?</h2><p>Registra finalidad y superficie. No pegues tokens, contraseñas ni secretos.</p><label>FUENTE REQUERIDA<select value={connectionTarget} onChange={e=>setConnectionTarget(e.target.value)}><option value="">Seleccionar…</option>{(caseProfile?.requiredSources??[]).map(s=><option key={s} value={s}>{s}</option>)}<option value="OTHER">Otra fuente</option></select></label><label>TIPO DE CONEXIÓN<select value={connectionType} onChange={e=>setConnectionType(e.target.value)}><option>API</option><option>DATABASE</option><option>RECURRENT_EXPORT</option><option>WEBHOOK_INBOUND</option></select></label><label>URL BASE / DOCUMENTACIÓN<input value={connectionBaseUrl} onChange={e=>setConnectionBaseUrl(e.target.value)} placeholder="https://…"/></label><label>NOTAS<textarea rows={3} value={connectionNotes} onChange={e=>setConnectionNotes(e.target.value)} placeholder="Datos autorizados, periodicidad y restricciones."/></label><div className="if-boundary"><KeyRound/><span>Las credenciales se provisionan fuera de la evidencia. Una solicitud no cuenta como fuente activa.</span></div><button className="if-primary" onClick={()=>void requestConnection()} disabled={busy==='connection'}>{busy==='connection'?<Loader2 className="spin"/>:<PlugZap/>} REGISTRAR SOLICITUD</button></section></div>:null}
 </main>
}
