import type { StudioProductionState } from './studioProductionTypes';
import { missingMetric, phase } from './studioContracts';

export function buildStudioProductionDegradedState(reason: string): StudioProductionState {
  const generatedAt = new Date().toISOString();

  return {
    generatedAt,
    systemState: 'degraded',
    session: {
      id: null,
      title: 'SIN SESION ACTIVA',
      status: 'blocked',
      createdAt: null,
      updatedAt: null,
    },
    activeObject: {
      id: null,
      sessionId: null,
      title: 'SIN OBJETO CARGADO',
      type: 'unknown',
      sourceUri: null,
      mimeType: null,
      sizeBytes: null,
      status: 'blocked',
      readiness: 'missing',
      uploadedAt: null,
      version: null,
      storageStatus: 'MISSING',
      analysisStatus: 'FAILED',
    },
    objectFeatures: {
      modality: 'unknown',
      readiness: 'missing',
      metrics: [],
      layers: [],
      graph: { nodes: [], edges: [] },
    },
    metricValues: [
      missingMetric('active_object', 'Active Object', 'Studio cannot identify an active persisted object.', ['studio_objects readable row']),
      missingMetric('storage_verified', 'Storage Verified', 'Storage verification is unavailable in degraded state.', ['studio_uploads readable row']),
      missingMetric('feature_coverage', 'Feature Coverage', 'No feature rows were available.', ['studio_object_features rows']),
    ],
    phaseStates: [
      phase({
        key: 'object_received',
        label: 'OBJECT RECEIVED',
        status: 'FAILED',
        error: reason,
        details: 'Studio production state could not be built.',
        nextAction: 'Inspect Supabase/Studio runtime error.',
        requirements: ['studio_sessions', 'studio_objects', 'studio_uploads'],
      }),
    ],
    evidence: [],
    viewContracts: [
      {
        key: 'overview',
        title: 'OVERVIEW',
        purpose: 'Show active object and pipeline state.',
        inputs: ['Studio production state'],
        outputs: ['Object status', 'pipeline', 'next action'],
        requiredEvidence: ['studio_object'],
        status: 'FAILED',
        blockedReason: reason,
      },
    ],
    fieldGraph: { nodes: [], edges: [] },
    nextAction: {
      code: 'NO_ACTION_AVAILABLE',
      action: 'NO_ACTION_AVAILABLE',
      reason,
      requirement: 'Restore Studio production state.',
      endpoint: null,
      method: null,
      disabledReason: reason,
    },
    audioFeatures: {
      waveform: [],
      rms: null,
      peak: null,
      clippingRisk: null,
      dynamicRange: null,
      lufs: null,
      spectralCentroid: null,
      frequencyBands: [],
      stereoImage: null,
      silenceStartSeconds: null,
      silenceEndSeconds: null,
      energySegments: [],
      stemCorrelation: [],
    },
    videoFeatures: {
      shots: null,
      scenes: null,
      motionIntensity: null,
      transitionRhythm: null,
      visualMotifs: [],
    },
    imageFeatures: {
      dominantColors: [],
      textureDensity: null,
      visualEntropy: null,
      spatialBalance: null,
      symbolicTags: [],
    },
    textFeatures: {
      tokens: null,
      sections: null,
      themes: [],
      motifs: [],
      sentimentArousal: null,
      narrativeArc: [],
      semanticDensity: null,
      symbolicRecurrence: null,
    },
    communityFeatures: {
      participantCount: null,
      messageDensity: null,
      topicClusters: [],
      affectiveTone: null,
      recurrence: null,
      coherence: null,
      friction: null,
    },
    timeCoordinateFeatures: {
      timeRange: null,
      placeLabel: null,
      semanticAnchors: [],
      historicalVectorTags: [],
      dominantTensions: [],
      gapDescription: null,
    },
    culturalLens: null,
    mihmReport: {
      score: null,
      individual: null,
      group: null,
      institutional: null,
      systemic: null,
      civilizational: null,
      source: 'SOURCE_UNAVAILABLE',
    },
    hypotheses: null,
    interventions: [],
    archive: {
      events: [],
      evidenceTraceCount: null,
      integrity: 'missing',
    },
    exports: {
      packages: [],
      signoffReadiness: 'missing',
    },
    provenance: {
      basedOn: [],
      derivedFrom: [],
      limits: [reason],
    },
    degradedSources: [reason],
  };
}
