import type { StudioProductionState } from './studioProductionTypes';

export function buildStudioProductionDegradedState(reason: string): StudioProductionState {
  const generatedAt = new Date().toISOString();

  return {
    generatedAt,
    systemState: 'degraded',
    session: {
      id: null,
      title: 'SIN SESION ACTIVA',
      status: 'blocked',
      createdAt: null,
      updatedAt: null,
    },
    activeObject: {
      id: null,
      sessionId: null,
      title: 'SIN OBJETO CARGADO',
      type: 'unknown',
      sourceUri: null,
      mimeType: null,
      status: 'blocked',
      readiness: 'missing',
      uploadedAt: null,
    },
    objectFeatures: {
      modality: 'unknown',
      readiness: 'missing',
      metrics: [],
      layers: [],
      graph: { nodes: [], edges: [] },
    },
    audioFeatures: {
      waveform: [],
      rms: null,
      peak: null,
      clippingRisk: null,
      dynamicRange: null,
      lufs: null,
      spectralCentroid: null,
      frequencyBands: [],
      stereoImage: null,
      silenceStartSeconds: null,
      silenceEndSeconds: null,
      energySegments: [],
      stemCorrelation: [],
    },
    videoFeatures: {
      shots: null,
      scenes: null,
      motionIntensity: null,
      transitionRhythm: null,
      visualMotifs: [],
    },
    imageFeatures: {
      dominantColors: [],
      textureDensity: null,
      visualEntropy: null,
      spatialBalance: null,
      symbolicTags: [],
    },
    textFeatures: {
      tokens: null,
      sections: null,
      themes: [],
      motifs: [],
      sentimentArousal: null,
      narrativeArc: [],
      semanticDensity: null,
      symbolicRecurrence: null,
    },
    communityFeatures: {
      participantCount: null,
      messageDensity: null,
      topicClusters: [],
      affectiveTone: null,
      recurrence: null,
      coherence: null,
      friction: null,
    },
    timeCoordinateFeatures: {
      timeRange: null,
      placeLabel: null,
      semanticAnchors: [],
      historicalVectorTags: [],
      dominantTensions: [],
      gapDescription: null,
    },
    culturalLens: null,
    mihmReport: {
      score: null,
      individual: null,
      group: null,
      institutional: null,
      systemic: null,
      civilizational: null,
      source: 'SOURCE_UNAVAILABLE',
    },
    hypotheses: null,
    interventions: [],
    archive: {
      events: [],
      evidenceTraceCount: null,
      integrity: 'missing',
    },
    exports: {
      packages: [],
      signoffReadiness: 'missing',
    },
    provenance: {
      basedOn: [],
      derivedFrom: [],
      limits: [reason],
    },
    degradedSources: [reason],
  };
}
