import {
  ContextBuilderAgent,
  CulturalSimulatorAgent,
  EconomicFieldSimulatorAgent,
  EvidenceHunterAgent,
  HistoricalScoutAgent,
  MultiStakeholderBootstrapAgent,
  OpportunityAgent,
  PhenotypeResolverAgent,
  PolicySimulatorAgent,
  ProjectExecutionManagerAgent,
  PsychologicalSimulatorAgent,
  RealityCalibrationAgent,
  RiskAgent,
  SocialFieldSimulatorAgent,
  TemporalResolverAgent,
  TrajectoryAgent,
} from './agents';
import { MetaOrchestratorAgent } from './metaOrchestrator';

export const canonicalAgents = [
  new EvidenceHunterAgent(),
  new TemporalResolverAgent(),
  new TrajectoryAgent(),
  new RealityCalibrationAgent(),
  new RiskAgent(),
  new OpportunityAgent(),
  new MetaOrchestratorAgent(),
  new HistoricalScoutAgent(),
  new PhenotypeResolverAgent(),
  new ContextBuilderAgent(),
  new SocialFieldSimulatorAgent(),
  new EconomicFieldSimulatorAgent(),
  new PolicySimulatorAgent(),
  new CulturalSimulatorAgent(),
  new PsychologicalSimulatorAgent(),
  new MultiStakeholderBootstrapAgent(),
  new ProjectExecutionManagerAgent(),
];
