import {
  SFI_SERVICE_PROFILE_CONTRACT,
  type SfiServiceProfileV1,
} from '../contracts/commercial';

export const SFI_SERVICE_PROFILES = [
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'SYSTEM_OBSERVATORY',
    label: 'SFI System Observatory',
    acceptedSubjects: ['SYSTEM', 'ORGANIZATION', 'SERVICE', 'AI_SYSTEM'],
    inputSchema: 'SFI_SYSTEM_OBSERVATORY_INPUT_V1',
    temporalPolicy: ['CROSS_SECTIONAL', 'LONGITUDINAL'],
    requiredSources: ['OPERATIONAL_RECORDS', 'SYSTEM_EVENTS'],
    allowedInstruments: ['METHOD', 'GRAPH', 'FORECAST', 'AI_MODEL', 'LLM'],
    requiredAnalyses: ['SYSTEM_MODEL', 'FRICTION_MAP', 'TRAJECTORY'],
    metricProfile: ['FRICTION', 'DEPENDENCY', 'LATENCY', 'CAPACITY', 'UNCERTAINTY'],
    domainRules: ['OBSERVE_BEFORE_INTERPRET', 'MAP_FAILURE_TO_SYSTEM_RELATIONS'],
    epistemicPolicy: ['AI_OUTPUT_NOT_EVIDENCE_BY_INHERITANCE'],
    governancePolicy: ['NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['SOURCE_LINEAGE', 'LONGITUDINAL_RETURN_WHEN_AVAILABLE'],
    reportTemplate: 'SFI_SYSTEM_OBSERVATORY_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'AI_IMPLEMENTATION_DIAGNOSTIC',
    label: 'SFI AI Implementation Diagnostic',
    acceptedSubjects: ['AI_SYSTEM', 'AI_ENABLED_WORKFLOW', 'ORGANIZATION'],
    inputSchema: 'SFI_AI_IMPLEMENTATION_DIAGNOSTIC_INPUT_V1',
    temporalPolicy: ['CROSS_SECTIONAL', 'LONGITUDINAL'],
    requiredSources: ['AI_EXECUTION_RECORDS', 'WORKFLOW_RECORDS'],
    allowedInstruments: ['METHOD', 'AI_MODEL', 'LLM', 'GRAPH', 'SIMULATION', 'HUMAN_REVIEW'],
    requiredAnalyses: ['MODEL_DATA_CONTEXT_WORKFLOW_DECOMPOSITION', 'FRICTION_LOCALIZATION'],
    metricProfile: ['MODEL_QUALITY', 'RETRIEVAL_QUALITY', 'INPUT_COMPLETENESS', 'HANDOFF', 'GOVERNANCE_LATENCY', 'ADOPTION'],
    domainRules: ['DO_NOT_ATTRIBUTE_ALL_FAILURE_TO_MODEL'],
    epistemicPolicy: ['AI_OUTPUT_NOT_EVIDENCE_BY_INHERITANCE'],
    governancePolicy: ['HUMAN_AUTHORITY_PRESERVED', 'NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['REPRODUCIBLE_FAILURE_TRACE', 'OPERATIONAL_RETURN'],
    reportTemplate: 'SFI_AI_IMPLEMENTATION_DIAGNOSTIC_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'AI_ADOPTION_INTEGRATION',
    label: 'SFI AI Adoption & Integration',
    acceptedSubjects: ['ORGANIZATION', 'PROCESS', 'SERVICE'],
    inputSchema: 'SFI_AI_ADOPTION_INTEGRATION_INPUT_V1',
    temporalPolicy: ['CROSS_SECTIONAL', 'LONGITUDINAL', 'PROJECTIVE'],
    requiredSources: ['PROCESS_RECORDS', 'OPERATIONAL_RECORDS'],
    allowedInstruments: ['METHOD', 'GRAPH', 'SIMULATION', 'AI_MODEL', 'LLM', 'HUMAN_REVIEW'],
    requiredAnalyses: ['FRICTION_MAP', 'AI_OPPORTUNITY_MAP', 'USE_CASE_FEASIBILITY', 'RETURN_DESIGN'],
    metricProfile: ['VALUE', 'FEASIBILITY', 'RISK', 'INTEGRATION_FRICTION', 'MEASURED_RETURN'],
    domainRules: ['OBSERVE_PROCESS_BEFORE_SELECTING_AI', 'MINIMAL_INTERVENTION_FIRST'],
    epistemicPolicy: ['PROJECTED_VALUE_NOT_OBSERVED_RETURN'],
    governancePolicy: ['HUMAN_APPROVAL_BEFORE_INTERVENTION', 'NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['PRE_POST_OBSERVATION', 'RETURN_MEASUREMENT'],
    reportTemplate: 'SFI_AI_ADOPTION_INTEGRATION_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'AI_GOVERNANCE_ASSURANCE',
    label: 'SFI AI Governance Assurance',
    acceptedSubjects: ['AI_SYSTEM', 'AI_ASSISTED_DECISION_CHAIN', 'ORGANIZATION'],
    inputSchema: 'SFI_AI_GOVERNANCE_ASSURANCE_INPUT_V1',
    temporalPolicy: ['CROSS_SECTIONAL', 'LONGITUDINAL', 'RETROLONGITUDINAL'],
    requiredSources: ['MODEL_TRACE', 'DECISION_TRACE', 'AUTHORITY_RECORDS'],
    allowedInstruments: ['AI_MODEL', 'LLM', 'GRAPH', 'ASSURANCE_ENGINE', 'HUMAN_REVIEW'],
    requiredAnalyses: ['PROVENANCE', 'AUTHORITY_CHAIN', 'DETERMINABILITY', 'AUDITABILITY'],
    metricProfile: ['TRACE_COMPLETENESS', 'HUMAN_GATE', 'DETERMINABILITY', 'CONTRADICTION'],
    domainRules: ['MODEL_OUTPUT_NOT_DECISION_AUTHORITY'],
    epistemicPolicy: ['SOURCE_RECORD_EVIDENCE_SEPARATION'],
    governancePolicy: ['HUMAN_AUTHORITY_PRESERVED', 'NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['MODEL_PROMPT_INPUT_CONTEXT_DECISION_ACTION_RETURN_TRACE'],
    reportTemplate: 'SFI_AI_GOVERNANCE_ASSURANCE_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'SERVICE_OBSERVABILITY',
    label: 'SFI Service / Help Desk Observability',
    acceptedSubjects: ['SERVICE', 'HELP_DESK', 'TICKET_ECOSYSTEM', 'ORGANIZATION'],
    inputSchema: 'SFI_SERVICE_OBSERVABILITY_INPUT_V1',
    temporalPolicy: ['LONGITUDINAL', 'RETROLONGITUDINAL'],
    requiredSources: ['TICKETS', 'ASSETS', 'SLA_RECORDS'],
    allowedInstruments: ['METHOD', 'GRAPH', 'FORECAST', 'ASSURANCE_ENGINE', 'AI_MODEL'],
    requiredAnalyses: ['RECURRENCE', 'FRICTION_CLUSTERS', 'SYSTEMIC_CAUSE_CANDIDATES', 'SERVICE_TRAJECTORY'],
    metricProfile: ['RECURRENCE', 'RESPONSE_TIME', 'RESOLUTION_TIME', 'SLA', 'DEPENDENCY', 'FRICTION'],
    domainRules: ['TICKET_COUNT_NOT_EQUAL_PROBLEM_COUNT', 'PRESERVE_ASSET_SUPPLIER_RELATIONS'],
    epistemicPolicy: ['CAUSE_CANDIDATE_REQUIRES_EVIDENCE'],
    governancePolicy: ['NO_AUTOMATIC_OPERATIONAL_ACTION', 'NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['TICKET_EVENT_LINEAGE', 'RESOLUTION_RETURN'],
    reportTemplate: 'SFI_SERVICE_OBSERVABILITY_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'CONTRACT_WARRANTY_ASSURANCE',
    label: 'SFI Contract & Warranty Assurance',
    acceptedSubjects: ['CONTRACT', 'ASSET', 'SUPPLIER', 'WARRANTY_ECOSYSTEM'],
    inputSchema: 'SFI_CONTRACT_WARRANTY_ASSURANCE_INPUT_V1',
    temporalPolicy: ['LONGITUDINAL', 'RETROLONGITUDINAL'],
    requiredSources: ['CONTRACTS', 'ASSETS', 'WARRANTY_EVENTS', 'SLA_RECORDS'],
    allowedInstruments: ['METHOD', 'GRAPH', 'ASSURANCE_ENGINE', 'AI_MODEL', 'LLM', 'HUMAN_REVIEW'],
    requiredAnalyses: ['OBLIGATION_MAP', 'WARRANTY_STATE', 'SUPPLIER_TRAJECTORY', 'COMPLIANCE_RISK'],
    metricProfile: ['OBLIGATION_STATUS', 'RESPONSE_TIME', 'RESOLUTION_TIME', 'RECURRENCE', 'SUPPLIER_PERFORMANCE'],
    domainRules: ['CONTRACT_TEXT_REQUIRES_SOURCE_TRACE', 'NO_AUTOMATIC_BREACH_DECLARATION'],
    epistemicPolicy: ['LEGAL_OR_CONTRACTUAL_CONCLUSION_REQUIRES_DETERMINABILITY'],
    governancePolicy: ['HUMAN_AUTHORITY_PRESERVED', 'NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['CONTRACTUAL_EVENTS', 'OPERATIONAL_PERFORMANCE', 'WARRANTY_RETURNS', 'SUPPLIER_HISTORY'],
    reportTemplate: 'SFI_CONTRACT_WARRANTY_ASSURANCE_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'TENDER_ASSURANCE',
    label: 'SFI Bid / Tender Evaluation Assurance',
    acceptedSubjects: ['TENDER', 'BIDDER', 'ACQUISITION_DECISION_SYSTEM'],
    inputSchema: 'SFI_TENDER_ASSURANCE_INPUT_V1',
    temporalPolicy: ['CROSS_SECTIONAL', 'RETROLONGITUDINAL'],
    requiredSources: ['FROZEN_REQUIREMENTS', 'BIDDER_DOCUMENTS'],
    allowedInstruments: ['AI_MODEL', 'LLM', 'ASSURANCE_ENGINE', 'HUMAN_REVIEW'],
    requiredAnalyses: ['REQUIREMENT_BY_BIDDER_MATRIX', 'CONTRADICTIONS', 'DETERMINABILITY', 'ECONOMIC_ASSESSMENT'],
    metricProfile: ['PASS_FAIL_UNDETERMINED', 'SOURCE_PAGE_COVERAGE', 'CONFIDENCE', 'CONTRADICTION'],
    domainRules: ['REQUIREMENTS_FROZEN_BEFORE_EVALUATION', 'AI_DOES_NOT_SELECT_WINNER'],
    epistemicPolicy: ['SOURCE_PAGE_EVIDENCE_ASSESSMENT_REQUIRED'],
    governancePolicy: ['HUMAN_DECISION_AUTHORITY', 'NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['SOURCE', 'PAGE', 'EVIDENCE', 'DETERMINABILITY'],
    reportTemplate: 'SFI_TENDER_ASSURANCE_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'ENTERPRISE_MEMORY',
    label: 'SFI Enterprise Memory / Atlas Node',
    acceptedSubjects: ['ORGANIZATION', 'PROGRAM', 'SUPPLIER_ECOSYSTEM'],
    inputSchema: 'SFI_ENTERPRISE_MEMORY_INPUT_V1',
    temporalPolicy: ['LONGITUDINAL', 'RETROLONGITUDINAL'],
    requiredSources: ['AUTHORIZED_ORGANIZATIONAL_RECORDS'],
    allowedInstruments: ['GRAPH', 'ORGANIZATIONAL_TWIN', 'ASSURANCE_ENGINE'],
    requiredAnalyses: ['RELATIONAL_HISTORY', 'TRAJECTORY', 'PROVENANCE'],
    metricProfile: ['COVERAGE', 'LINEAGE', 'TEMPORAL_CONTINUITY'],
    domainRules: ['CLIENT_MEMORY_REMAINS_TENANT_SCOPED'],
    epistemicPolicy: ['ASSOCIATION_NOT_CAUSALITY'],
    governancePolicy: ['NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['SOURCE_LINEAGE', 'TEMPORAL_RECONSTRUCTION'],
    reportTemplate: 'SFI_ENTERPRISE_MEMORY_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'COGNITIVE_RECONSTRUCTION',
    label: 'SFI Cognitive / Expert Knowledge Preservation',
    acceptedSubjects: ['PERSON', 'EXPERT_KNOWLEDGE_SYSTEM'],
    inputSchema: 'SFI_COGNITIVE_RECONSTRUCTION_INPUT_V1',
    temporalPolicy: ['LONGITUDINAL', 'RETROLONGITUDINAL', 'PROJECTIVE'],
    requiredSources: ['AUTHORIZED_COGNITIVE_EVIDENCE'],
    allowedInstruments: ['METHOD', 'AI_MODEL', 'LLM', 'GRAPH', 'COGNITIVE_TWIN', 'HUMAN_REVIEW'],
    requiredAnalyses: ['COGNITIVE_OPERATIONS', 'LONGITUDINAL_CONSISTENCY', 'RIVAL_HYPOTHESIS'],
    metricProfile: ['STRUCTURAL_FIDELITY', 'PREDICTION', 'RECONSTRUCTION_ERROR'],
    domainRules: ['COMPUTATIONAL_REPRESENTATION_NOT_PHENOMENAL_CONSCIOUSNESS'],
    epistemicPolicy: ['OBSERVER_FALSIFICATION_REQUIRED_FOR_STRONG_CLAIMS'],
    governancePolicy: ['PERSON_CT_NOT_INHERITED_BY_SFI_CT', 'NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['BLIND_PREDICTION', 'LONGITUDINAL_CONSISTENCY', 'RETROLONGITUDINAL_RECONSTRUCTION', 'OBSERVER_FALSIFICATION'],
    reportTemplate: 'SFI_COGNITIVE_RECONSTRUCTION_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
  {
    contract: SFI_SERVICE_PROFILE_CONTRACT,
    id: 'CUSTOM_RESEARCH',
    label: 'SFI Custom Research',
    acceptedSubjects: ['SYSTEM', 'PHENOMENON', 'ORGANIZATION', 'CASE'],
    inputSchema: 'SFI_CUSTOM_RESEARCH_INPUT_V1',
    temporalPolicy: ['CROSS_SECTIONAL', 'LONGITUDINAL', 'RETROLONGITUDINAL', 'COUNTERFACTUAL', 'PROJECTIVE'],
    requiredSources: ['DECLARED_BY_PROTOCOL'],
    allowedInstruments: ['METHOD', 'AI_MODEL', 'LLM', 'SIMULATION', 'FORECAST', 'GRAPH', 'MULTIAGENT', 'HUMAN_REVIEW'],
    requiredAnalyses: ['DECLARED_BY_PROTOCOL'],
    metricProfile: ['DECLARED_BY_PROTOCOL'],
    domainRules: ['PROTOCOL_REQUIRED'],
    epistemicPolicy: ['EPISTEMIC_CLASS_PRESERVED'],
    governancePolicy: ['NO_DIRECT_ROOT_ACCESS'],
    validationProfile: ['DECLARED_BY_PROTOCOL'],
    reportTemplate: 'SFI_CUSTOM_RESEARCH_REPORT_V1',
    rootAccess: false,
    institutionalAdmission: 'GATED',
  },
] as const satisfies readonly SfiServiceProfileV1[];

export function getSfiServiceProfile(id: string) {
  return SFI_SERVICE_PROFILES.find((profile) => profile.id === id) ?? null;
}
