import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=(path:string)=>fs.readFileSync(path,'utf8');
const integration=read('src/core/cognitive-twin/institutionalIntegration.ts');
const experience=read('src/core/cognitive-twin/experience.ts');
const evidenceIngestion=read('src/core/cognitive-twin/evidenceIngestion.ts');
const studioContext=read('src/core/cognitive-twin/studioContext.ts');
const canonicalMemory=read('src/core/cognitive-twin/canonicalMemoryView.ts');
const crl=read('src/lib/cognitive-lab/service.ts');
const field=read('src/lib/field/governedReturn.ts');
const methodLab=read('src/lib/method-lab/simulationRun.ts');
const deliberate=read('src/app/api/root/cognitive-twin/deliberate/route.ts');
const continuity=read('src/app/api/cron/continuity-report/route.ts');
const scheduledCycle=read('src/app/api/cron/sfi-institutional-cycle/route.ts');
const manualCycle=read('src/app/api/root/institutional-cycle/route.ts');
const state=read('src/core/cognitive-twin/readState.ts');
const liveSurface=read('src/components/sfi/SfiConsole.tsx');
const sceneRegistry=read('src/components/sfi/scenes.ts');
const workflow=read('.github/workflows/sfi-ct-institutional-integration.yml');
for(const organ of ['ROOT_EVIDENCE','OBSERVATORY','STUDIO','METHOD_LAB','FIELD','GOVERNANCE','COGNITIVE_TWIN'])assert.ok(integration.includes(`organ:'${organ}'`),`missing organ integration: ${organ}`);
assert.ok(integration.includes("case 'simulated': return 'SIMULATED'"));
assert.ok(integration.includes("case 'real_input': return 'DERIVED_FROM_OBSERVED_INPUT'"));
assert.ok(integration.includes("case 'provider_enriched': return 'DERIVED_FROM_PROVIDER_ENRICHED_INPUT'"));
assert.ok(integration.includes("case 'no_input': return 'MISSING_INPUT'"));
assert.ok(integration.includes("default: return 'UNCLASSIFIED_NON_OBSERVED'"));
assert.equal(integration.includes("dataMode === 'SIMULATED' ? 'SIMULATED' : 'OBSERVED_RECORD'"),false);
assert.ok(integration.includes(".order('created_at', { ascending: false })"));
assert.ok(integration.includes("epistemicClass:'OBSERVED_RETURN'"));
assert.ok(integration.includes("import { recordCognitiveTwinExperience } from './experience'"));
assert.equal(integration.includes("from('sfi_cognitive_twin_memory').upsert"),false);
assert.ok(experience.includes("eventName:'cognitive_twin.experience.recorded'"));
assert.ok(experience.includes('Memory promotion is policy-governed and never expands Cognitive Twin authority'));
assert.ok(experience.includes('processEpistemicEvent(emitted.event)'));
assert.ok(canonicalMemory.includes("lifecycle === 'REJECTED'"));
assert.ok(canonicalMemory.includes("lifecycle === 'OBSOLETE'"));
assert.ok(canonicalMemory.includes('CONSUMABLE_MEMORY_STATUSES'));
assert.ok(canonicalMemory.includes('seenKeys.add(memory.memory_key)'));
assert.ok(canonicalMemory.includes('.range(offset, offset + PAGE_SIZE - 1)'));
assert.equal(canonicalMemory.includes('.limit(scanLimit)'),false);
for(const [name,source] of [['ROOT Evidence',evidenceIngestion],['Studio',studioContext],['CRL',crl]] as const){assert.ok(source.includes('recordCognitiveTwinExperience'),`${name} canonical bridge missing`);assert.equal(source.includes("from('sfi_cognitive_twin_memory').upsert"),false);}
assert.ok(field.includes('recordCognitiveTwinExperience'));
assert.ok(field.includes("epistemicClass:'OBSERVED_RETURN'"));
assert.ok(field.includes('returnContrast:contrast'));
assert.ok(methodLab.includes('recordCognitiveTwinExperience'));
assert.ok(methodLab.includes("epistemicClass:'SIMULATED'"));
assert.ok(deliberate.includes('syncSfiInstitutionalStateToCognitiveTwin'));
assert.ok(deliberate.includes('sfiIntegration: institutionalSync.integration'));
assert.ok(deliberate.includes('organ_unexercised:'));
const syncIndex=continuity.indexOf('syncSfiInstitutionalStateToCognitiveTwin()'),heartbeatIndex=continuity.indexOf('runCognitiveTwinDevelopmentalHeartbeat()');
assert.ok(syncIndex>=0&&heartbeatIndex>syncIndex);
assert.ok(scheduledCycle.includes('runIntegratedInstitutionalCycle'));
assert.ok(manualCycle.includes('runIntegratedInstitutionalCycle'));
assert.ok(state.includes('readCognitiveTwinSfiIntegration'));
assert.ok(state.includes('sfiOrgansConnected'));
assert.ok(state.includes('sfiOrgansExercised'));
assert.ok(liveSurface.includes('COGNITIVE TWIN'));
assert.ok(liveSurface.includes('El sistema propone'));
assert.ok(liveSurface.includes('/api/acp/proposals'));
assert.ok(sceneRegistry.includes("root:{key:'root'"));
assert.ok(workflow.includes('permissions:\n  contents: read'));
console.log(JSON.stringify({ok:true,contract:'SFI-CT-INSTITUTIONAL-INTEGRATION-2.0',organs:7,canonicalExperienceBridge:true,canonicalMemoryTerminalFiltering:true,canonicalMemoryDistinctKeyPaging:true,methodLabEpistemicBoundary:true,newestFirstSync:true,nativeCognitiveTwinSurface:'SFI_LIVE_SCENE',authority:['GOVERNANCE'],longitudinalSubject:'CT-A01'},null,2));
