import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read=(path:string)=>readFileSync(path,'utf8');
const route=read('src/app/api/reality-chain/extract/route.ts');
const parser=read('src/lib/studio/multimodal/textAnalyzer.ts');
const page=read('src/app/reality-chain/page.tsx');
const ui=read('src/components/sfi/RealityChainWorkbench.tsx');
const publicSurface=read('src/components/sfi/PublicInstrumentSurface.tsx');
assert.match(page,/requireUserProfile/,'Authenticated case surface required');
assert.match(route,/requireAuthenticatedUser/,'Transient extraction requires login');
assert.match(route,/extractDocumentTextTransient/,'Must reuse an existing extractor rather than introduce an untested second parser');
assert.match(parser,/extractPdfTextFallback/,'PDF parser fallback must remain available');
assert.match(route,/sha256/,'Server-calculated original content hash required');
assert.match(route,/no-store, private/,'Response must not cache document excerpts');
assert.match(route,/MAX_BYTES/,'Input byte limit is mandatory');
assert.match(route,/complete:!textLimited/,'Report extraction completeness must exclude truncated text');
assert.doesNotMatch(route,/\.storage\.from\(|\.upload\(|\.writeFile\(/,'Transient extract route cannot persist original bytes');
assert.match(ui,/kind:'RECORD'/,'Quoted passages are records, not promoted evidence');
assert.match(ui,/sourceRefs:\[sourceRef\]/,'Every passage must cite its registered source');
assert.match(ui,/SOURCE:-1,RECORD:-1/,'Sources and records cannot silently be treated as observed signals');
assert.match(ui,/NOT AN AUTHORITY OR SCIENTIFIC VALIDATION/,'Report cannot claim certification');
assert.match(ui,/claims:\[\]/,'Governed receipt cannot invent substantive claims');
assert.match(ui,/persistTraceManifest/,'Source-linked trace manifest must be persistable without source files');
assert.match(ui,/DERIVED_RECORD_NOT_AUTHORIZED_REPORT/,'Trace snapshot is never promoted to institutional authority');
assert.doesNotMatch(ui,/src="\/assets\/sfi\/instruments\/RealityChain\\.png"/,'Operative case reconstruction cannot fake panels with a flattened reference image');
assert.match(publicSurface,/label:'RECONSTRUCT A CASE',href:'\/reality-chain'/,'Public introduction should lead to account-scoped workspace');
console.log('PASS · Reality Chain case access, source-only intake, parser reuse, non-promotion, report boundaries and existing assets');
