import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=(p:string)=>readFileSync(p,'utf8');
const ui=read('src/components/sfi/RealityChainWorkbench.tsx');
const css=read('src/components/sfi/RealityChainWorkbench.css');
const link=read('src/app/api/cases/[caseId]/linked-cases/route.ts');
const root=read('src/components/sfi/RootNeuralGraphView.tsx');
const nav=read('src/components/sfi/AuthenticatedSfiMenu.tsx');
const stageNames=['WORLD','SIGNAL','OBSERVATION','EVIDENCE','INFERENCE','AUTHORITY','EXECUTION','RETURN','LEARNING'];
for(const label of stageNames) assert(ui.includes("name:'"+label+"'"),'missing stage '+label);
assert.equal((ui.match(/className="rcHorizon rcThreeHorizon"/g)||[]).length,3,'exactly three screen groups');
assert(ui.includes('STEPS.slice(0,3)')&&ui.includes('STEPS.slice(3,6)')&&ui.includes('STEPS.slice(6,9)'),'three groups of three');
assert(css.includes('width:300vw')&&css.includes('flex:0 0 100vw'),'three viewport-wide stages, not 225vw scroll');
assert(css.includes('scrollbar-width:none')&&css.includes('::-webkit-scrollbar{display:none}'),'invisible horizontal scrollbar');
assert(ui.includes('RealityChain.png'),'reuses existing image; no AI artwork');
assert(ui.includes('rcLearningIcon')&&ui.includes('aria-label="Learning"'),'semantic LEARNING icon inside screen three');
assert(ui.includes("requestJson('/api/cases')")&&ui.includes("requestJson('/api/cases/'+encodeURIComponent(id))"),'existing case/tenant API');
assert(ui.includes('EXTRACT TEXT TEMPORARILY')&&ui.includes('STORE SOURCE PRIVATELY'),'both transient extraction and direct upload');
assert(ui.includes('/sources/upload-ticket')&&ui.includes('/sources/finalize-upload'),'direct private storage contract');
assert(ui.includes("kind:'RECORD'")&&ui.includes('sourceRefs:[sourceRef]'),'extracted passage remains source-linked record');
assert(ui.includes('Date.parse(o.createdAt)<=Date.parse(cutoff'),'do not introduce future records into historical T0');
assert(ui.includes('const stageObjects=asOfObjects.filter'),'T0 applied to stages, not only ledger');
assert(ui.includes('Date.parse(o.createdAt)<=Date.parse(cutoff')&&ui.includes('Date.parse(o.observedAt)<=Date.parse(cutoff'),'T0 requires recorded and observed boundaries');
assert(ui.includes('STEPS.slice(6,9)')&&ui.includes('NOT AUTOMATICALLY')===false,'learning displayed without fabricated promotion claim');
assert(ui.includes("const sourceObjects=asOfObjects.filter"),'T0 applied to persisted trace manifest');
assert(ui.includes("function" )||ui.includes("const linkExistingCase"),'existing case link');
assert(link.includes("readOperationalCase(referencedCaseId,user.id)"),'permission check on referenced case');
assert(link.includes('CROSS_TENANT_CASE_REFERENCE_FORBIDDEN'),'tenant boundary');
assert(link.includes('CROSS_CASE_REFERENCE_CYCLE_FORBIDDEN'),'no direct/indirect chain cycle');
assert(link.includes("epistemicRole:'RECORD'")&&link.includes("evidenceQualification:'NOT_ESTABLISHED'"),'no automatic evidence promotion');
assert(link.includes('readbackVerified:true'),'verify case link persistence');
assert(ui.includes("'/root?reading=REALITY_CHAIN&node='"),'ROOT passport deep link');
assert(root.includes("searchParams.get('node')"),'ROOT reads deep link');
assert(root.includes('THIS CASE IS NOT ADMITTED AS A CANONICAL GRAPH NODE'),'ROOT must disclose missing graph admission, not silently lose the Passport');
assert(nav.includes("{label:'REALITY CHAIN',href:'/reality-chain'}"),'authenticated menu points to one actual case workbench');
assert(!ui.includes('Coastal Resilience Finance Shift')&&!ui.includes('C-2026-0417'),'no image mock case');
assert(!ui.includes('CONFIDENCE 87%')&&!ui.includes('RISK 13%'),'no invented confidence');
console.log('PASS · Three real Reality Chain screens, traceability, safe case linkage and inherited operational intake');
