import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const read = (relative: string) => fs.readFileSync(path.join(root, relative), 'utf8');
const checks: Array<{ name: string; ok: boolean }> = [];
const check = (name: string, ok: boolean) => checks.push({ name, ok });

const reconcile = read('src/lib/evidence/reconcileEvidenceGraph.ts');
const canonicalGraph = read('src/lib/graph/canonicalGraph.ts');
const libraryProjection = read('src/lib/graph/libraryCorpusProjection.ts');
const libraryPage = read('src/app/library/page.tsx');
const documentaryCatalog = read('src/lib/sfi/library/documentaryCatalog.ts');
const libraryClient = read('src/app/library/LibraryClient.tsx');
const reader = read('src/lib/root/sovereign/readers/readRootEvidenceGraph.ts');
const amvReader = read('src/lib/root/sovereign/readers/readRootAmv.ts');
const predictionReader = read('src/lib/root/sovereign/readers/readRootPredictions.ts');
const systemReader = read('src/lib/root/sovereign/readers/readRootSystemState.ts');
const readerSupport = read('src/lib/root/sovereign/readers/readerSupport.ts');
const reconcileRoute = read('src/app/api/root/evidence/reconcile/route.ts');
const reportsRoute = read('src/app/api/root/reports/route.ts');
const scenes = read('src/components/sfi/scenes.ts');
const shellUi = read('src/components/sfi/SfiConsole.tsx');
const rootUi = read('src/components/sfi/SfiRootWorkspace.tsx');
const operatingUi = read('src/components/sfi/SfiOperatingWorkspace.tsx');
const governanceUi = read('src/components/sfi/SfiGovernanceWorkspace.tsx');
const interactiveRoute = read('src/app/api/root/interactive/route.ts');
const scenePage = read('src/app/[scene]/page.tsx');
const humanReport = read('src/lib/reports/humanReport.ts');
const neuralGraphRuntime = read('src/lib/root/neuralGraphRuntime.ts');
const continuityStore = read('src/lib/sfi/continuityPostgres.ts');
const canonicalGraphRuntime = read('src/lib/graph/canonicalGraph.ts');
const neuralGraphView = read('src/components/sfi/RootNeuralGraphView.tsx');
const cognitiveAdmission = read('src/lib/graph/cognitiveGraphAdmission.ts');
const publicGraphStateRoute = read('src/app/api/graph/state/route.ts');
const runtimeBootstrapRoute = read('src/app/api/runtime/bootstrap/route.ts');
const observatoryStateRoute = read('src/app/api/observatory/state/route.ts');

check('legacy graph node storage remains compatible', reconcile.includes("LEGACY_NODE_STORAGE_TYPE = 'INF'") && !reconcile.includes("node_type: 'SRC'") && !reconcile.includes("node_type: 'ATR'"));
check('legacy graph edge storage remains compatible', reconcile.includes("LEGACY_EDGE_STORAGE_TYPE = 'structural_inferred'") && reconcile.includes('relation_type: LEGACY_EDGE_STORAGE_TYPE'));
check('graph edge upsert matches live composite unique key', reconcile.includes("EDGE_CONFLICT = 'source_node_key,target_node_key,relation_type'") && reconcile.includes('{ onConflict: EDGE_CONFLICT }'));
check('multiple semantic relations survive one physical legacy edge', reconcile.includes('declaredRelations') && reconcile.includes('semanticRelationTypes'));
check('evidence graph read has no reconciliation write side effect', !reader.includes('reconcilePersistedEvidenceGraph'));
check('AMV read has no ensure/write side effect', !amvReader.includes('ensureInstitutionalAttractorDeclaration'));
check('prediction read has no attractor reconciliation side effect', !predictionReader.includes('reconcilePredictionAttractors'));
check('system read no longer recomputes MIHM matrix', !systemReader.includes('readRootMihmMatrix'));
check('Supabase reads are abortable', readerSupport.includes('executeAbortableQuery') && readerSupport.includes('DEFAULT_SUPABASE_READ_TIMEOUT_MS'));
check('evidence reader does not require missing graph_nodes.evidence_ids column', !reader.includes("lineage,evidence_ids,payload,attributes") && reader.includes("lineage,payload,attributes"));
check('evidence reader exposes semantic and temporal edge metadata', reader.includes('declaredRelations.join') && reader.includes('relationClass:') && reader.includes('observedAt: dateValue(attributes.observedAt'));
check('explicit graph maintenance is sovereign and audited', reconcileRoute.includes("requireRootActor('evidence.graph.reconcile')") && reconcileRoute.includes("action: 'evidence.graph.reconcile'"));

check('Library corpus projects into canonical graph types without a second graph store', libraryProjection.includes('buildLibraryCorpusGraphProjection') && libraryProjection.includes('CanonicalGraphNode') && libraryProjection.includes('CanonicalGraphEdge') && libraryProjection.includes('sf_docs_frontmatter.json') && !libraryProjection.includes("from('graph_nodes')") && !libraryProjection.includes("from('graph_edges')"));
check('canonical graph reader merges shared Library projection without write side effects', canonicalGraph.includes('buildLibraryCorpusGraphProjection') && canonicalGraph.includes('libraryProjection') && !canonicalGraph.includes('.upsert(') && !canonicalGraph.includes('.insert('));
check('Retired public Library preserves its SFI canonical graph capability internally', libraryPage.includes("redirect('/publications')") && documentaryCatalog.includes("readCanonicalGraphState('sfi')") && documentaryCatalog.includes('graphRelations') && documentaryCatalog.includes('library_corpus'));
check('Library search and cards consume graph relations', libraryClient.includes('graphRelations?:string[]') && libraryClient.includes('...(doc.graphRelations??[])') && libraryClient.includes('doc.graphRelationCount??0') && libraryClient.includes('graph relations'));
check('Library graph remains documentary relation rather than validation claim', libraryProjection.includes('doesNotImplyValidation: true') && libraryProjection.includes("epistemicClass: 'DECLARED'"));
check('Library graph supplies a stable non-empty label when source title is absent', libraryProjection.includes('function documentLabel') && libraryProjection.includes('doc.title?.trim()') && libraryProjection.includes('doc.nodeId?.trim()') && libraryProjection.includes('label: documentLabel(doc)'));
check('ROOT graph reconciliation materializes Library through the existing canonical store', reconcile.includes('buildLibraryCorpusGraphProjection') && reconcile.includes('libraryProjection.nodes') && reconcile.includes('libraryProjection.edges') && reconcile.includes("'library_corpus'"));
check('persisted Library materialization preserves the documentary non-validation boundary', reconcile.includes('doesNotImplyValidation') && reconcile.includes("epistemic_class: 'declared'") && reconcile.includes('library_corpus'));

check('ROOT remains the canonical sovereign operating scene', scenes.includes("root:{key:'root'") && scenes.includes("title:'ROOT · Sovereign Operation'") && scenes.includes("liveSource:'/api/root/workboard'"));
check('legacy sovereign workspace no longer composes the ROOT scene', !scenePage.includes('SfiRootWorkspace') && scenePage.includes('RootNeuralGraphView'));
check('ROOT field exposes temporal and reconstructive readings', neuralGraphView.includes("'TRAJECTORY'") && neuralGraphView.includes("'RETROLONGITUDINAL'") && neuralGraphView.includes("'PROJECTION'") && neuralGraphView.includes("'FRICTION_REGIME'") && neuralGraphView.includes("'RETURN_CONTRAST'"));
check('ROOT preserves binary terminal decisions while evidence request remains a non-terminal defer', rootUi.includes('ACCEPT') && rootUi.includes('DENY') && rootUi.includes('REQUEST EVIDENCE') && rootUi.includes('does not turn a source into admitted evidence') && rootUi.includes('decision remains open'));
check('ROOT report archive is observational rather than approvable', rootUi.includes("jsonFetch('/api/root/reports')") && rootUi.includes('do not require ACCEPT/DENY') && !rootUi.includes('DENY REPORT'));
check('ROOT report route normalizes every report body before presentation', reportsRoute.includes("humanReportText") && reportsRoute.includes("from '@/lib/reports/humanReport'") && reportsRoute.includes('body: humanReportText(item.body)'));
check('human report normalizer supports headings, lists and markdown tables', humanReport.includes("kind: 'heading'") && humanReport.includes("kind: 'list'") && humanReport.includes("kind: 'table'") && humanReport.includes('normalizeHumanReport'));
check('human report normalizer removes presentational markdown tokens', humanReport.includes('stripInlineMarkdown') && humanReport.includes('replace(/\\*\\*([^*]+)\\*\\*/g') && humanReport.includes('replace(/`([^`]+)`/g'));
check('human report text materializes tables without markdown pipe syntax', humanReport.includes('tableRowText') && humanReport.includes("join(' · ')") && humanReport.includes('humanReportText'));
check('technical JSON remains behind trace disclosure', rootUi.includes('View technical trace') && rootUi.includes('JSON.stringify(value, null, 2)'));
check('ROOT operating workspace delegates governance to one canonical workspace', operatingUi.includes('SfiGovernanceWorkspace') && operatingUi.includes("if(surface==='governance')return <SfiGovernanceWorkspace enabled={enabled}/>"));
check('ROOT governance workspace defers governed proposal hydration to the canonical interactive projection', governanceUi.includes("jsonFetch('/api/root/interactive?surface=governance')") && governanceUi.includes('includeTargets=1') && governanceUi.includes('setWorkboard(data.operationalNext?{operationalNext:data.operationalNext}') && interactiveRoute.includes("proposalQueueSource: 'operationalNext.items'") && interactiveRoute.includes('targetHydrationDeferred: true'));
check('ROOT governance workspace exposes live operational telemetry without duplicate base feeds', governanceUi.includes("jsonFetch('/api/root/interactive?surface=governance')") && governanceUi.includes('/api/root/cognitive-runtime/records?agentId=') && governanceUi.includes('workboard?.operationalNext') && governanceUi.includes('latestExecutionAt'));
check('live scene runtime is gated by canonical scene registry', scenePage.includes('SCENE_KEYS.includes') && scenePage.includes('scene={scene as SceneKey}'));
check('deleted sovereign workspace is not required for graph truth', !shellUi.includes('RootObservatoryWorkspace') && !operatingUi.includes('RootObservatoryWorkspace') && !scenePage.includes('RootObservatoryWorkspace'));
check('ROOT graph runtime uses one primary sentinel before Neon fallback', neuralGraphRuntime.includes("let nodeCount = await queryCount('graph_nodes')") && neuralGraphRuntime.includes("if (nodeCount === null && isSfiContinuityConfigured())"));
check('ROOT graph runtime exposes active read plane and diagnostic', neuralGraphRuntime.includes("readPlane: 'SUPABASE' | 'NEON' | 'UNAVAILABLE'") && neuralGraphRuntime.includes('primaryDiagnostic'));
check('Neon ROOT graph fallback is one aggregate continuity query', continuityStore.includes('readContinuityRootNeuralGraphRuntime') && continuityStore.includes('(select count(*)::int from graph_nodes)') && continuityStore.includes('top_attractors') && continuityStore.includes('top_ejectors'));
check('ROOT graph row-read failures remain distinguishable from legitimate empty rows', neuralGraphRuntime.includes("failed: true") && neuralGraphRuntime.includes("attractorRead.failed") && neuralGraphRuntime.includes("ejectorRead.failed"));
check('partial primary graph data keeps Supabase provenance if Neon fallback fails', neuralGraphRuntime.includes("readPlane = 'SUPABASE'") && neuralGraphRuntime.includes("supabase_root_graph_partial_read_unavailable; continuity="));
check('canonical graph full-state read reuses one Neon aggregate fallback', canonicalGraphRuntime.includes('readContinuityCanonicalGraphRows') && continuityStore.includes('readContinuityCanonicalGraphRows') && continuityStore.includes('jsonb_agg('));
check('canonical graph hybrid reads preserve top-level profile without breaking canonical-minimal schema', canonicalGraphRuntime.includes('GRAPH_NODE_HYBRID_READ_FIELDS') && canonicalGraphRuntime.includes('GRAPH_EDGE_HYBRID_READ_FIELDS') && canonicalGraphRuntime.includes('GRAPH_NODE_CANONICAL_READ_FIELDS') && canonicalGraphRuntime.includes('GRAPH_EDGE_CANONICAL_READ_FIELDS') && canonicalGraphRuntime.includes('profile,origin') && canonicalGraphRuntime.includes("error.code === '42703'"));
check('canonical graph retries compatibility projections only for a missing-column schema mismatch', canonicalGraphRuntime.includes('readSupabaseGraphRows') && canonicalGraphRuntime.includes('isMissingGraphColumn') && canonicalGraphRuntime.includes('GRAPH_NODE_CANONICAL_READ_FIELDS') && canonicalGraphRuntime.includes('readSupabaseGraphRowsWide'));
check('canonical graph keeps the normal read narrow but has a schema-wide final fallback for supported endpoint aliases', canonicalGraphRuntime.includes('readSupabaseGraphRowsWide') && canonicalGraphRuntime.includes("service.from('graph_nodes').select('*')") && canonicalGraphRuntime.includes("service.from('graph_edges').select('*')") && !canonicalGraphRuntime.includes("GRAPH_NODE_HYBRID_READ_FIELDS = 'id,node_id,node_key,label,node_type,ontology_type,profile,origin,payload"));
check('canonical graph preserves payload-backed metadata when attributes are absent or empty', canonicalGraphRuntime.includes('function attributesFromRow') && canonicalGraphRuntime.includes('Object.keys(attributes).length') && canonicalGraphRuntime.includes('asRecord(row.payload)'));
check('Neon canonical graph read is schema-tolerant, one-round-trip, and keeps profile when present', continuityStore.includes('to_jsonb(n)') && continuityStore.includes('to_jsonb(e)') && continuityStore.includes(" - 'payload'") && continuityStore.includes('jsonb_agg(') && !continuityStore.includes('select *\n              from graph_nodes'));
check('Neon continuity normalizes legacy payload into attributes before trimming duplicate payload', continuityStore.includes("to_jsonb(n)->'attributes'") && continuityStore.includes("to_jsonb(n)->'payload'") && continuityStore.includes("to_jsonb(e)->'attributes'") && continuityStore.includes("to_jsonb(e)->'payload'"));
check('Neon continuity treats JSON null attributes as absent before payload fallback', continuityStore.includes("nullif(to_jsonb(n)->'attributes', 'null'::jsonb)") && continuityStore.includes("nullif(to_jsonb(e)->'attributes', 'null'::jsonb)"));
check('Neon continuity preserves legacy evidence_ids as canonical edge lineage', continuityStore.includes("'lineage'") && continuityStore.includes("to_jsonb(e)->'evidence_ids'") && continuityStore.includes("nullif(nullif(to_jsonb(e)->'lineage', 'null'::jsonb), '[]'::jsonb)"));
check('canonical graph continuity fallback requires explicit caller opt-in', canonicalGraphRuntime.includes('CanonicalGraphReadOptions') && canonicalGraphRuntime.includes('options: CanonicalGraphReadOptions = {}') && canonicalGraphRuntime.includes('options.allowContinuity === true') && canonicalGraphRuntime.includes('primaryDiagnostic && allowContinuity && isSfiContinuityConfigured()'));
check('public graph, Library, and Observatory surfaces cannot opt into continuity', !publicGraphStateRoute.includes('allowContinuity: true') && !libraryPage.includes('allowContinuity: true') && !observatoryStateRoute.includes('allowContinuity: true'));
check('authenticated runtime bootstrap remains primary-only after user authorization', runtimeBootstrapRoute.includes('if (!ctx.user)') && runtimeBootstrapRoute.includes('readCanonicalGraphState(profile)') && !runtimeBootstrapRoute.includes('allowContinuity: true') && runtimeBootstrapRoute.indexOf('if (!ctx.user)') < runtimeBootstrapRoute.indexOf('readCanonicalGraphState(profile)'));
check('canonical graph marks primary failure when continuity served', canonicalGraphRuntime.includes('primary_graph_read_unavailable_continuity_served') && canonicalGraphRuntime.includes('continuityServed') && canonicalGraphRuntime.includes("readPlane: continuityServed ? 'NEON' : 'SUPABASE'"));
check('canonical graph resolves semantic edge relation before physical compatibility type', canonicalGraphRuntime.includes('function semanticRelation') && canonicalGraphRuntime.includes('attributes.declaredRelations') && canonicalGraphRuntime.includes('attributes.declaredRelation') && canonicalGraphRuntime.includes('const relation = semanticRelation(row, attributes)'));
check('canonical graph preserves legacy evidence_ids as lineage on wide-schema fallback', canonicalGraphRuntime.includes('Array.isArray(row.evidence_ids)') && canonicalGraphRuntime.includes('const lineageSource'));
check('ROOT retains founder continuity projection while institutional Neural is independently authenticated', scenePage.includes("await requireFounderPage('/root')") && scenePage.includes("readCanonicalGraphState('sfi', { allowContinuity: true })") && scenePage.includes('projectCognitiveGraph(canonicalGraph)'));
check('ROOT Cognitive Field attributes topology to canonical read plane and keeps edge provenance', scenePage.includes("readPlane: graph.readPlane ?? 'UNAVAILABLE'") && scenePage.includes('provenance: edge.provenance') && scenePage.includes('lineage: edge.lineage'));
check('ROOT Neural Graph view renders topology without owning persistence', neuralGraphView.includes('SFI-ROOT-NEURAL-GRAPH-1.0') && neuralGraphView.includes('RELATION ≠ CAUSALITY') && neuralGraphView.includes('<svg') && !neuralGraphView.includes("from('graph_nodes')") && !neuralGraphView.includes("from('graph_edges')"));
check('ROOT Neural Graph inspector does not silently truncate adjacent relations', !neuralGraphView.includes('.filter((edge) => edge.source === selected.id || edge.target === selected.id).slice(0, 40)'));
check('ROOT Neural Graph inspector does not silently truncate selected-node lineage', !neuralGraphView.includes('selected.lineage.slice(0, 12)'));
check('ROOT Neural Graph timestamp formatting is hydration-deterministic', neuralGraphView.includes("timeZone: 'America/Mexico_City'"));
check('ROOT temporal reading prefers observed sequence and cycle coordinates before chronology', neuralGraphView.includes("basis: 'SEQUENCE'") && neuralGraphView.includes("basis: 'CYCLE'") && neuralGraphView.includes("basis: 'PHASE'") && neuralGraphView.includes("basis: 'CHRONOLOGY'") && neuralGraphView.includes("['sequence','sequenceIndex','transitionIndex','eventIndex','order']") && neuralGraphView.includes("['cycle','cycleIndex','cycleNumber','recurrence','recurrenceIndex']"));
check('ROOT temporal inspector exposes temporal basis instead of presenting timestamps as the only time model', neuralGraphView.includes('<dt>TEMPORAL BASIS</dt>') && neuralGraphView.includes('<dt>TIME / CYCLE</dt>'));
check('ROOT Neural Graph unavailable read plane does not claim primary active', neuralGraphView.includes("graph.readPlane === 'SUPABASE' ? 'Primary active' : 'Projection / unavailable'"));
check('ROOT itself is the Neural Graph surface without a duplicate neural-graph route or scene', scenePage.includes('RootNeuralGraphView') && !shellUi.includes("href:'/root/neural-graph'") && !scenes.includes("key:'neural-graph'") && !fs.existsSync(path.join(root, 'src/app/root/neural-graph/page.tsx')));

check('ROOT cognitive admission excludes documentary relations regardless of graph materialization', cognitiveAdmission.includes("DOCUMENTARY_RELATION_NOT_COGNITIVE_STATE") && cognitiveAdmission.includes("node.origin === 'library_corpus'") && cognitiveAdmission.includes("projectionKind === 'DOCUMENTARY_RELATION'"));
check('ROOT canonical field preserves graph attributes for Reality Chain reconstruction', scenePage.includes('attributes: node.attributes') && scenePage.includes('attributes: edge.attributes') && scenePage.includes('realityChainCoverage'));
check('ROOT derives bounded method signals from the canonical graph rather than a parallel store', scenePage.includes('deriveCanonicalFieldMethodSignal') && scenePage.includes('graph.nodes.map') && scenePage.includes('graph.edges') && scenePage.includes('methodSignal: methodSignals.get(node.nodeId)'));
check('ROOT inspector exposes field-derived method need without claiming causal explanation', neuralGraphView.includes('FIELD-DERIVED METHOD SIGNAL') && neuralGraphView.includes('<dt>METHOD NEED</dt>') && neuralGraphView.includes("'NOT DERIVED'"));
check('ROOT exposes expectation, discriminator, stopping condition and RETURN as contrast prerequisites', neuralGraphView.includes('EXPECTATION ·') && neuralGraphView.includes('DISCRIMINATOR ·') && neuralGraphView.includes('CONTRAST READINESS ·') && neuralGraphView.includes("'READY TO VERIFY'") && neuralGraphView.includes("'OPEN / INCOMPLETE'"));
check('ROOT distinguishes contrast readiness from governed learning reorganization', neuralGraphView.includes('GOVERNED CONTRAST ·') && neuralGraphView.includes('FIELD REORGANIZATION ·') && neuralGraphView.includes("'LEARNING_QUARANTINED'") && neuralGraphView.includes("'LEARNING_PROMOTED'"));
check('ROOT learning can deform only reversible CURRENT_STATE and RETURN_CONTRAST readings', neuralGraphView.includes("reading !== 'CURRENT_STATE' && reading !== 'RETURN_CONTRAST'") && neuralGraphView.includes('applyReorganizationReading') && neuralGraphView.includes("reorganization === 'LEARNING_PROMOTED'") && neuralGraphView.includes("? 'memory'") && neuralGraphView.includes("? 'learning'") && neuralGraphView.includes("? 'contrast'"));
check('ROOT learning deformation does not persist or overwrite canonical coordinates/history', neuralGraphView.includes('reversible reading transform only') && neuralGraphView.includes('are not persisted or overwritten by learning projection'));
check('ROOT learning deformation magnitude is evidence-modulated rather than a fixed visual offset', neuralGraphView.includes('reorganizationMagnitude') && neuralGraphView.includes('relationSupportRatio') && neuralGraphView.includes('observedWeightDelta') && neuralGraphView.includes('PROVENANCE COVERAGE') && !neuralGraphView.includes("return { x: 54 * direction, y: -24 }"));
check('ROOT abstains from evidence-shaped geometry until Method Lab supplies projection authority', neuralGraphView.includes("projectionAuthority === 'METHOD_LAB_REQUIRED'") && neuralGraphView.includes("return { x: 0, y: 0 }") && neuralGraphView.includes('PROJECTION AUTHORITY ·'));
check('ROOT resolves Method Lab projection from canonical node declaration before geometry', scenePage.includes('resolveMethodLabFieldProjection') && scenePage.includes('methodLabProtocolId') && scenePage.includes('fieldProjection: fieldProjections.get(node.nodeId)'));
check('ROOT consumes only explicit SIMULATED_PROJECTION and otherwise abstains', neuralGraphView.includes("labProjection?.decision !== 'SIMULATED_PROJECTION'") && neuralGraphView.includes('METHOD LAB PROJECTION ·') && neuralGraphView.includes('PROJECTION REASON ·'));
check('ROOT can derive a Method Lab protocol proposal from observed field needs without requiring manual node classification', scenePage.includes('proposeMethodLabFieldProtocol') && scenePage.includes('fieldProtocolProposals') && neuralGraphView.includes('PROTOCOL PROPOSAL ·'));
check('Derived protocol proposal remains epistemically separate from Method Lab simulation output', neuralGraphView.includes("epistemicClass: 'DECLARED' | 'DERIVED'") && neuralGraphView.includes("epistemicClass: 'SIMULATED'"));
check('ROOT reuses canonical MIHM resolution instead of shortcutting PPOI from field flags', scenePage.includes('resolveCanonicalFieldMethodology') && scenePage.includes('fieldMethodResolutions') && scenePage.includes('methodology.resolution.primary?.methodId') && !scenePage.includes("signal.requiresTrajectory || signal.requiresRivalHypothesis ? 'PPOI' : null"));
check('ROOT exposes MIHM resolution before Method Lab protocol proposal', neuralGraphView.includes('MIHM RESOLUTION ·') && neuralGraphView.includes('PROTOCOL PROPOSAL ·'));
check('ROOT preserves subject identity as declared proposed or unknown before MIHM authority', neuralGraphView.includes('SUBJECT IDENTITY ·') && neuralGraphView.includes("subjectBasis: 'DECLARED' | 'PROPOSED' | 'UNKNOWN'"));
check('ROOT does not turn a proposed subject into Method Lab authority', scenePage.includes("methodology.resolution.status === 'READY'") && scenePage.includes("methodology.resolution.primary?.methodId") && !scenePage.includes("subjectProposal"));
check('UNKNOWN is an active resolution state rather than permanent epistemic parking', scenePage.includes('planCanonicalUnknownResolution') && scenePage.includes('unknownResolutionPlans') && neuralGraphView.includes('UNKNOWN RESOLUTION ·'));
check('Unknown resolution is cycle and observation bounded rather than forced into calendar timeout', neuralGraphView.includes('STOPPING CONDITION ·') && neuralGraphView.includes('temporalBasis'));

check('Reality Chain reading exposes canonical v0.1 grammar and MCDC gaps', neuralGraphView.includes('WORLD → CAPTURE → EVIDENCE → TRANSFORMATION → [INFERENCE] → VERIFICATION → AUTHORITY → ACTION → RETURN') && neuralGraphView.includes('MCDC COVERAGE') && neuralGraphView.includes('NOT VERIFIED') && neuralGraphView.includes('NOT OBSERVED'));
check('ROOT readings change deterministic projection rather than object identity', neuralGraphView.includes("reading === 'CURRENT_STATE'") && neuralGraphView.includes("reading === 'TRAJECTORY'") && neuralGraphView.includes("reading === 'RETROLONGITUDINAL'") && neuralGraphView.includes("reading === 'PROJECTION'") && neuralGraphView.includes("reading === 'FRICTION_REGIME'") && neuralGraphView.includes("reading === 'REALITY_CHAIN'") && neuralGraphView.includes("reading === 'RETURN_CONTRAST'") && neuralGraphView.includes('buildPositions(graph.nodes, reading)'));

const failed = checks.filter((item) => !item.ok);
for (const item of checks) console.log(`${item.ok ? 'PASS' : 'FAIL'} · ${item.name}`);
if (failed.length) {
  console.error(`\nROOT graph/operating-workspace convergence QA failed: ${failed.length}/${checks.length}`);
  process.exit(1);
}
console.log(`\nROOT graph/operating-workspace convergence QA passed: ${checks.length}/${checks.length}`);
