import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { spawn } from 'node:child_process';
import ffmpegPath from 'ffmpeg-static';
import type { SfiAudioPerformance, SfiPerformanceEvent } from '../src/lib/studio/audio/acoustic/acousticPackageContract';
import type { SfiProductionInstrumentRow } from '../src/lib/studio/audio/acoustic/productionInstrumentResolver';

const GUITAR: SfiProductionInstrumentRow = { id:'81e744b7-f274-4da9-9e04-b9b7fdbba713', name:'FreePats Spanish Classical Guitar', family:'acoustic_guitar', engine:'SFZ', packageRef:'https://raw.githubusercontent.com/freepats/spanish-classical-guitar/6f4eb1b092acc88f5448cea1a0001bd07b971af8/SpanishClassicalGuitar-20190618.sfz', packageHash:'git:6f4eb1b092acc88f5448cea1a0001bd07b971af8', license:'CC0-1.0', rightsStatus:'DERIVATIVE_ALLOWED', rightsEvidenceRef:'https://github.com/freepats/spanish-classical-guitar/blob/6f4eb1b092acc88f5448cea1a0001bd07b971af8/LICENSE', rangeLow:29, rangeHigh:88, articulations:['sustain'], sampleRate:48000, culturalProfiles:['ranchero_pop','regional_mexicano','acoustic_pop'], verifiedAt:'2026-09-08T09:25:17.858503Z' };
const BASS: SfiProductionInstrumentRow = { id:'421405bd-4e98-4df8-968a-12a181602cca', name:'FreePats Finger Bass YR', family:'bass', engine:'SFZ', packageRef:'https://raw.githubusercontent.com/freepats/electric-bass-YR/8dcb7ea9116f417273ef8c030d15e7b3aa654301/FingerBassYR%2020190930.sfz', packageHash:'git:8dcb7ea9116f417273ef8c030d15e7b3aa654301', license:'CC0-1.0', rightsStatus:'DERIVATIVE_ALLOWED', rightsEvidenceRef:'https://github.com/freepats/electric-bass-YR/blob/8dcb7ea9116f417273ef8c030d15e7b3aa654301/LICENSE.txt', rangeLow:26, rangeHigh:45, articulations:['sustain'], sampleRate:48000, culturalProfiles:['ranchero_pop','regional_mexicano','acoustic_pop'], verifiedAt:'2026-09-08T09:25:17.858503Z' };

function event(id:string,note:number,startSeconds:number,durationSeconds:number,velocity:number,sourceRef:string):SfiPerformanceEvent { return { eventId:id,startSeconds,durationSeconds,note,velocity,articulation:null,microtimingSeconds:0,controls:{gainDb:0,pitchBendCents:0,vibratoDepthCents:0,vibratoHz:0},roomSend:0,provenance:{sourceRef,plannerRef:'SFI-MATERIAL-PRODUCTION-REAL-QA-1.0'} }; }
function performance(instrument:SfiProductionInstrumentRow,role:string,notes:number[]):SfiAudioPerformance { return { contract:'SFI-AUDIO-PERFORMANCE-1.0',performanceId:`qa-${role}`,performanceVersion:'1.0.0',instrumentRef:instrument.id,tempoBpm:112,timeSignature:[4,4],events:notes.map((note,index)=>event(`${role}-${index}`,note,index*0.45,0.38,index===0?100:84,'fixture:voice-like-source')) }; }
function ffmpeg(args:string[]) { if(!ffmpegPath) throw new Error('SFI_FFMPEG_UNAVAILABLE'); return new Promise<void>((ok,fail)=>{ const child=spawn(ffmpegPath,['-hide_banner','-loglevel','error','-y',...args],{stdio:['ignore','ignore','pipe']}); let stderr=''; child.stderr.on('data',(chunk)=>{stderr+=String(chunk)}); child.on('error',fail); child.on('close',(code)=>code===0?ok():fail(new Error(`SFI_REAL_PRODUCTION_FFMPEG_FAILED:${code}:${stderr.slice(-1200)}`))); }); }
function sha256(bytes:Buffer){ return `sha256:${createHash('sha256').update(bytes).digest('hex')}`; }
async function ensureServerOnlyCliShim(){ const dir=resolve('node_modules/server-only'); await mkdir(dir,{recursive:true}); await writeFile(resolve(dir,'package.json'),'{"name":"server-only","version":"0.0.0-sfi-qa","main":"index.js"}\n','utf8'); await writeFile(resolve(dir,'index.js'),'module.exports = {};\n','utf8'); }
function requirements(performance:SfiAudioPerformance){ return performance.events.map(({note,velocity})=>({note,velocity})); }

async function main(){
  await ensureServerOnlyCliShim();
  const [{materializeRemoteAcousticPackage},{executeSfzAcousticRender}] = await Promise.all([import('../src/lib/studio/audio/acoustic/remotePackageMaterializer'),import('../src/lib/studio/audio/acoustic/executeSfzRender')]);
  const build=resolve('build/sfi-audio/material-production-real'); const workspace=resolve(build,'workspace'); const source=resolve('fixtures/audio/sfi-acoustic-instrument-package-1.0/samples/qa-tone.wav');
  const guitarPath=resolve(build,'guitar.wav'); const bassPath=resolve(build,'bass.wav'); const mixPath=resolve(build,'voice-plus-instruments.wav'); const masterPath=resolve(build,'musicalized-master.wav'); const receiptPath=resolve(build,'material-production-real-receipt.json');
  await rm(build,{recursive:true,force:true}); await mkdir(workspace,{recursive:true});
  try {
    const guitarPerformance=performance(GUITAR,'guitar',[55,59,62,67]); const bassPerformance=performance(BASS,'bass',[31,35,38,43]);
    const guitarPackage=await materializeRemoteAcousticPackage({instrument:GUITAR,requiredEvents:requirements(guitarPerformance),workspace});
    const bassPackage=await materializeRemoteAcousticPackage({instrument:BASS,requiredEvents:requirements(bassPerformance),workspace});
    assert.equal(guitarPackage.sourceCommit,'6f4eb1b092acc88f5448cea1a0001bd07b971af8'); assert.equal(bassPackage.sourceCommit,'8dcb7ea9116f417273ef8c030d15e7b3aa654301'); assert.equal(guitarPackage.manifest.rights.publicAccessUsedAsRightsEvidence,false); assert.equal(bassPackage.manifest.rights.publicAccessUsedAsRightsEvidence,false);
    const authorizationRef='qa:ws06:real-material-production:execute-reversible';
    const guitarReceipt=await executeSfzAcousticRender({runId:'qa-real-guitar-render',packageRoot:guitarPackage.packageRoot,packageRef:GUITAR.packageRef,performance:guitarPerformance,performanceRef:'qa:performance:guitar',rightsAssertions:{instrumentRightsStatus:'DERIVATIVE_ALLOWED',materialRightsEligibility:'ELIGIBLE',materialRightsEvidenceRefs:[GUITAR.rightsEvidenceRef],institutionalAuthorization:{authorizationRef,authorityClass:'EXECUTE_REVERSIBLE',authorized:true},culturalReferenceUsedAsExecutableMaterial:false,publicAccessUsedAsExecutionRightsEvidence:false},artifactPath:guitarPath,artifactRef:'ci-artifact:material-production-real/guitar.wav'});
    const bassReceipt=await executeSfzAcousticRender({runId:'qa-real-bass-render',packageRoot:bassPackage.packageRoot,packageRef:BASS.packageRef,performance:bassPerformance,performanceRef:'qa:performance:bass',rightsAssertions:{instrumentRightsStatus:'DERIVATIVE_ALLOWED',materialRightsEligibility:'ELIGIBLE',materialRightsEvidenceRefs:[BASS.rightsEvidenceRef],institutionalAuthorization:{authorizationRef,authorityClass:'EXECUTE_REVERSIBLE',authorized:true},culturalReferenceUsedAsExecutableMaterial:false,publicAccessUsedAsExecutionRightsEvidence:false},artifactPath:bassPath,artifactRef:'ci-artifact:material-production-real/bass.wav'});
    assert.equal(guitarReceipt.cleanup.state,'CLEANED'); assert.equal(bassReceipt.cleanup.state,'CLEANED'); assert.ok(guitarReceipt.metrics.renderedEventCount>=4); assert.ok(bassReceipt.metrics.renderedEventCount>=4);
    await ffmpeg(['-i',source,'-i',guitarPath,'-i',bassPath,'-filter_complex','[0:a]volume=-1.5dB[v];[1:a]volume=-7dB[g];[2:a]volume=-5dB[b];[v][g][b]amix=inputs=3:normalize=0,aresample=48000[mix]','-map','[mix]','-ar','48000','-ac','2','-c:a','pcm_s24le',mixPath]);
    await ffmpeg(['-i',mixPath,'-af','highpass=f=28,loudnorm=I=-12:LRA=8:TP=-1.0,alimiter=limit=0.891:attack=5:release=50','-ar','48000','-ac','2','-c:a','pcm_s24le',masterPath]);
    const master=await readFile(masterPath); assert.ok(master.byteLength>1000); const masterHash=sha256(master); assert.match(masterHash,/^sha256:[0-9a-f]{64}$/);
    const receipt={contract:'SFI-MATERIAL-PRODUCTION-REAL-QA-1.0',status:'PASS',source:'fixture:voice-like-source',upstream:{guitar:{commit:guitarPackage.sourceCommit,license:'CC0-1.0',rightsEvidenceRef:GUITAR.rightsEvidenceRef},bass:{commit:bassPackage.sourceCommit,license:'CC0-1.0',rightsEvidenceRef:BASS.rightsEvidenceRef}},canonicalRender:{guitar:{runId:guitarReceipt.runId,hash:guitarReceipt.output.sha256,events:guitarReceipt.metrics.renderedEventCount},bass:{runId:bassReceipt.runId,hash:bassReceipt.output.sha256,events:bassReceipt.metrics.renderedEventCount}},mix:{includesAuthorizedSource:true,includesRealSampleStems:true},master:{ref:'ci-artifact:material-production-real/musicalized-master.wav',sha256:masterHash,bytes:master.byteLength},authority:{execution:'EXECUTE_REVERSIBLE',rightsTransfer:false,canonicalPromotion:false},midiUsedAsSoundSource:false,publicAccessUsedAsRightsEvidence:false,velocityAwareMaterialization:true};
    await writeFile(receiptPath,`${JSON.stringify(receipt,null,2)}\n`,'utf8'); console.log(JSON.stringify(receipt,null,2));
  } finally { await rm(workspace,{recursive:true,force:true}); }
}
main().catch((error)=>{console.error(error);process.exitCode=1});
