export type SfiInstitutionMilestone = {
  id: string;
  occurredAt: string;
  title: string;
  summary: string;
  epistemicClass: 'OBSERVED';
  sourceType: 'github_repository' | 'github_pr' | 'github_commit' | 'live_site';
  sourceUrl: string;
  sourceLabel: string;
};

export const SFI_INSTITUTION_HISTORY: SfiInstitutionMilestone[] = [
  {
    id: 'SFI-HIST-20260222-REPOSITORY',
    occurredAt: '2026-02-22T00:26:38Z',
    title: "Public system-friction repository created",
    summary: "First verifiable technical origin of the current public repository. It documents the observable beginning of the code archive without turning that date into a claim about the institute’s earlier conceptual origin.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_repository',
    sourceUrl: 'https://github.com/Aptymok/system-friction',
    sourceLabel: 'GitHub repository metadata',
  },
  {
    id: 'SFI-HIST-20260514-CT-EARLY',
    occurredAt: '2026-05-14T23:47:41-06:00',
    title: "First verifiable Cognitive Twin milestone in the repository",
    summary: "Public history records a commit dedicated to cognitive_twin. It is preserved as the first verifiable point of that technical line in the current repository.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/e79a16cae509cde264b9fc57d80c1694194efc23',
    sourceLabel: 'commit e79a16ca',
  },
  {
    id: 'SFI-HIST-20260521-CT-PHASE15',
    occurredAt: '2026-05-21T22:12:54-06:00',
    title: "Cognitive Twin formalized as an architecture phase",
    summary: "The repository records Phase15: Cognitive Twin, showing that the Twin moved from an isolated component to an explicit phase of the developing architecture.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/714c15a83a6bc43ac8ee3d4a7099746f99dc5d80',
    sourceLabel: 'commit 714c15a8',
  },
  {
    id: 'SFI-HIST-20260529-OBS-MIHM-CT',
    occurredAt: '2026-05-29T00:21:24-06:00',
    title: "Observatory, MIHM and Cognitive Twin converge on one field dataset",
    summary: "The Observatory runtime, static field dataset, MIHM matrix and a Cognitive Twin seed were reconciled, creating one of the first verifiable connections among observation, method and cognitive reconstruction.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/e0fb0e8e8ab7d1dc8b0f273df2d07cc224199e37',
    sourceLabel: 'commit e0fb0e8e / PR #54',
  },
  {
    id: 'SFI-HIST-20260529-MIHM-SCHEMA',
    occurredAt: '2026-05-29T02:58:24-06:00',
    title: "MIHM aligned with the real persistent schema",
    summary: "The MIHM process was aligned with the actual mihm_analyses table and the runtime began reading the vector from the persistent schema instead of a parallel representation.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/5635daba7d85f73a852206707c007f7a04e5b83f',
    sourceLabel: 'commit 5635daba / PR #58',
  },
  {
    id: 'SFI-HIST-20260531-CT-EVIDENCE',
    occurredAt: '2026-05-31T18:59:45-06:00',
    title: "Cognitive Twin proposals anchored to field evidence",
    summary: "Twin proposals were linked to evidence from the field seed. This milestone makes the separation between cognitive proposal and supporting evidence explicit.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/559d9efb9f563f96cdfd68bc335ae4c1f0674295',
    sourceLabel: 'commit 559d9efb / PR #63',
  },
  {
    id: 'SFI-HIST-20260607-ROOT',
    occurredAt: '2026-06-07T16:04:52-06:00',
    title: "ROOT closes foundational phases 0–11",
    summary: "ROOT integrated live nodes, logbook, viewer, Twin, World State/Vector, MIHM, attractor and governance. The repository records phases 0–11 as a shared operational foundation.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/7f35a0937dd9cf964ee73cf6b168516fdd9e1ab4',
    sourceLabel: 'commit 7f35a093 / PR #79',
  },
  {
    id: 'SFI-HIST-20260711-STUDIO-CONTEXT',
    occurredAt: '2026-07-11T06:42:00-06:00',
    title: "Studio interprets objects against world context and partial MIHM",
    summary: "Studio incorporated persistent-context synthesis, gating by declared attractor, MIHM variables with coverage, longitudinal Cultural/WorldSpect context, verification and falsification criteria, and reversible intervention candidates.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/44ac99a47ebf045a26d349f6dfa0fc4172c039b6',
    sourceLabel: 'commit 44ac99a4',
  },
  {
    id: 'SFI-HIST-20260716-INSTRUMENT-STATES',
    occurredAt: '2026-07-16T23:59:30-06:00',
    title: "Instrument states normalized across MIHM, World Vector, PPOI and Φ",
    summary: "The architecture introduced explicit instrument-state contracts and joint normalization across MIHM, World Vector, PPOI and Φ to reduce divergence between surfaces and runtime.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/256e3ecc0d4b4b5e7379e867ecb0ed00e538d82f',
    sourceLabel: 'commit 256e3ecc',
  },
  {
    id: 'SFI-HIST-20260805-MIHM-REGISTRY',
    occurredAt: '2026-08-05T18:11:29-06:00',
    title: "Canonical MIHM methodology registry",
    summary: "A canonical registry for MIHM methodology selection was added, followed by a central resolver linking ROOT cases to an explicit and verifiable method selection.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/95396b31d121140bdb6ebaf2a0664cab5353ea3a',
    sourceLabel: 'commit 95396b31',
  },
  {
    id: 'SFI-HIST-20260806-METHOD-LAB-CANON',
    occurredAt: '2026-08-06T17:42:23-06:00',
    title: "Method Lab and simulation canon",
    summary: "Method Lab appears formally as the governed container for simulation and experimentation, preserving the distinction between simulated results and observation of the world.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/f777db1f3135142bf6cd3b70c1b45f6eb2f0b97b',
    sourceLabel: 'commit f777db1f',
  },
  {
    id: 'SFI-HIST-20260806-CT-AUTHORITY',
    occurredAt: '2026-08-06T17:43:08-06:00',
    title: "Authority canon for Cognitive Twin and agents",
    summary: "An explicit authority canon was introduced to separate Twin and agent capabilities from institutional decision authority.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/5a4b1594f3cbb0f2d9dab5eb2dbc4d0a549e381f',
    sourceLabel: 'commit 5a4b1594',
  },
  {
    id: 'SFI-HIST-20260807-CT-CORE',
    occurredAt: '2026-08-07T06:24:45-06:00',
    title: "Model-independent Cognitive Twin core",
    summary: "A model-provider-independent Cognitive Twin core was established with governed persistence, authority invariants and runtime views readable by operators.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/3dcf995d8c131eb2666113b53b385b6b4ae3084e',
    sourceLabel: 'commit 3dcf995d',
  },
  {
    id: 'SFI-HIST-20260807-INSTITUTIONAL-CYCLE',
    occurredAt: '2026-08-07T09:35:12-06:00',
    title: "Institutional cycle linked to evidence",
    summary: "SFI connected persisted evidence with Twin memory, the institutional attractor, cognitive cycles, active runtime contracts and a public surface that fails closed when verifiable storage is unavailable.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/66164090b4cedd760850437879fccc26f9143f52',
    sourceLabel: 'commit 66164090 / PR #167',
  },
  {
    id: 'SFI-HIST-20260809-TWIN-LLM',
    occurredAt: '2026-08-09T10:04:38-06:00',
    title: "Cognitive agents augmented through a Twin-linked LLM gateway",
    summary: "The existing runtime introduced an LLM gateway connected to the Cognitive Twin to augment agents without converting model output into canonical authority.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/0afe0534f9636558d990f0e4000ee042ff43b3be',
    sourceLabel: 'commit 0afe0534',
  },
  {
    id: 'SFI-HIST-20260809-LONGITUDINAL-ROOT',
    occurredAt: '2026-08-09T10:44:22-06:00',
    title: "ROOT becomes longitudinal, contextual and conversational",
    summary: "Twin LLM deliberation, historical WorldSpect reconstruction, prediction cases, a longitudinal temporal observer, a decision queue and retrospective semantic context were introduced while preserving missing values as missing.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/f80ccb12cd16055255a4170a5334ddd4dd5165df',
    sourceLabel: 'commit f80ccb12',
  },
  {
    id: 'SFI-HIST-20260810-EVIDENCE-GRAPH',
    occurredAt: '2026-08-10T19:54:09-06:00',
    title: "Canonical evidence graph reconstructed",
    summary: "Evidence identity was canonicalized across ROOT and the ledger, the graph was rebuilt as a derived projection, and ROOT was connected to the real Cognitive Twin state while visible predictive placeholders were removed.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/b8804ab0d5375d8d721982426185e5df396996c9',
    sourceLabel: 'commit b8804ab0 / PR #199',
  },
  {
    id: 'SFI-HIST-20260811-METHOD-LAB-UNIFIED',
    occurredAt: '2026-08-11T01:45:48-06:00',
    title: "CHRONOS, CRL and simulations converge in one Method Lab",
    summary: "CHRONOS/Cognitive Olympics, CRL and sociotechnical/economic simulations were consolidated under one Method Lab contract, keeping SIMULATED separate from OBSERVED and exposing protocol health in ROOT.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/01a588dfb7fb694e7d9973882a8d3dc90378f0f2',
    sourceLabel: 'commit 01a588df / PR #201',
  },
  {
    id: 'SFI-HIST-20260811-CT-LONGITUDINAL',
    occurredAt: '2026-08-11T10:13:03-06:00',
    title: "Longitudinal Cognitive Twin circuit completed",
    summary: "A development journal, governed snapshots, experimental forks, mutation proposals and reconciliation with World Vector and MOP-S were added while keeping promotion and authority separate.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/f92db304a8f01fd8de55599f56350f7642a11c0f',
    sourceLabel: 'commit f92db304',
  },
  {
    id: 'SFI-HIST-20260811-FIELD-RETURN',
    occurredAt: '2026-08-11T13:17:38-06:00',
    title: "Studio → Field → RETURN wired as a verifiable cycle",
    summary: "Studio began emitting immutable handoffs; Field preserves identity through T0 and RETURN, freezes rivals and stopping terms, and requires Return/Contrast before closing the cycle.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/5bf0faeab4d0f16545f9630ce5bb7aeb758181d6',
    sourceLabel: 'commit 5bf0faea / PR #206',
  },
  {
    id: 'SFI-HIST-20260811-LAB-TO-TWIN',
    occurredAt: '2026-08-11T13:49:36-06:00',
    title: "Method Lab runs feed Cognitive Twin experience",
    summary: "Laboratory executions were explicitly connected to Twin experience while preserving the epistemic mode of each run during synchronization.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/cf6c679d57963087ae117dfb69941b564ebf75ef',
    sourceLabel: 'commit cf6c679d',
  },
  {
    id: 'SFI-HIST-20260815-DECISION-TRANSFER',
    occurredAt: '2026-08-15T18:33:25-06:00',
    title: "Decision Transfer operationalized in Method Lab",
    summary: "Method Lab incorporated the decision-transfer phase with explicit validation limits: simulation and derivation remain diagnostic until sufficient observed/verified contrast exists.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/57dbd26d41e19a50f7649196805d1e586757e112',
    sourceLabel: 'commit 57dbd26d',
  },
  {
    id: 'SFI-HIST-20260816-SYSTEM-AI',
    occurredAt: '2026-08-16T14:47:03Z',
    title: "System / AI Assurance V1 domain",
    summary: "A tenant-scoped domain was consolidated for system observability, AI implementation diagnosis, integration/adoption and governance assurance on the existing Case Platform.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/245',
    sourceLabel: 'PR #245',
  },
  {
    id: 'SFI-HIST-20260816-LIVING-MEMBRANE',
    occurredAt: '2026-08-16T15:30:25Z',
    title: "Navigable institutional membrane",
    summary: "The institutional entry was reorganized as a continuous surface for observation, interaction and access while preserving boundaries among presentation, evidence, simulation, governance and authority.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/248',
    sourceLabel: 'PR #248',
  },
  {
    id: 'SFI-HIST-20260816-EMERGENCE',
    occurredAt: '2026-08-16T16:42:45Z',
    title: "Public governed-emergence program",
    summary: "SFI materialized a public layer for observing its own emergence with explicit separation among publication, attention, engagement, evidence and causality.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/251',
    sourceLabel: 'PR #251',
  },
  {
    id: 'SFI-HIST-20260821-CONVERGENCE',
    occurredAt: '2026-08-21T10:26:00Z',
    title: "Convergence on observation, evidence and RETURN",
    summary: "Heuristic routes and remaining synthetic state were removed, requiring real cases and evidence, execution traceability and persisted RETURN without creating a parallel architecture.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/260',
    sourceLabel: 'PR #260',
  },
  {
    id: 'SFI-HIST-20260821-FRONTEND',
    occurredAt: '2026-08-21T23:34:16Z',
    title: "Full frontend replacement and external agent gateway",
    summary: "The legacy frontend was replaced by live scenes while preserving the existing backend. Manifest, observe, propose, execute and Method Lab capabilities were added for governed AI clients.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/262',
    sourceLabel: 'PR #262',
  },
  {
    id: 'SFI-HIST-20260822-METHODLAB-FIX',
    occurredAt: '2026-08-22T07:53:54Z',
    title: "Persistent Method Lab read corrected",
    summary: "Ambiguity in reading sfi_lab_analyses that produced a WITHIN GROUP error on the mode column was corrected.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/44ec16a53e9b7034a30e0a78886d1b44c3031486',
    sourceLabel: 'commit 44ec16a5',
  },
  {
    id: 'SFI-HIST-20260822-AI-CONSOLE',
    occurredAt: '2026-08-22T08:10:23Z',
    title: "Consolidated console for AI agents",
    summary: "The external API added a consolidated read of Method Lab, reports, Cognitive Twin, proposals, evidence, runs and agent capabilities for authorized clients.",
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/79665191fb7b99bcc775c25b0e836497ff8203fc',
    sourceLabel: 'commit 79665191',
  },
  {
    id: 'SFI-HIST-20260822-LIVE',
    occurredAt: '2026-08-22T19:06:25Z',
    title: "Current observable technical state",
    summary: "The public repository remains active on main and the canonical public surface is presented as a LIVE OBSERVATION SURFACE at systemfriction.org.",
    epistemicClass: 'OBSERVED',
    sourceType: 'live_site',
    sourceUrl: 'https://systemfriction.org',
    sourceLabel: 'systemfriction.org + GitHub repository metadata',
  },
];

export const SFI_HISTORY_BOUNDARY =
  'This chronology contains only milestones verifiable through SFI/GitHub public sources. It does not fill undocumented periods, convert a code date into a claim about the institute’s conceptual origin, or present runtime capability as empirical validation.';
