export type SfiInstitutionMilestone = {
  id: string;
  occurredAt: string;
  title: string;
  summary: string;
  epistemicClass: 'OBSERVED';
  sourceType: 'github_repository' | 'github_pr' | 'github_commit' | 'live_site';
  sourceUrl: string;
  sourceLabel: string;
};

export const SFI_INSTITUTION_HISTORY: SfiInstitutionMilestone[] = [
  {
    id: 'SFI-HIST-20260222-REPOSITORY',
    occurredAt: '2026-02-22T00:26:38Z',
    title: 'Repositorio público system-friction creado',
    summary: 'Primer origen técnico verificable del repositorio público actual. Documenta el inicio observable del archivo de código, sin convertirlo en una afirmación sobre el origen conceptual previo del instituto.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_repository',
    sourceUrl: 'https://github.com/Aptymok/system-friction',
    sourceLabel: 'GitHub repository metadata',
  },
  {
    id: 'SFI-HIST-20260514-CT-EARLY',
    occurredAt: '2026-05-14T23:47:41-06:00',
    title: 'Primer hito verificable del Cognitive Twin en el repositorio',
    summary: 'El historial público registra un commit dedicado al cognitive_twin. Se conserva como el primer punto verificable de esa línea técnica en el repositorio actual.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/e79a16cae509cde264b9fc57d80c1694194efc23',
    sourceLabel: 'commit e79a16ca',
  },
  {
    id: 'SFI-HIST-20260521-CT-PHASE15',
    occurredAt: '2026-05-21T22:12:54-06:00',
    title: 'Cognitive Twin formalizado como fase de arquitectura',
    summary: 'El repositorio registra Fase15: Cognitive Twin, señalando que el Twin pasó de ser una pieza aislada a una fase explícita de la arquitectura en desarrollo.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/714c15a83a6bc43ac8ee3d4a7099746f99dc5d80',
    sourceLabel: 'commit 714c15a8',
  },
  {
    id: 'SFI-HIST-20260529-OBS-MIHM-CT',
    occurredAt: '2026-05-29T00:21:24-06:00',
    title: 'Observatory, MIHM y Cognitive Twin convergen sobre un mismo dataset de campo',
    summary: 'Se reconciliaron el runtime de Observatory, el dataset estático de campo, la matriz MIHM y una semilla del Cognitive Twin, creando una de las primeras conexiones verificables entre observación, método y reconstrucción cognitiva.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/e0fb0e8e8ab7d1dc8b0f273df2d07cc224199e37',
    sourceLabel: 'commit e0fb0e8e / PR #54',
  },
  {
    id: 'SFI-HIST-20260529-MIHM-SCHEMA',
    occurredAt: '2026-05-29T02:58:24-06:00',
    title: 'MIHM alineado con esquema persistente real',
    summary: 'El proceso MIHM fue alineado con la tabla real mihm_analyses y el runtime comenzó a leer el vector desde el esquema persistente en lugar de una representación paralela.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/5635daba7d85f73a852206707c007f7a04e5b83f',
    sourceLabel: 'commit 5635daba / PR #58',
  },
  {
    id: 'SFI-HIST-20260531-CT-EVIDENCE',
    occurredAt: '2026-05-31T18:59:45-06:00',
    title: 'Propuestas del Cognitive Twin ancladas a evidencia de campo',
    summary: 'Las propuestas del Twin quedaron vinculadas a evidencia de la semilla de campo. Este hito hace explícita la separación entre propuesta cognitiva y evidencia que la sustenta.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/559d9efb9f563f96cdfd68bc335ae4c1f0674295',
    sourceLabel: 'commit 559d9efb / PR #63',
  },
  {
    id: 'SFI-HIST-20260607-ROOT',
    occurredAt: '2026-06-07T16:04:52-06:00',
    title: 'ROOT cierra fases fundacionales 0–11',
    summary: 'ROOT integró nodos vivos, logbook, visor, Twin, World State/Vector, MIHM, attractor y gobernanza. El repositorio registra el cierre de las fases 0–11 como una fundación operativa común.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/7f35a0937dd9cf964ee73cf6b168516fdd9e1ab4',
    sourceLabel: 'commit 7f35a093 / PR #79',
  },
  {
    id: 'SFI-HIST-20260711-STUDIO-CONTEXT',
    occurredAt: '2026-07-11T06:42:00-06:00',
    title: 'Studio interpreta objetos contra contexto mundial y MIHM parcial',
    summary: 'Studio incorporó síntesis de contexto persistente, gating por attractor declarado, variables MIHM con cobertura, contexto longitudinal Cultural/WorldSpect, criterios de verificación y falsificación y candidatos de intervención reversibles.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/44ac99a47ebf045a26d349f6dfa0fc4172c039b6',
    sourceLabel: 'commit 44ac99a4',
  },
  {
    id: 'SFI-HIST-20260716-INSTRUMENT-STATES',
    occurredAt: '2026-07-16T23:59:30-06:00',
    title: 'Estados instrumentales normalizados entre MIHM, World Vector, PPOI y Φ',
    summary: 'La arquitectura incorporó contratos explícitos de estado instrumental y una normalización conjunta de MIHM, World Vector, PPOI y Φ para reducir divergencia entre superficies y runtime.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/256e3ecc0d4b4b5e7379e867ecb0ed00e538d82f',
    sourceLabel: 'commit 256e3ecc',
  },
  {
    id: 'SFI-HIST-20260805-MIHM-REGISTRY',
    occurredAt: '2026-08-05T18:11:29-06:00',
    title: 'Registro canónico de metodologías MIHM',
    summary: 'Se agregó un registro canónico para selección metodológica MIHM y posteriormente un resolver central, vinculando los casos de ROOT con una selección de método explícita y verificable.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/95396b31d121140bdb6ebaf2a0664cab5353ea3a',
    sourceLabel: 'commit 95396b31',
  },
  {
    id: 'SFI-HIST-20260806-METHOD-LAB-CANON',
    occurredAt: '2026-08-06T17:42:23-06:00',
    title: 'Method Lab y canon de simulación',
    summary: 'Method Lab aparece formalmente como el contenedor gobernado para simulación y experimentación, manteniendo la distinción entre resultados simulados y observación del mundo.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/f777db1f3135142bf6cd3b70c1b45f6eb2f0b97b',
    sourceLabel: 'commit f777db1f',
  },
  {
    id: 'SFI-HIST-20260806-CT-AUTHORITY',
    occurredAt: '2026-08-06T17:43:08-06:00',
    title: 'Canon de autoridad para Cognitive Twin y agentes',
    summary: 'Se incorporó un canon explícito de autoridad que separa capacidades del Twin y agentes de la autoridad de decisión institucional.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/5a4b1594f3cbb0f2d9dab5eb2dbc4d0a549e381f',
    sourceLabel: 'commit 5a4b1594',
  },
  {
    id: 'SFI-HIST-20260807-CT-CORE',
    occurredAt: '2026-08-07T06:24:45-06:00',
    title: 'Core model-independent del Cognitive Twin',
    summary: 'Se estableció un core del Cognitive Twin independiente del proveedor de modelo, con persistencia gobernada, invariantes de autoridad y vistas de runtime legibles por operadores.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/3dcf995d8c131eb2666113b53b385b6b4ae3084e',
    sourceLabel: 'commit 3dcf995d',
  },
  {
    id: 'SFI-HIST-20260807-INSTITUTIONAL-CYCLE',
    occurredAt: '2026-08-07T09:35:12-06:00',
    title: 'Ciclo institucional vinculado a evidencia',
    summary: 'SFI conectó evidencia persistida con memoria del Twin, attractor institucional, ciclos cognitivos, contratos activos de runtime y una superficie pública que falla cerrada cuando no existe almacenamiento verificable.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/66164090b4cedd760850437879fccc26f9143f52',
    sourceLabel: 'commit 66164090 / PR #167',
  },
  {
    id: 'SFI-HIST-20260809-TWIN-LLM',
    occurredAt: '2026-08-09T10:04:38-06:00',
    title: 'Agentes cognitivos aumentados mediante gateway LLM ligado al Twin',
    summary: 'El runtime existente incorporó un gateway LLM unido al Cognitive Twin para aumentar agentes sin convertir la salida del modelo en autoridad canónica.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/0afe0534f9636558d990f0e4000ee042ff43b3be',
    sourceLabel: 'commit 0afe0534',
  },
  {
    id: 'SFI-HIST-20260809-LONGITUDINAL-ROOT',
    occurredAt: '2026-08-09T10:44:22-06:00',
    title: 'ROOT se vuelve longitudinal, contextual y conversacional',
    summary: 'Se incorporaron deliberación LLM del Twin, reconstrucción histórica WorldSpect, casos de predicción, observador temporal longitudinal, cola de decisiones y contexto semántico retrospectivo, preservando valores faltantes como faltantes.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/f80ccb12cd16055255a4170a5334ddd4dd5165df',
    sourceLabel: 'commit f80ccb12',
  },
  {
    id: 'SFI-HIST-20260810-EVIDENCE-GRAPH',
    occurredAt: '2026-08-10T19:54:09-06:00',
    title: 'Reconstrucción del grafo canónico de evidencia',
    summary: 'Se canonicalizó la identidad de evidencia entre ROOT y ledger, se reconstruyó el grafo como proyección derivada y se conectó ROOT al estado real del Cognitive Twin, eliminando placeholders predictivos visibles.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/b8804ab0d5375d8d721982426185e5df396996c9',
    sourceLabel: 'commit b8804ab0 / PR #199',
  },
  {
    id: 'SFI-HIST-20260811-METHOD-LAB-UNIFIED',
    occurredAt: '2026-08-11T01:45:48-06:00',
    title: 'CHRONOS, CRL y simulaciones convergen en un único Method Lab',
    summary: 'CHRONOS/Cognitive Olympics, CRL y simulaciones sociotécnicas/económicas fueron consolidadas bajo un contrato común de Method Lab, manteniendo separado SIMULATED de OBSERVED y haciendo visible la salud de los protocolos en ROOT.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/01a588dfb7fb694e7d9973882a8d3dc90378f0f2',
    sourceLabel: 'commit 01a588df / PR #201',
  },
  {
    id: 'SFI-HIST-20260811-CT-LONGITUDINAL',
    occurredAt: '2026-08-11T10:13:03-06:00',
    title: 'Circuito longitudinal del Cognitive Twin completado',
    summary: 'Se agregaron journal de desarrollo, snapshots gobernados, forks experimentales, propuestas de mutación y reconciliación con World Vector y MOP-S, manteniendo promoción y autoridad separadas.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/f92db304a8f01fd8de55599f56350f7642a11c0f',
    sourceLabel: 'commit f92db304',
  },
  {
    id: 'SFI-HIST-20260811-FIELD-RETURN',
    occurredAt: '2026-08-11T13:17:38-06:00',
    title: 'Studio → Field → Return queda cableado como ciclo verificable',
    summary: 'Studio comenzó a emitir handoffs inmutables; Field preserva identidad a través de T0 y retorno, congela rivales y stopping terms y exige Return/Contrast antes de cerrar el ciclo.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/5bf0faeab4d0f16545f9630ce5bb7aeb758181d6',
    sourceLabel: 'commit 5bf0faea / PR #206',
  },
  {
    id: 'SFI-HIST-20260811-LAB-TO-TWIN',
    occurredAt: '2026-08-11T13:49:36-06:00',
    title: 'Runs de Method Lab alimentan experiencia del Cognitive Twin',
    summary: 'Las ejecuciones del laboratorio se conectaron explícitamente con la experiencia del Twin, preservando después los modos epistemológicos de cada run durante la sincronización.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/cf6c679d57963087ae117dfb69941b564ebf75ef',
    sourceLabel: 'commit cf6c679d',
  },
  {
    id: 'SFI-HIST-20260815-DECISION-TRANSFER',
    occurredAt: '2026-08-15T18:33:25-06:00',
    title: 'Decision Transfer operacionalizado en Method Lab',
    summary: 'Method Lab incorporó la fase de transferencia de decisión con límites explícitos de validación: simulación y derivación permanecen diagnósticas hasta existir contraste observado/verificado suficiente.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/57dbd26d41e19a50f7649196805d1e586757e112',
    sourceLabel: 'commit 57dbd26d',
  },
  {
    id: 'SFI-HIST-20260816-SYSTEM-AI',
    occurredAt: '2026-08-16T14:47:03Z',
    title: 'Dominio System / AI Assurance V1',
    summary: 'Se consolidó un dominio tenant-scoped para observabilidad de sistemas, diagnóstico de implementación de IA, integración/adopción y assurance de gobernanza sobre la Case Platform existente.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/245',
    sourceLabel: 'PR #245',
  },
  {
    id: 'SFI-HIST-20260816-LIVING-MEMBRANE',
    occurredAt: '2026-08-16T15:30:25Z',
    title: 'Membrana institucional navegable',
    summary: 'La entrada institucional se reorganizó como una superficie continua de observación, interacción y acceso, preservando límites entre presentación, evidencia, simulación, gobernanza y autoridad.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/248',
    sourceLabel: 'PR #248',
  },
  {
    id: 'SFI-HIST-20260816-EMERGENCE',
    occurredAt: '2026-08-16T16:42:45Z',
    title: 'Programa público de emergencia gobernada',
    summary: 'SFI materializó una capa pública de observación de su propia emergencia, con separación explícita entre publicación, atención, engagement, evidencia y causalidad.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/251',
    sourceLabel: 'PR #251',
  },
  {
    id: 'SFI-HIST-20260821-CONVERGENCE',
    occurredAt: '2026-08-21T10:26:00Z',
    title: 'Convergencia sobre observación, evidencia y retorno',
    summary: 'Se removieron rutas heurísticas y estado sintético restante, exigiendo casos y evidencia reales, trazabilidad de ejecución y retorno persistido sin crear una arquitectura paralela.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/260',
    sourceLabel: 'PR #260',
  },
  {
    id: 'SFI-HIST-20260821-FRONTEND',
    occurredAt: '2026-08-21T23:34:16Z',
    title: 'Reemplazo total del frontend y gateway externo de agentes',
    summary: 'El frontend legado fue sustituido por escenas vivas, manteniendo el backend existente. Se incorporaron manifest, observe, propose, execute y Method Lab para clientes de IA gobernados.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_pr',
    sourceUrl: 'https://github.com/Aptymok/system-friction/pull/262',
    sourceLabel: 'PR #262',
  },
  {
    id: 'SFI-HIST-20260822-METHODLAB-FIX',
    occurredAt: '2026-08-22T07:53:54Z',
    title: 'Corrección de lectura persistente de Method Lab',
    summary: 'Se corrigió la ambigüedad de lectura de sfi_lab_analyses que producía el error WITHIN GROUP sobre la columna mode.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/44ec16a53e9b7034a30e0a78886d1b44c3031486',
    sourceLabel: 'commit 44ec16a5',
  },
  {
    id: 'SFI-HIST-20260822-AI-CONSOLE',
    occurredAt: '2026-08-22T08:10:23Z',
    title: 'Consola consolidada para agentes de IA',
    summary: 'La API externa incorporó una lectura consolidada de Method Lab, reportes, Cognitive Twin, propuestas, evidencia, runs y capacidades agénticas para clientes autorizados.',
    epistemicClass: 'OBSERVED',
    sourceType: 'github_commit',
    sourceUrl: 'https://github.com/Aptymok/system-friction/commit/79665191fb7b99bcc775c25b0e836497ff8203fc',
    sourceLabel: 'commit 79665191',
  },
  {
    id: 'SFI-HIST-20260822-LIVE',
    occurredAt: '2026-08-22T19:06:25Z',
    title: 'Estado técnico observable actual',
    summary: 'El repositorio público permanece activo sobre main y la superficie pública canónica se presenta como LIVE OBSERVATION SURFACE en systemfriction.org.',
    epistemicClass: 'OBSERVED',
    sourceType: 'live_site',
    sourceUrl: 'https://systemfriction.org',
    sourceLabel: 'systemfriction.org + GitHub repository metadata',
  },
];

export const SFI_HISTORY_BOUNDARY =
  'Esta cronología contiene únicamente hitos verificables por fuentes públicas del propio SFI/GitHub. No rellena periodos no documentados, no convierte una fecha de código en una afirmación sobre el origen conceptual del instituto y no presenta capacidad de runtime como validación empírica.';
