import type { AgenticRootState } from '@/lib/agents/sfiAgents';
import { buildRootTopologyModel } from './rootTopologyModel';
import { ROOT_FUNCTIONS_CATALOG } from './rootFunctionsCatalog';
import { buildRootExpansionModel } from './rootExpansionModel';
import type { RootViewId } from './rootViews';
import type { RootSceneModel, RootSceneNode } from './scene/rootSceneTypes';

export type Tone = 'ok' | 'watch' | 'bad' | 'muted';
export type DataSnapshot = { confidence: number; confidenceAvailable: boolean; predictions: unknown[]; graphNodes: unknown[]; evidence: unknown[]; amvItems: unknown[]; warnings: unknown[]; queue: unknown[]; agentCount: number; worldAgent: Record<string, unknown>; systemHealth: Record<string, unknown>; amv: Record<string, unknown>; worldObservation: Record<string, unknown> };
export type PanelItem = { id: string; label: string; body: string; status: string; source: string };

export function asRecord(value: unknown): Record<string, unknown> { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
export function asArray(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
export function text(value: unknown, fallback = 'not_available') { return typeof value === 'string' && value.trim() ? value.trim() : fallback; }
export function num(value: unknown, fallback = 0) { const parsed = Number(value ?? fallback); return Number.isFinite(parsed) ? parsed : fallback; }
export function bounded(value: unknown, fallback = 0) { return Math.max(0, Math.min(1, num(value, fallback))); }
export function pct(value: number) { return `${Math.round(Math.max(0, Math.min(1, value)) * 100)}%`; }
export function statusTone(value: unknown): Tone { const raw = text(value, '').toLowerCase(); if (/(fail|error|critical|degraded|collapsed|missing|deny|reject)/.test(raw)) return 'bad'; if (/(pending|queued|warn|review|watch|medium|study|hold|partial|gated)/.test(raw)) return 'watch'; if (/(ok|live|active|stable|operational|observed|available|build|approved)/.test(raw)) return 'ok'; return 'muted'; }
export function toneClass(tone: Tone) { return `tone-${tone}`; }

export function toDataSnapshot(initialState: AgenticRootState, worldVector: unknown): DataSnapshot {
  const registry = asRecord(initialState.predictionRegistry); const graph = asRecord(initialState.neuralGraph); const amv = asRecord(initialState.amv); const systemHealth = asRecord(initialState.systemHealth); const world = asRecord(worldVector); const today = asRecord(world.today); const observation = asRecord(today.observation); const confidenceAvailable = typeof observation.confidence === 'number';
  return { confidence: bounded(observation.confidence, 0), confidenceAvailable, predictions: asArray(registry.entries), graphNodes: asArray(graph.nodes), evidence: asArray(graph.evidence), amvItems: asArray(amv.items), warnings: asArray(systemHealth.warnings), queue: asArray(initialState.executionQueue), agentCount: num(systemHealth.llmProvidersAvailable, 0), worldAgent: asRecord(initialState.worldVectorAgent), systemHealth, amv, worldObservation: observation };
}

function panelItemFromUnknown(item: unknown, index: number, source: string): PanelItem { const record = asRecord(item); const label = text(record.action ?? record.label ?? record.hypothesis_id ?? record.id ?? record.theme ?? record.type ?? record.status, `ROOT-${index + 1}`); const body = text(record.reason ?? record.description ?? record.prediccion_explicita ?? record.prediction ?? record.summary ?? record.expected_outcome ?? record.source ?? record.status, 'No detail available from source.'); const status = text(record.status ?? record.recommendation ?? record.evidence_state ?? record.estado_observacion ?? record.current_signal_state, 'observed'); return { id: `${source}-${index}-${label}`, label, body, status, source }; }

export function buildInstituteScene(data: DataSnapshot): RootSceneModel {
  const topology = buildRootTopologyModel({ confidence: data.confidence, graphNodeCount: data.graphNodes.length, evidenceCount: data.evidence.length, predictionCount: data.predictions.length, amvCount: data.amvItems.length, queueCount: data.queue.length, warningCount: data.warnings.length, agentCount: data.agentCount });
  const domainNodes: RootSceneNode[] = topology.nodes.map((node) => ({ id: `domain-${node.id}`, label: node.id === 'ROOT' ? 'GOV' : node.label, x: node.x, y: node.y, value: node.value, status: data.warnings.length ? 'watch' : 'observed', kind: 'domain', source: node.source, meaning: node.meaning, dataClass: node.source.includes('derived') ? 'derived' : 'mixed' }));
  const core: RootSceneNode = { id: 'root-core', label: 'ROOT', x: 50, y: 50, value: data.confidenceAvailable ? pct(data.confidence) : 'gated', status: data.warnings.length ? 'watch' : data.confidenceAvailable ? 'stable' : 'gated', kind: 'core', source: 'worldVector.today.observation.confidence + buildAgenticRootState()', meaning: 'Central ROOT observatory point. Confidence is shown only when the World Vector observation provides it.', dataClass: data.confidenceAvailable ? 'mixed' : 'gated' };
  return { title: 'Institute State', subtitle: 'Orbital institutional observatory', nodes: [core, ...domainNodes], edges: [...topology.edges.map((edge) => ({ id: edge.id, from: `domain-${edge.from}`, to: `domain-${edge.to}`, weight: edge.weight, kind: edge.kind, source: edge.source, meaning: edge.meaning })), ...domainNodes.map((node) => ({ id: `core-${node.id}`, from: core.id, to: node.id, weight: data.confidenceAvailable ? Math.max(0.22, data.confidence) : 0.16, kind: data.confidenceAvailable ? 'radial' : 'gated', source: 'ROOT scene radial adapter over rootTopologyModel', meaning: `ROOT can inspect the ${node.label} domain without duplicating the source model.` }))], rings: topology.rings.map((ring) => ({ id: ring.id, radius: ring.radius + 8, weight: ring.weight, label: ring.id.toUpperCase(), source: ring.source, meaning: ring.meaning })), annotations: [{ id: 'root-observatory-label', label: 'ROOT OBSERVATORY', x: 50, y: 8.5, source: 'scene label', meaning: 'Scene identity label.', dataClass: 'derived' }, { id: 'r18-label', label: 'R18 / NO DUPLICATED GOVERNANCE', x: 50, y: 94, source: 'DT-AUTONOMY-02 rule label', meaning: 'The scene connects existing ROOT state without creating a parallel approval flow.', dataClass: 'derived' }], readouts: [{ id: 'confidence', label: 'confidence', value: data.confidenceAvailable ? pct(data.confidence) : 'gated', source: 'worldVector.today.observation.confidence', meaning: 'World Vector confidence when present.', dataClass: data.confidenceAvailable ? 'real' : 'gated' }, { id: 'graph', label: 'graph', value: data.graphNodes.length, source: 'initialState.neuralGraph.nodes.length', meaning: 'Graph node count.', dataClass: 'real' }, { id: 'evidence', label: 'evidence', value: data.evidence.length, source: 'initialState.neuralGraph.evidence.length', meaning: 'Evidence count.', dataClass: 'real' }, { id: 'predictions', label: 'predictions', value: data.predictions.length, source: 'initialState.predictionRegistry.entries.length', meaning: 'Prediction registry count.', dataClass: 'real' }, { id: 'amv', label: 'amv', value: data.amvItems.length, source: 'initialState.amv.items.length', meaning: 'AMV item count.', dataClass: 'real' }, { id: 'warnings', label: 'warnings', value: data.warnings.length, source: 'initialState.systemHealth.warnings.length', meaning: 'System warning count.', dataClass: 'real' }] };
}

export function buildContextItems(activeView: RootViewId, data: DataSnapshot): PanelItem[] {
  const expansion = buildRootExpansionModel({ confidence: data.confidence, amvCount: data.amvItems.length, predictionCount: data.predictions.length, evidenceCount: data.evidence.length });
  const agentItems = [{ label: 'World Vector Agent', description: text(data.worldAgent.current_signal_state), status: data.worldAgent.current_signal_state, source: 'initialState.worldVectorAgent' }, { label: 'Neural Graph Agent', description: `${data.graphNodes.length} nodes / ${data.evidence.length} evidence`, status: data.systemHealth.graphStatus, source: 'initialState.neuralGraph + initialState.systemHealth' }, { label: 'AMV Agent', description: `${data.amvItems.length} memory items`, status: data.amv.status, source: 'initialState.amv' }, { label: 'Prediction Registry', description: `${data.predictions.length} entries`, status: data.systemHealth.predictionStatus, source: 'initialState.predictionRegistry' }];
  if (activeView === 'prediction-registry') return data.predictions.map((item, index) => panelItemFromUnknown(item, index, 'initialState.predictionRegistry.entries'));
  if (activeView === 'agentic-operations') return agentItems.map((item, index) => panelItemFromUnknown(item, index, item.source));
  if (activeView === 'founder-governance') return (data.queue.length ? data.queue : data.predictions).map((item, index) => panelItemFromUnknown(item, index, data.queue.length ? 'initialState.executionQueue' : 'initialState.predictionRegistry.entries'));
  if (activeView === 'institute-functions') return ROOT_FUNCTIONS_CATALOG.map((item, index) => panelItemFromUnknown(item, index, 'rootFunctionsCatalog'));
  if (activeView === 'expansion-investigation') return expansion.themes.map((item, index) => panelItemFromUnknown(item, index, 'rootExpansionModel.themes'));
  return data.evidence.map((item, index) => panelItemFromUnknown(item, index, 'initialState.neuralGraph.evidence'));
}

export function readingForView(activeView: RootViewId, data: DataSnapshot) { if (activeView === 'institute-functions') return 'ROOT tools are grouped by declared function family. Available, partial and gated states come from the catalog.'; if (activeView === 'expansion-investigation') return 'Expansion routes are DERIVED from confidence, AMV, prediction and evidence counts. They are investigation signals, not publication proof.'; if (activeView === 'prediction-registry') return data.predictions.length ? 'Prediction routes are generated from registry entries and their available probability fields. Falsification risk, calibration and quality are DERIVED from existing registry data.' : 'No prediction entries arrived in initialState.predictionRegistry.entries, so no hypothesis route is drawn.'; if (activeView === 'founder-governance') return 'Founder governance exposes approval pressure without creating a parallel queue. ROOT inspects, routes, holds, approves or denies through existing action state.'; return text(data.worldAgent.root_interpretation ?? data.worldObservation.interpretation, 'ROOT is observing the live state through buildAgenticRootState() and buildWorldVectorOperationalState().'); }
