import 'server-only';

import { SFI_SYSTEM_AI_RELATION_TYPES, validateSystemAiRelationDraft, type SfiSystemAiEntityRef, type SfiSystemAiRelationDraft, type SfiSystemAiRelationEpistemicRole, type SfiSystemAiRelationType } from '@/core/case-platform';
import type { SfiCanonicalRef } from '@/core/contracts/sfi';
import { createServiceSupabaseClient } from '@/runtime/supabase/server';
import { assertCaseServiceProfileAllowed, assertCaseReferenceIntegrity, assertTenantSystemAiEntityRefs, readCaseAuthorityRole } from './integrity';

const SYSTEM_AI_PROFILES=['SYSTEM_OBSERVATORY','AI_IMPLEMENTATION_DIAGNOSTIC','AI_ADOPTION_INTEGRATION','AI_GOVERNANCE_ASSURANCE','CUSTOM_RESEARCH'] as const;
type Row=Record<string,unknown>;
function text(v:unknown){return typeof v==='string'?v.trim():'';} function obj(v:unknown):Record<string,unknown>{return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function refs(v:unknown):SfiCanonicalRef[]{return Array.isArray(v)?v.map(item=>{const r=obj(item);return{id:text(r.id),version:text(r.version)||null,hash:text(r.hash)||null};}).filter(r=>r.id):[];}
function entityRef(v:unknown):SfiSystemAiEntityRef{const r=obj(v);return{id:text(r.id),version:text(r.version)||null,hash:text(r.hash)||null,entityType:text(r.entityType) as SfiSystemAiEntityRef['entityType']};}
function fromRow(row:Row){return{id:text(row.id),relationKey:text(row.relation_key),caseId:text(row.case_id),tenantId:text(row.tenant_id),relationType:text(row.relation_type) as SfiSystemAiRelationType,epistemicRole:text(row.epistemic_role) as SfiSystemAiRelationEpistemicRole,from:entityRef(row.from_ref),to:entityRef(row.to_ref),sourceRefs:refs(row.source_refs),recordRefs:refs(row.record_refs),evidenceRefs:refs(row.evidence_refs),payload:obj(row.payload),observedAt:text(row.observed_at)||null,createdAt:text(row.created_at)};}

export async function recordOperationalSystemAiRelation(input:{caseId:string;userId:string;relation:SfiSystemAiRelationDraft}){
  await assertCaseServiceProfileAllowed(input.caseId,input.userId,[...SYSTEM_AI_PROFILES]); const authority=await readCaseAuthorityRole(input.caseId,input.userId); if(!['OWNER','ADMIN','OPERATOR'].includes(authority.role)) throw new Error('SFI_TENANT_WRITE_FORBIDDEN'); if(['CLOSED','REJECTED'].includes(authority.status)) throw new Error(`SFI_SYSTEM_AI_RELATION_WRITE_FORBIDDEN:${authority.status}`);
  const violations=validateSystemAiRelationDraft(input.relation); if(violations.length) throw new Error(`SFI_SYSTEM_AI_RELATION_INVALID:${violations.join(',')}`);
  await assertCaseReferenceIntegrity({caseId:input.caseId,userId:input.userId,sourceRefs:input.relation.sourceRefs,recordRefs:input.relation.recordRefs,evidenceRefs:input.relation.evidenceRefs});
  await assertTenantSystemAiEntityRefs({caseId:input.caseId,userId:input.userId,entityRefs:[input.relation.from,input.relation.to]});
  const service=createServiceSupabaseClient(); const existing=await service.from('sfi_case_relations').select('*').eq('case_id',input.caseId).eq('relation_key',input.relation.relationKey).maybeSingle(); if(existing.error) throw new Error(`SFI_SYSTEM_AI_RELATION_IDENTITY_READ_FAILED:${existing.error.message}`); if(existing.data){const row=fromRow(existing.data as Row); if(row.relationType===input.relation.relationType&&row.from.id===input.relation.from.id&&row.to.id===input.relation.to.id&&row.epistemicRole===input.relation.epistemicRole)return row; throw new Error('SFI_SYSTEM_AI_RELATION_KEY_CONFLICT');}
  const inserted=await service.from('sfi_case_relations').insert({relation_key:input.relation.relationKey,case_id:input.caseId,owner_id:authority.ownerId,tenant_id:authority.tenantId,relation_type:input.relation.relationType,epistemic_role:input.relation.epistemicRole,from_ref:input.relation.from,to_ref:input.relation.to,source_refs:input.relation.sourceRefs??[],record_refs:input.relation.recordRefs??[],evidence_refs:input.relation.evidenceRefs??[],payload:input.relation.payload??{},observed_at:input.relation.observedAt??null}).select('*').single(); if(inserted.error||!inserted.data) throw new Error(`SFI_SYSTEM_AI_RELATION_WRITE_FAILED:${inserted.error?.message??'unknown'}`); return fromRow(inserted.data as Row);
}

export async function listOperationalSystemAiRelations(caseId:string,userId:string){await assertCaseServiceProfileAllowed(caseId,userId,[...SYSTEM_AI_PROFILES]); const service=createServiceSupabaseClient(); const result=await service.from('sfi_case_relations').select('*').eq('case_id',caseId).in('relation_type',[...SFI_SYSTEM_AI_RELATION_TYPES]).order('created_at',{ascending:true}); if(result.error) throw new Error(`SFI_SYSTEM_AI_RELATION_LIST_FAILED:${result.error.message}`); return ((result.data??[]) as Row[]).map(fromRow);}

export async function listTenantSystemAiRelations(tenantId:string,userId:string){const service=createServiceSupabaseClient(); const membership=await service.from('sfi_tenant_members').select('status').eq('tenant_id',tenantId).eq('user_id',userId).maybeSingle(); if(membership.error) throw new Error(`SFI_SYSTEM_AI_MEMBERSHIP_READ_FAILED:${membership.error.message}`); if(!membership.data||membership.data.status!=='ACTIVE') throw new Error('SFI_TENANT_FORBIDDEN'); const result=await service.from('sfi_case_relations').select('*').eq('tenant_id',tenantId).in('relation_type',[...SFI_SYSTEM_AI_RELATION_TYPES]).order('created_at',{ascending:true}); if(result.error) throw new Error(`SFI_SYSTEM_AI_TENANT_RELATION_LIST_FAILED:${result.error.message}`); return ((result.data??[]) as Row[]).map(fromRow);}
