import type { ScoreFrictionCaseStudy } from './types';

export const SCORE_FRICTION_CASES: ScoreFrictionCaseStudy[] = [
  {
    case_id: 'CW-001',
    name: 'Saturacion Reggaeton / Vacio de Construccion',
    phenomenon: 'Saturacion de formulas urbanas dominantes.',
    friction: 'Alta repeticion con baja construccion narrativa.',
    hypothesis: 'Un prototipo con agencia narrativa clara puede producir senal diferencial.',
    sources: ['youtube', 'spotify', 'lyrics'],
    variables: ['semantic_density', 'repetition_load', 'identity_resonance_score'],
    expectedPrototype: 'Cancion urbana con eje de agencia y hook temprano.',
    verificationMetric: 'Comentarios de identidad + saves/repeticion.',
    status: 'active',
  },
  {
    case_id: 'CW-002',
    name: 'Nostalgia Tecnologica / Futuro Personal',
    phenomenon: 'Recuerdo tecnologico como refugio cultural.',
    friction: 'Nostalgia sin direccion futura.',
    hypothesis: 'La nostalgia puede convertirse en futuro personal verificable.',
    sources: ['youtube', 'google_trends', 'manual_upload'],
    variables: ['semantic_echo_score', 'future_axis', 'PAC'],
    expectedPrototype: 'Textura retro con letra orientada a accion personal.',
    verificationMetric: 'Eco semantico en comentarios y retencion proxy.',
    status: 'active',
  },
  {
    case_id: 'CW-003',
    name: 'Fatiga Cognitiva / Musica de Baja Carga',
    phenomenon: 'Busqueda de baja carga mental.',
    friction: 'Atencion agotada y baja tolerancia a densidad.',
    hypothesis: 'Una estructura simple con textura precisa puede sostener escucha repetida.',
    sources: ['spotify', 'youtube', 'audio_local'],
    variables: ['rms_energy', 'semantic_density', 'dynamic_range'],
    expectedPrototype: 'Baja densidad verbal, pulso estable y timbre memorable.',
    verificationMetric: 'Repeticion, baja friccion en feedback manual.',
    status: 'active',
  },
  {
    case_id: 'CW-004',
    name: 'Microcomunidad / Coro de Pertenencia',
    phenomenon: 'Coro como senal de pertenencia local.',
    friction: 'Comunidad dispersa sin gesto comun.',
    hypothesis: 'Un hook coral puede condensar pertenencia sin marketing pesado.',
    sources: ['tiktok_research_alternative', 'youtube', 'manual_upload'],
    variables: ['identity_resonance_score', 'gesture_adoption_score', 'ritualization_index'],
    expectedPrototype: 'Coro breve con frase territorial reutilizable.',
    verificationMetric: 'Reuso de frase, comentarios de pertenencia.',
    status: 'active',
  },
  {
    case_id: 'CW-005',
    name: 'Ansiedad de Futuro / Epica Operativa',
    phenomenon: 'Futuro percibido como amenaza.',
    friction: 'Energia alta sin direccion operacional.',
    hypothesis: 'Una epica sobria puede transformar ansiedad en accion verificable.',
    sources: ['lyrics', 'youtube', 'manual_upload'],
    variables: ['future_axis', 'agency_axis', 'FS_C'],
    expectedPrototype: 'Produccion tensa con salida lirica accionable.',
    verificationMetric: 'Lecturas de motivacion sin grandilocuencia.',
    status: 'active',
  },
  {
    case_id: 'CW-006',
    name: 'Lenguaje Meme / Sedimentacion Semantica',
    phenomenon: 'Memes como memoria cultural comprimida.',
    friction: 'Alta velocidad con baja permanencia.',
    hypothesis: 'Un motivo repetible puede sedimentar significado sin explicar demasiado.',
    sources: ['tiktok_research_alternative', 'youtube', 'manual_upload'],
    variables: ['semantic_compression_score', 'caption_reuse_score', 'SCR'],
    expectedPrototype: 'Motivo corto, flexible y semanticamente comprimido.',
    verificationMetric: 'Reuso de caption y variaciones del motivo.',
    status: 'active',
  },
  {
    case_id: 'CW-007',
    name: 'Territorio Local / Identidad Expandible',
    phenomenon: 'Identidad territorial que puede escalar.',
    friction: 'Lo local queda encerrado o se diluye.',
    hypothesis: 'Una marca sonora local puede expandirse si conserva rasgo verificable.',
    sources: ['soundcloud_public_v2', 'youtube', 'manual_upload'],
    variables: ['territory_axis', 'identity_resonance_score', 'IHG_C'],
    expectedPrototype: 'Rasgo local audible con estructura exportable.',
    verificationMetric: 'Reconocimiento local + comprension externa.',
    status: 'active',
  },
  {
    case_id: 'CW-008',
    name: 'Romance Post-Digital / Vinculo Sin Performance',
    phenomenon: 'Vinculo afectivo mediado por performance digital.',
    friction: 'Exceso de pose y baja vulnerabilidad util.',
    hypothesis: 'Una voz menos performativa puede activar resonancia afectiva.',
    sources: ['lyrics', 'youtube', 'tiktok_research_alternative'],
    variables: ['desire_axis', 'cooperation_axis', 'semantic_density'],
    expectedPrototype: 'Letra afectiva directa con produccion contenida.',
    verificationMetric: 'Comentarios de identificacion no ironica.',
    status: 'active',
  },
  {
    case_id: 'CW-009',
    name: 'Escena SoundCloud / Emergencia No Institucionalizada',
    phenomenon: 'Escena periferica creativa fuera de canales formales.',
    friction: 'Senal emergente sin lectura institucional.',
    hypothesis: 'SoundCloud puede revelar protoatractores antes del mainstream.',
    sources: ['soundcloud_public_v2', 'manual_upload'],
    variables: ['scene_emergence_score', 'drop_reaction_points', 'underground_signal_strength'],
    expectedPrototype: 'Urbano lento con textura experimental y drop reutilizable.',
    verificationMetric: 'Drop reaction density y comentarios timestamped.',
    status: 'active',
  },
  {
    case_id: 'CW-010',
    name: 'TikTok Gesture Loop / Ritualizacion de Audio Corto',
    phenomenon: 'Audio corto como gesto social repetido.',
    friction: 'Fragmentabilidad alta con baja continuidad.',
    hypothesis: 'Un drop reutilizable puede generar ritualizacion si comprime sentido.',
    sources: ['tiktok_research_alternative', 'manual_upload'],
    variables: ['fragmentability_score', 'gesture_adoption_score', 'VFE'],
    expectedPrototype: 'Hook/drop de alta compresion gestual.',
    verificationMetric: 'Reuse count, caption reuse y gesture replication.',
    status: 'active',
  },
];
