import type { CulturalWaveCase } from './cultural-vector-contract';

export const CULTURAL_WAVE_CASES: CulturalWaveCase[] = [
  {
    case_id: 'CW-001',
    name: 'Saturación Reggaetón / Vacío de Construcción',
    phenomenon: 'Alta circulación urbana con fatiga semántica.',
    friction: 'Repetición formal sin construcción narrativa suficiente.',
    hypothesis: 'Un prototipo con agencia narrativa clara puede producir señal diferencial.',
    seedVector: { NTI_C: 0.63, IHG_C: 0.46, ICE_C: 0.64, CRM_C: 0.61, FS_C: 0.57, LCP: 0.76, PAC: 0.69, VFE: 0.72, SCR: 0.66 },
    sources: { youtube: 0.62, tiktok: 0.78, soundcloud: 0.36, spotify: 0.71, lyrics: 0.70 },
    prototypeHint: { bpm: '94-102', rhythm: 'urbano sobrio con hook temprano', instruments: ['sub bass', 'percusión seca', 'lead mínimo'], lyricsAxis: ['agencia', 'construcción', 'futuro'], platformTargets: ['soundcloud', 'tiktok', 'youtube'] },
  },
  {
    case_id: 'CW-002',
    name: 'Nostalgia Tecnológica / Futuro Personal',
    phenomenon: 'Nostalgia digital como refugio cultural.',
    friction: 'El pasado tecnológico aparece sin dirección operativa.',
    hypothesis: 'La nostalgia puede convertirse en futuro personal verificable.',
    seedVector: { NTI_C: 0.66, IHG_C: 0.52, ICE_C: 0.71, CRM_C: 0.66, FS_C: 0.42, LCP: 0.81, PAC: 0.73, VFE: 0.59, SCR: 0.55 },
    sources: { youtube: 0.48, tiktok: 0.62, soundcloud: 0.68, spotify: 0.44, lyrics: 0.57 },
    prototypeHint: { bpm: '82-96', rhythm: 'retro digital lento', instruments: ['synth granular', 'pad oxidado', 'voz cercana'], lyricsAxis: ['memoria', 'futuro', 'decisión'], platformTargets: ['youtube', 'soundcloud'] },
  },
  {
    case_id: 'CW-003',
    name: 'Fatiga Cognitiva / Música de Baja Carga',
    phenomenon: 'Búsqueda de escucha de baja carga mental.',
    friction: 'Atención agotada y baja tolerancia a densidad.',
    hypothesis: 'Una estructura simple con textura precisa puede sostener escucha repetida.',
    seedVector: { NTI_C: 0.49, IHG_C: 0.58, ICE_C: 0.69, CRM_C: 0.59, FS_C: 0.31, LCP: 0.68, PAC: 0.65, VFE: 0.41, SCR: 0.38 },
    sources: { youtube: 0.55, tiktok: 0.39, soundcloud: 0.46, spotify: 0.53, lyrics: 0.42 },
    prototypeHint: { bpm: '72-88', rhythm: 'pulso estable y aireado', instruments: ['bass cálido', 'percusión suave', 'textura ambiental'], lyricsAxis: ['claridad', 'calma', 'mínima acción'], platformTargets: ['spotify', 'youtube'] },
  },
  {
    case_id: 'CW-004',
    name: 'Microcomunidad / Coro de Pertenencia',
    phenomenon: 'Coro como señal de pertenencia local.',
    friction: 'Comunidad dispersa sin gesto común.',
    hypothesis: 'Un hook coral puede condensar pertenencia sin marketing pesado.',
    seedVector: { NTI_C: 0.71, IHG_C: 0.61, ICE_C: 0.75, CRM_C: 0.74, FS_C: 0.48, LCP: 0.72, PAC: 0.76, VFE: 0.68, SCR: 0.61 },
    sources: { youtube: 0.52, tiktok: 0.74, soundcloud: 0.51, spotify: 0.39, lyrics: 0.63 },
    prototypeHint: { bpm: '90-100', rhythm: 'coro grupal con llamada y respuesta', instruments: ['palmas secas', 'sub discreto', 'voces dobles'], lyricsAxis: ['nosotros', 'territorio', 'pertenencia'], platformTargets: ['tiktok', 'youtube'] },
  },
  {
    case_id: 'CW-005',
    name: 'Ansiedad de Futuro / Épica Operativa',
    phenomenon: 'Futuro percibido como amenaza.',
    friction: 'Energía alta sin dirección operacional.',
    hypothesis: 'Una épica sobria puede transformar ansiedad en acción verificable.',
    seedVector: { NTI_C: 0.69, IHG_C: 0.48, ICE_C: 0.67, CRM_C: 0.68, FS_C: 0.64, LCP: 0.83, PAC: 0.70, VFE: 0.63, SCR: 0.58 },
    sources: { youtube: 0.61, tiktok: 0.58, soundcloud: 0.44, spotify: 0.49, lyrics: 0.72 },
    prototypeHint: { bpm: '96-108', rhythm: 'épica contenida con tensión ascendente', instruments: ['drone', 'percusión militar seca', 'voz procesada'], lyricsAxis: ['futuro', 'acción', 'método'], platformTargets: ['youtube', 'soundcloud'] },
  },
  {
    case_id: 'CW-006',
    name: 'Lenguaje Meme / Sedimentación Semántica',
    phenomenon: 'Memes como memoria cultural comprimida.',
    friction: 'Alta velocidad con baja permanencia.',
    hypothesis: 'Un motivo repetible puede sedimentar significado sin explicar demasiado.',
    seedVector: { NTI_C: 0.55, IHG_C: 0.38, ICE_C: 0.54, CRM_C: 0.77, FS_C: 0.69, LCP: 0.64, PAC: 0.57, VFE: 0.86, SCR: 0.82 },
    sources: { youtube: 0.45, tiktok: 0.92, soundcloud: 0.33, spotify: 0.28, lyrics: 0.64 },
    prototypeHint: { bpm: '100-116', rhythm: 'loop corto y cortado', instruments: ['sample vocal', 'kick seco', 'silencio marcado'], lyricsAxis: ['frase', 'doble sentido', 'compresión'], platformTargets: ['tiktok'] },
  },
  {
    case_id: 'CW-007',
    name: 'Territorio Local / Identidad Expandible',
    phenomenon: 'Identidad territorial que puede escalar.',
    friction: 'Lo local queda encerrado o se diluye.',
    hypothesis: 'Una marca sonora local puede expandirse si conserva rasgo verificable.',
    seedVector: { NTI_C: 0.64, IHG_C: 0.59, ICE_C: 0.68, CRM_C: 0.65, FS_C: 0.44, LCP: 0.71, PAC: 0.67, VFE: 0.56, SCR: 0.49 },
    sources: { youtube: 0.54, tiktok: 0.59, soundcloud: 0.57, spotify: 0.41, lyrics: 0.69 },
    prototypeHint: { bpm: '88-98', rhythm: 'local expandible sin folclorismo plano', instruments: ['percusión regional intervenida', 'sub', 'voz directa'], lyricsAxis: ['barrio', 'ciudad', 'expansión'], platformTargets: ['soundcloud', 'youtube'] },
  },
  {
    case_id: 'CW-008',
    name: 'Romance Post-Digital / Vínculo Sin Performance',
    phenomenon: 'Vínculo afectivo mediado por performance digital.',
    friction: 'Exceso de pose y baja vulnerabilidad útil.',
    hypothesis: 'Una voz menos performativa puede activar resonancia afectiva.',
    seedVector: { NTI_C: 0.58, IHG_C: 0.62, ICE_C: 0.72, CRM_C: 0.60, FS_C: 0.38, LCP: 0.62, PAC: 0.66, VFE: 0.52, SCR: 0.44 },
    sources: { youtube: 0.49, tiktok: 0.57, soundcloud: 0.43, spotify: 0.58, lyrics: 0.74 },
    prototypeHint: { bpm: '76-92', rhythm: 'romance contenido y voz cercana', instruments: ['guitarra procesada', 'pad', 'percusión mínima'], lyricsAxis: ['vínculo', 'cuidado', 'no performance'], platformTargets: ['spotify', 'youtube'] },
  },
  {
    case_id: 'CW-009',
    name: 'SoundCloud / Emergencia No Institucionalizada',
    phenomenon: 'Escena periférica creativa fuera de canales formales.',
    friction: 'Señal emergente sin lectura institucional.',
    hypothesis: 'SoundCloud puede revelar protoatractores antes del mainstream.',
    seedVector: { NTI_C: 0.57, IHG_C: 0.41, ICE_C: 0.61, CRM_C: 0.62, FS_C: 0.52, LCP: 0.79, PAC: 0.58, VFE: 0.47, SCR: 0.51 },
    sources: { youtube: 0.31, tiktok: 0.44, soundcloud: 0.88, spotify: 0.22, lyrics: 0.48 },
    prototypeHint: { bpm: '92-98', rhythm: 'urbano lento + textura experimental', instruments: ['sub bass', 'percusión seca', 'synth granular', 'voz procesada'], lyricsAxis: ['identidad local', 'futuro', 'agencia'], platformTargets: ['soundcloud', 'tiktok', 'youtube'] },
  },
  {
    case_id: 'CW-010',
    name: 'TikTok Gesture Loop / Ritualización de Audio Corto',
    phenomenon: 'Audio corto como gesto social repetido.',
    friction: 'Fragmentabilidad alta con baja continuidad.',
    hypothesis: 'Un drop reutilizable puede generar ritualización si comprime sentido.',
    seedVector: { NTI_C: 0.62, IHG_C: 0.37, ICE_C: 0.60, CRM_C: 0.81, FS_C: 0.71, LCP: 0.74, PAC: 0.63, VFE: 0.91, SCR: 0.79 },
    sources: { youtube: 0.42, tiktok: 0.95, soundcloud: 0.29, spotify: 0.24, lyrics: 0.53 },
    prototypeHint: { bpm: '104-118', rhythm: 'drop corto con gesto replicable', instruments: ['silencio', 'hit vocal', 'percusión seca'], lyricsAxis: ['gesto', 'frase', 'repetición'], platformTargets: ['tiktok', 'soundcloud'] },
  },
];

export function findCulturalWaveCase(caseId: string) {
  return CULTURAL_WAVE_CASES.find((item) => item.case_id === caseId) ?? null;
}
