import type { FoundationCopyKey } from './foundation-copy';

export type FoundationNode = {
  id: string;
  label: string;
  category: 'foundation' | 'method' | 'model' | 'variable' | 'instrument' | 'evidence' | 'phenomenon';
  layer: number;
  x: number;
  y: number;
  z: number;
  radius: number;
  connections: string[];
  superLabel: string;
  title: string;
  contentKey: FoundationCopyKey;
  evidenceCount: number;
  privateEvidenceCount: number;
  density: number;
  degradation: number;
  weight: number;
};

const variableContent = 'variable' as const;

export const FOUNDATION_NODES: FoundationNode[] = [
  {
    id: 'SFI',
    label: 'System Friction Institute',
    category: 'foundation',
    layer: 1,
    x: 0,
    y: 0,
    z: 0,
    radius: 34,
    connections: ['CARTA_FUNDACIONAL', 'METODOLOGIA', 'SFI_OBS_N0', 'SCOREFRICTION', 'MOPH'],
    superLabel: 'Institucion / Campo raiz',
    title: 'System Friction Institute',
    contentKey: 'carta',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.85,
    degradation: 0.05,
    weight: 0.90,
  },
  {
    id: 'CARTA_FUNDACIONAL',
    label: 'Carta Fundacional',
    category: 'foundation',
    layer: 1,
    x: -280,
    y: -70,
    z: 0,
    radius: 26,
    connections: ['MISION', 'VISION', 'VALORES'],
    superLabel: 'Carta / Origen',
    title: 'Carta Fundacional',
    contentKey: 'carta',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.82,
    degradation: 0.04,
    weight: 0.84,
  },
  {
    id: 'MISION',
    label: 'Mision',
    category: 'foundation',
    layer: 1,
    x: -450,
    y: -210,
    z: 1,
    radius: 20,
    connections: ['CARTA_FUNDACIONAL', 'METODOLOGIA'],
    superLabel: 'Direccion / Observacion',
    title: 'Mision',
    contentKey: 'mission',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.72,
    degradation: 0.08,
    weight: 0.72,
  },
  {
    id: 'VISION',
    label: 'Vision',
    category: 'foundation',
    layer: 1,
    x: -470,
    y: 40,
    z: 1,
    radius: 20,
    connections: ['CARTA_FUNDACIONAL', 'PHENOMENON_ENGINE'],
    superLabel: 'Horizonte / Integracion',
    title: 'Vision',
    contentKey: 'vision',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.70,
    degradation: 0.10,
    weight: 0.70,
  },
  {
    id: 'VALORES',
    label: 'Valores',
    category: 'foundation',
    layer: 1,
    x: -320,
    y: 210,
    z: 1,
    radius: 20,
    connections: ['CARTA_FUNDACIONAL', 'EVIDENCE_LEDGER'],
    superLabel: 'Reglas / Criterio',
    title: 'Valores operativos',
    contentKey: 'values',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.68,
    degradation: 0.11,
    weight: 0.68,
  },
  {
    id: 'METODOLOGIA',
    label: 'Metodologia',
    category: 'method',
    layer: 1,
    x: 360,
    y: -160,
    z: 0,
    radius: 28,
    connections: ['MIHM', 'WorldSpect', 'FIELD_EQUATION', 'ATTRACTOR_MAPPING'],
    superLabel: 'Metodo / Nucleo operativo',
    title: 'Metodologia SFI',
    contentKey: 'methodology',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.80,
    degradation: 0.08,
    weight: 0.82,
  },
  {
    id: 'MIHM',
    label: 'MIHM',
    category: 'model',
    layer: 2,
    x: 640,
    y: -220,
    z: 1,
    radius: 24,
    connections: ['IHG', 'NTI', 'LDI', 'PHI', 'FS'],
    superLabel: 'Modelo / Evaluador interno',
    title: 'Multi-Dimensional Institutional Homeostasis Model',
    contentKey: 'mihm',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.76,
    degradation: 0.10,
    weight: 0.80,
  },
  {
    id: 'WorldSpect',
    label: 'WorldSpect',
    category: 'model',
    layer: 2,
    x: 650,
    y: 80,
    z: 1,
    radius: 24,
    connections: ['CULTURAL', 'ECONOMY', 'GEO_DIGITAL', 'GEOPOLITICAL', 'BIO', 'CLIMATE', 'INSTITUTIONAL', 'MEMETIC', 'TECH', 'AFFECTIVE'],
    superLabel: 'Modelo / Entorno externo',
    title: 'WorldSpect',
    contentKey: 'worldspect',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.70,
    degradation: 0.20,
    weight: 0.72,
  },
  {
    id: 'FIELD_EQUATION',
    label: 'Field Equation',
    category: 'method',
    layer: 2,
    x: 390,
    y: 125,
    z: 1,
    radius: 22,
    connections: ['PHI', 'FS', 'REALITY_DEBT'],
    superLabel: 'Ecuacion / Compresion',
    title: 'Field Equation',
    contentKey: 'fieldEquation',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.74,
    degradation: 0.12,
    weight: 0.75,
  },
  {
    id: 'ATTRACTOR_MAPPING',
    label: 'Attractor Mapping',
    category: 'model',
    layer: 2,
    x: 250,
    y: -390,
    z: 2,
    radius: 22,
    connections: ['REALITY_DEBT', 'PHENOMENON_ENGINE'],
    superLabel: 'Modelo / Trayectoria',
    title: 'Attractor Mapping',
    contentKey: 'attractorMapping',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.67,
    degradation: 0.18,
    weight: 0.70,
  },
  {
    id: 'REALITY_DEBT',
    label: 'Reality Debt',
    category: 'variable',
    layer: 3,
    x: 50,
    y: -470,
    z: 2,
    radius: 18,
    connections: ['GOVERNANCE_REALITY_LAYER', 'PHENOMENON_ENGINE'],
    superLabel: 'Variable / Deuda',
    title: 'Reality Debt',
    contentKey: 'realityDebt',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.63,
    degradation: 0.22,
    weight: 0.62,
  },
  {
    id: 'SFI_OBS_N0',
    label: 'SFI-OBS-N0',
    category: 'instrument',
    layer: 1,
    x: -360,
    y: -180,
    z: 0,
    radius: 28,
    connections: ['AMV', 'MOPH', 'EVIDENCE_LEDGER', 'FIELD_EQUATION'],
    superLabel: 'Observatorio / Nodo raiz',
    title: 'SFI-OBS-N0',
    contentKey: 'sfiobsn0',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.70,
    degradation: 0.12,
    weight: 0.74,
  },
  {
    id: 'SCOREFRICTION',
    label: 'ScoreFriction',
    category: 'instrument',
    layer: 1,
    x: 80,
    y: 320,
    z: 0,
    radius: 30,
    connections: ['WorldSpect', 'MIHM', 'PHENOMENON_ENGINE', 'ATTRACTOR_MAPPING'],
    superLabel: 'Observatorio / Campo cultural',
    title: 'ScoreFriction',
    contentKey: 'scorefriction',
    evidenceCount: 6,
    privateEvidenceCount: 2,
    density: 0.78,
    degradation: 0.18,
    weight: 0.76,
  },
  {
    id: 'CLUSTER_ATLAS',
    label: 'Cluster Atlas',
    category: 'instrument',
    layer: 2,
    x: -120,
    y: 430,
    z: 2,
    radius: 20,
    connections: ['SFI', 'SIGNAL_VANE'],
    superLabel: 'Instrumento / Agrupacion',
    title: 'Cluster Atlas',
    contentKey: 'clusterAtlas',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.58,
    degradation: 0.28,
    weight: 0.58,
  },
  {
    id: 'SIGNAL_VANE',
    label: 'Signal Vane',
    category: 'instrument',
    layer: 2,
    x: 180,
    y: 500,
    z: 2,
    radius: 20,
    connections: ['WorldSpect', 'CLUSTER_ATLAS'],
    superLabel: 'Instrumento / Orientacion',
    title: 'Signal Vane',
    contentKey: 'signalVane',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.56,
    degradation: 0.30,
    weight: 0.56,
  },
  {
    id: 'COGNITIVE_TWIN_ENGINE',
    label: 'Cognitive Twin Engine',
    category: 'instrument',
    layer: 2,
    x: -610,
    y: 170,
    z: 2,
    radius: 22,
    connections: ['MOPH', 'EVIDENCE_LEDGER', 'AMV'],
    superLabel: 'Instrumento / Memoria',
    title: 'Cognitive Twin Engine',
    contentKey: 'cognitiveTwinEngine',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.62,
    degradation: 0.24,
    weight: 0.64,
  },
  {
    id: 'GOVERNANCE_REALITY_LAYER',
    label: 'Governance Reality Layer',
    category: 'instrument',
    layer: 2,
    x: -620,
    y: -330,
    z: 2,
    radius: 22,
    connections: ['REALITY_DEBT', 'AMV', 'EVIDENCE_LEDGER'],
    superLabel: 'Instrumento / Gobernanza',
    title: 'Governance Reality Layer',
    contentKey: 'governanceRealityLayer',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.60,
    degradation: 0.26,
    weight: 0.62,
  },
  {
    id: 'MOPH',
    label: 'MOP-H',
    category: 'instrument',
    layer: 1,
    x: -120,
    y: -335,
    z: 1,
    radius: 24,
    connections: ['SFI_OBS_N0', 'COGNITIVE_TWIN_ENGINE', 'EVIDENCE_LEDGER'],
    superLabel: 'Instrumento / Fenomenologia',
    title: 'MOP-H',
    contentKey: 'moph',
    evidenceCount: 0,
    privateEvidenceCount: 0,
    density: 0.66,
    degradation: 0.20,
    weight: 0.68,
  },
  {
    id: 'AMV',
    label: 'AMV',
    category: 'instrument',
    layer: 2,
    x: -170,
    y: -520,
    z: 2,
    radius: 22,
    connections: ['SFI_OBS_N0', 'EVIDENCE_LEDGER', 'PHENOMENON_ENGINE'],
    superLabel: 'Agente / Propuesta',
    title: 'AMV',
    contentKey: 'amv',
    evidenceCount: 3,
    privateEvidenceCount: 0,
    density: 0.64,
    degradation: 0.18,
    weight: 0.66,
  },
  {
    id: 'EVIDENCE_LEDGER',
    label: 'Evidence Ledger',
    category: 'evidence',
    layer: 4,
    x: -60,
    y: 170,
    z: 1,
    radius: 24,
    connections: ['SFI_OBS_N0', 'AMV', 'PHENOMENON_ENGINE'],
    superLabel: 'Ledger / Evidencia agregada',
    title: 'Evidence Ledger',
    contentKey: 'evidenceLedger',
    evidenceCount: 9,
    privateEvidenceCount: 4,
    density: 0.73,
    degradation: 0.14,
    weight: 0.73,
  },
  {
    id: 'PHENOMENON_ENGINE',
    label: 'Phenomenon Engine',
    category: 'phenomenon',
    layer: 5,
    x: 360,
    y: 390,
    z: 2,
    radius: 25,
    connections: ['SCOREFRICTION', 'EVIDENCE_LEDGER', 'ATTRACTOR_MAPPING'],
    superLabel: 'Fenomeno / Persistencia',
    title: 'Phenomenon Engine',
    contentKey: 'phenomenonEngine',
    evidenceCount: 2,
    privateEvidenceCount: 0,
    density: 0.62,
    degradation: 0.31,
    weight: 0.64,
  },
  ...['IHG', 'NTI', 'LDI', 'PHI', 'FS'].map((id, index) => ({
    id,
    label: id,
    category: 'variable' as const,
    layer: 3,
    x: 870,
    y: -360 + index * 72,
    z: 3,
    radius: 14,
    connections: ['MIHM'],
    superLabel: 'Variable / MIHM',
    title: id,
    contentKey: variableContent,
    evidenceCount: index === 3 ? 3 : 0,
    privateEvidenceCount: 0,
    density: 0.44 + index * 0.035,
    degradation: 0.26,
    weight: 0.46 + index * 0.035,
  })),
  ...['CULTURAL', 'ECONOMY', 'GEO_DIGITAL', 'GEOPOLITICAL', 'BIO', 'CLIMATE', 'INSTITUTIONAL', 'MEMETIC', 'TECH', 'AFFECTIVE'].map((id, index) => {
    const angle = (Math.PI * 2 * index) / 10;
    return {
      id,
      label: id.replace('_', ' '),
      category: 'variable' as const,
      layer: 3,
      x: 650 + Math.cos(angle) * 250,
      y: 80 + Math.sin(angle) * 190,
      z: 3,
      radius: 13,
      connections: ['WorldSpect'],
      superLabel: 'Vector / WorldSpect',
      title: id,
      contentKey: variableContent,
      evidenceCount: id === 'CULTURAL' ? 6 : 0,
      privateEvidenceCount: 0,
      density: id === 'CULTURAL' ? 0.62 : 0.36,
      degradation: id === 'CULTURAL' ? 0.22 : 0.42,
      weight: id === 'CULTURAL' ? 0.60 : 0.38,
    };
  }),
];

