export const SCENE_KEYS=['field','systems','archive','falsification','optionality','governance','authority','agents','identity','models','genai','root'] as const;
export type SceneKey=typeof SCENE_KEYS[number];
export type SceneSpec={key:SceneKey;label:string;title:string;subtitle:string;image:string;liveSource:string;markers:string[]};
export const SCENES:Record<SceneKey,SceneSpec>={
 field:{key:'field',label:'FIELD',title:'Campo de observación',subtitle:'La Tierra es el instrumento. Los datos aparecen donde ocurren.',image:'/sfi-scenes/field.svg',liveSource:'/api/root/state',markers:['observación','persistencia','emergencia','provenance']},
 systems:{key:'systems',label:'SYSTEMS',title:'Qué es un sistema',subtitle:'Relaciones, frontera, intercambio, estado y persistencia.',image:'/sfi-scenes/systems.svg',liveSource:'/api/root/state',markers:['frontera','intercambio','estado','persistencia']},
 archive:{key:'archive',label:'ARCHIVE',title:'Archivo, fuente y contexto',subtitle:'La memoria externa conserva linaje; las pérdidas se muestran.',image:'/sfi-scenes/archive.svg',liveSource:'/api/root/state',markers:['fuente','índice','archivo','síntesis']},
 falsification:{key:'falsification',label:'FALSIFICATION',title:'Campo de falsación',subtitle:'Las hipótesis se sostienen sólo mientras sobreviven al contraste.',image:'/sfi-scenes/falsification.svg',liveSource:'/api/acp/proposals',markers:['hipótesis','instrumentos','umbrales','rivales']},
 optionality:{key:'optionality',label:'OPTIONALITY',title:'Conservar futuros abiertos',subtitle:'Reserva, memoria, redundancia y reversibilidad mantienen opciones.',image:'/sfi-scenes/optionality.svg',liveSource:'/api/acp/proposals',markers:['reserva','memoria','redundancia','reversibilidad']},
 governance:{key:'governance',label:'GOVERNANCE',title:'Arquitectura canónica de gobernanza',subtitle:'Observar → evidenciar → evaluar → inferir → autorizar → ejecutar → retornar → memorizar.',image:'/sfi-scenes/governance.svg',liveSource:'/api/acp/proposals',markers:['observación','evidencia','autorización','retorno']},
 authority:{key:'authority',label:'AUTHORITY',title:'Autoridad · evidencia · recuperación',subtitle:'La autoridad sólo es sostenible si la evidencia y el retorno pueden alcanzarla.',image:'/sfi-scenes/authority.svg',liveSource:'/api/acp/proposals',markers:['autoridad','evidencia','recuperación','riesgo']},
 agents:{key:'agents',label:'AGENTS',title:'Envolvente de autoridad agéntica',subtitle:'Identidad, alcance, herramienta, tiempo, consecuencia y retorno.',image:'/sfi-scenes/agents.svg',liveSource:'/api/root/cognitive-runtime',markers:['identidad','herramienta','consecuencia','retorno']},
 identity:{key:'identity',label:'IDENTITY',title:'Tarea · profesión · identidad',subtitle:'Cuando cambia una capacidad, cambia la forma de ser útil.',image:'/sfi-scenes/identity.svg',liveSource:'/api/root/state',markers:['humano','máquina','sistema','contexto']},
 models:{key:'models',label:'MODELS',title:'Modelo generativo observable',subtitle:'La inferencia se trata como proceso inspeccionable, no como caja negra.',image:'/sfi-scenes/models.svg',liveSource:'/api/root/cognitive-runtime',markers:['tokens','capas','atención','salida']},
 genai:{key:'genai',label:'GENAI',title:'Anatomía de una aplicación GenAI',subtitle:'Entrada, contexto, modelo, herramientas, memoria y controles.',image:'/sfi-scenes/genai.svg',liveSource:'/api/root/cognitive-runtime',markers:['input','memory','tools','policy']},
 root:{key:'root',label:'ROOT',title:'SFI · director operativo',subtitle:'El sistema propone. ROOT acepta, rechaza o pide evidencia en lenguaje normal.',image:'/sfi-scenes/governance.svg',liveSource:'/api/acp/proposals',markers:['propuestas','estado','evidencia','decisión']}
};
