export const SCENE_KEYS=['field','systems','archive','falsification','optionality','governance','authority','agents','identity','models','genai','root'] as const;
export type SceneKey=typeof SCENE_KEYS[number];
export type SceneSpec={key:SceneKey;label:string;title:string;subtitle:string;image:string;liveSource:string;markers:string[]};
export const SCENES:Record<SceneKey,SceneSpec>={
 field:{key:'field',label:'FIELD',title:'Campo de observación',subtitle:'La Tierra es el instrumento. Los datos aparecen donde ocurren.',image:'/sfi-scenes/field.svg',liveSource:'/api/root/state',markers:['observación','persistencia','emergencia','provenance']},
 systems:{key:'systems',label:'SYSTEMS',title:'Sistema vivo',subtitle:'Componentes, frontera, dependencias, intercambio y persistencia observados como una sola estructura.',image:'/sfi-scenes/systems.svg',liveSource:'/api/root/state',markers:['frontera','dependencias','estado','persistencia']},
 archive:{key:'archive',label:'ARCHIVE',title:'Archivo, fuente y contexto',subtitle:'La memoria externa conserva linaje; las pérdidas y discontinuidades deben hacerse visibles.',image:'/sfi-scenes/archive.svg',liveSource:'/api/root/state',markers:['fuente','linaje','archivo','pérdida']},
 falsification:{key:'falsification',label:'FALSIFICATION',title:'Campo de falsación',subtitle:'Hipótesis, contradicciones y evidencia pendiente; nada se cierra por coherencia narrativa.',image:'/sfi-scenes/falsification.svg',liveSource:'/api/acp/proposals',markers:['hipótesis','contraste','evidencia','rivales']},
 optionality:{key:'optionality',label:'OPTIONALITY',title:'Conservar futuros abiertos',subtitle:'Reserva, reversibilidad, congelamiento y riesgo antes de colapsar una opción.',image:'/sfi-scenes/optionality.svg',liveSource:'/api/acp/proposals',markers:['reserva','reversibilidad','riesgo','freeze']},
 governance:{key:'governance',label:'GOVERNANCE',title:'Gobernanza del ciclo',subtitle:'Propuesta → autorización → ejecución → RETURN → calibración → aprendizaje → canon/cierre.',image:'/sfi-scenes/governance.svg',liveSource:'/api/acp/proposals',markers:['decisión','ejecución','return','canon']},
 authority:{key:'authority',label:'AUTHORITY',title:'Autoridad y delegación',subtitle:'Quién puede decidir qué, bajo qué riesgo y con qué traza; canon permanece ROOT-only.',image:'/sfi-scenes/authority.svg',liveSource:'/api/acp/proposals',markers:['root','controller','delegación','traza']},
 agents:{key:'agents',label:'AGENTS',title:'Agentes en ejecución real',subtitle:'Registro no equivale a operación: muestra quién ejecutó, quién está gated y dónde falta soporte.',image:'/sfi-scenes/agents.svg',liveSource:'/api/root/cognitive-runtime',markers:['executor','gated','degraded','return']},
 identity:{key:'identity',label:'IDENTITY',title:'Identidad · linaje · Cognitive Twin',subtitle:'CT-A01 se observa por separado como identidad, conexión, función, ejecución y validación.',image:'/sfi-scenes/identity.svg',liveSource:'/api/root/cognitive-twin/connection',markers:['CT-A01','lineage','connected','validation']},
 models:{key:'models',label:'MODELS',title:'Runtime y modelo observable',subtitle:'La inferencia sólo cuenta como capacidad operativa cuando existe ejecución atribuible y trazable.',image:'/sfi-scenes/models.svg',liveSource:'/api/root/cognitive-runtime',markers:['runtime','execution','evidence','output']},
 genai:{key:'genai',label:'GENAI',title:'Gateway GenAI gobernado',subtitle:'Entrada, scopes, herramientas, memoria, ejecución y RETURN se mantienen como fronteras distintas.',image:'/sfi-scenes/genai.svg',liveSource:'/api/external/v1/manifest',markers:['input','scope','tools','policy']},
 root:{key:'root',label:'ROOT',title:'SFI · director operativo',subtitle:'ROOT observa todo, interviene cuando corresponde y conserva en exclusiva la promoción a canon; la revisión operativa puede delegarse.',image:'/sfi-scenes/governance.svg',liveSource:'/api/acp/proposals',markers:['supervisión','traza','delegación','canon']}
};
