'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import type { RootRow, RootSovereignState } from '@/lib/root/sovereign/rootSovereignState';
import type { RootActionRequest, RootSelection } from './sovereignTypes';
import './root-observatory.css';

type TopologyId = 'I' | 'II' | 'III';
type AccessMode = 'sovereign' | 'observer';
type PanelProps = { id:string; module:string; label:string; status?:string; source?:string; width?:'s'|'m'|'l'|'xl'; children:ReactNode; onOpen?:()=>void };

const TOPOLOGIES: Record<TopologyId,{title:string;question:string}> = {
  I:{title:'SISTEMA',question:'¿Qué existe y qué responde?'},
  II:{title:'CAMPO COGNITIVO',question:'¿Qué está comprendiendo SFI y qué podría hacer?'},
  III:{title:'TRAYECTORIA',question:'¿Qué cambió y qué aprendimos?'},
};
const MODULES = [
  ['01','Estado Institucional'],['02','Sistema / Infraestructura'],['03','Identidad / Autoridad'],['04','Evidencia / Grafo'],['05','Cognitive Runtime'],
  ['06','Cognitive Twin'],['07','Proyección / Predicción'],['08','Atractores / PPOI'],['09','Memoria / Trayectoria'],['10','Gobernanza / Operación'],
] as const;

function text(v:unknown,f='—'){return typeof v==='string'&&v.trim()?v.trim():f}
function rec(v:unknown):RootRow{return v&&typeof v==='object'&&!Array.isArray(v)?v as RootRow:{}}
function strings(v:unknown){return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string'):[]}
function rowDate(r:RootRow){return text(r.observed_at??r.occurred_at??r.executed_at??r.updated_at??r.created_at??r.timestamp,'')||null}
function rid(r:RootRow,f:string){return text(r.id??r.event_id??r.run_id??r.node_key??r.node_id??r.attractor_key??r.hypothesis_id,f)}
function when(v:string|null|undefined){if(!v)return'SIN FECHA';const d=new Date(v);return Number.isFinite(d.valueOf())?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(d):v}
function tone(v:string|null|undefined){const s=(v??'').toLowerCase();if(['observed','operational','available','accepted','verified','active'].includes(s))return'ok';if(['derived','thin','declared','proposed','waiting_evidence'].includes(s))return'warn';if(['degraded','conflicted','blocked','error','blocking'].includes(s))return'bad';return'idle'}
function sel(i:{kind:string;id:string;title:string;source:string;observedAt?:string|null;evidenceIds?:string[];warning?:string|null;data:unknown}):RootSelection{return{kind:i.kind,id:i.id,title:i.title,source:i.source,observedAt:i.observedAt??null,confidence:null,evidenceIds:i.evidenceIds??[],warning:i.warning??null,data:i.data}}

function Panel({id,module,label,status,source,width='m',children,onOpen}:PanelProps){return <section id={id} className={`row-panel pw-${width}`} onClick={onOpen}><header><div><b>{module}</b><span>{label}</span></div>{status?<em data-tone={tone(status)}>{status.toUpperCase()}</em>:null}</header><div className="row-panel-body">{children}</div>{source?<footer>fuente: <strong>{source}</strong></footer>:null}</section>}
function Rows({rows}:{rows:Array<{name:string;sub?:string;status?:string;onClick?:()=>void}>}){return <div className="live-list">{rows.length?rows.map((r,i)=><button key={`${r.name}-${i}`} type="button" onClick={e=>{e.stopPropagation();r.onClick?.()}}><span>{r.name}{r.sub?<small>{r.sub}</small>:null}</span>{r.status?<i data-tone={tone(r.status)}>{r.status}</i>:null}</button>):<p className="empty">MISSING · no hay registros persistidos para este panel.</p>}</div>}

function EvidenceGraph({state,onSelect}:{state:RootSovereignState;onSelect:(s:RootSelection)=>void}){
  const nodes=state.evidence.data.nodes.slice(0,28), edges=state.evidence.data.edges.slice(0,64);
  const pts=useMemo(()=>new Map(nodes.map((n,i)=>{const a=i/Math.max(1,nodes.length)*Math.PI*2,r=28+(i%3)*7;return[n.id,{x:50+Math.cos(a)*r,y:50+Math.sin(a)*r}] as const})),[nodes]);
  return <svg className="graph-svg" viewBox="0 0 100 100">{edges.map(e=>{const a=pts.get(e.from),b=pts.get(e.to);return a&&b?<line key={e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null})}{nodes.map(n=>{const p=pts.get(n.id)!;return <g key={n.id} onClick={e=>{e.stopPropagation();onSelect(sel({kind:'evidence-node',id:n.id,title:n.label,source:n.source,observedAt:n.observedAt,evidenceIds:n.evidenceIds,data:n.payload}))}}><circle cx={p.x} cy={p.y} r="1.8" data-tone={tone(n.epistemicClass)}/><text x={p.x+2.5} y={p.y+1}>{n.label.slice(0,18)}</text></g>})}{!nodes.length?<text x="50" y="50" textAnchor="middle" className="graph-empty">MISSING</text>:null}</svg>
}

function AttractorField({state,onSelect}:{state:RootSovereignState;onSelect:(s:RootSelection)=>void}){
  const a=state.amv.data.attractors[0]??null,v=rec(a?.vector),dims=strings(v.dimensions),sup=new Set(strings(v.supportedDimensions)),con=new Set(strings(v.contradictedDimensions)),mis=new Set(strings(v.missingDimensions));
  return <div className="attractor-field" onClick={e=>{e.stopPropagation();if(a)onSelect(sel({kind:'attractor',id:rid(a,'attractor'),title:text(a.label??a.attractor_key,'Atractor'),source:state.amv.source,observedAt:rowDate(a),data:a}))}}><div className="living-grid"/><div className="attractor-core"><span>{a?text(a.label??a.attractor_key):'SIN ATRACTOR DECLARADO'}</span><small>{a?text(a.status,'DECLARED'):'MISSING'}</small></div>{dims.map((d,i)=>{const ang=i/Math.max(1,dims.length)*Math.PI*2,x=50+Math.cos(ang)*32,y=50+Math.sin(ang)*32,s=con.has(d)?'bad':sup.has(d)?'ok':mis.has(d)?'idle':'warn';return <span className="orbit-node" data-tone={s} key={d} style={{left:`${x}%`,top:`${y}%`}} title={d}>{i+1}</span>})}</div>
}

export function RootObservatoryWorkspace({state,accessMode,actorLabel,refreshing,warning,onRefresh,onSelect,onAction}:{state:RootSovereignState;accessMode:AccessMode;actorLabel:string;refreshing:boolean;warning:string|null;onRefresh:()=>void;onSelect:(v:RootSelection)=>void;onAction:(a:RootActionRequest)=>void}){
  const [filter,setFilter]=useState<'all'|TopologyId>('all'),[clock,setClock]=useState(()=>new Date());
  useEffect(()=>{const id=window.setInterval(()=>setClock(new Date()),1000);return()=>window.clearInterval(id)},[]);
  const phiFact=state.interpretation.facts.find(f=>f.id==='institutional-position'),phi=phiFact?.value.match(/([0-9]+(?:\.[0-9]+)?)/)?.[1]??'—';
  const agents=state.cognitiveRuntime.data.agents,executed=agents.filter(a=>a.status==='operational').length,caps=state.execution.data.capabilities,available=caps.filter(c=>c.state==='available').length;
  const evidenceCount=state.evidence.data.entries.length+state.evidence.data.ledger.length,graphStatus=state.evidence.error?'DEGRADED':state.evidence.data.nodes.length?'OBSERVED':'MISSING',attractor=state.amv.data.attractors[0]??null,divergences=state.interpretation.divergences.length;
  const sources=[state.system,state.governance,state.agents,state.predictions,state.amv,state.evidence,state.execution,state.telemetry,state.cognitiveRuntime],sourceOk=sources.filter(s=>!s.error).length;
  const hypotheses=[...state.predictions.data.runs,...state.predictions.data.legacyEntries],recentEvents=state.cognitiveRuntime.data.eventGraph.recentEvents.slice(0,30);
  const trajectory=[...state.evidence.data.entries.map(row=>({kind:'evidence',row})),...hypotheses.map(row=>({kind:'prediction',row})),...state.predictions.data.outcomes.map(row=>({kind:'outcome',row})),...state.predictions.data.learningEvents.map(row=>({kind:'learning',row})),...state.governance.data.audits.map(row=>({kind:'audit',row}))].sort((a,b)=>new Date(rowDate(b.row)??0).valueOf()-new Date(rowDate(a.row)??0).valueOf()).slice(0,40);
  const byFamily=new Map<string,typeof caps>();for(const c of caps){const f=c.id==='daily'||c.id==='audit'?'OBSERVAR':c.id==='evidence'||c.id==='amv-ingest'?'INTEGRAR':c.id==='amv-search'||c.id==='graph'?'CONSULTAR':c.id==='simulation'?'MODELAR':c.id==='report'||c.id==='reports'?'REPORTAR':c.id==='all'||c.id==='institutional-cycle'?'ORQUESTAR':'GOBERNAR';byFamily.set(f,[...(byFamily.get(f)??[]),c])}
  const focus=(t:TopologyId)=>filter==='all'||filter===t,jump=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',inline:'start',block:'center'});
  const agentEvidenceIds=(agentId:string)=>recentEvents.filter(e=>e.sourceId===agentId&&e.eventId).map(e=>e.eventId);

  return <div className="root-observatory"><header className="root-hdr"><strong>SFI · ROOT</strong><span>01 · ESTADO INSTITUCIONAL</span><b>ΦSFI <em>{phi}</em></b><span>AGENTES <i>{executed}/{agents.length||'—'}</i></span><span>CAPACIDADES <i>{available}/{caps.length||'—'}</i></span><span>EVIDENCIA <i>{evidenceCount}</i></span><span>GRAFO <i data-tone={tone(graphStatus)}>{graphStatus}</i></span><span>ATRACTOR <i>{attractor?text(attractor.status,'DECLARED').toUpperCase():'MISSING'}</i></span><span>DIVERGENCIAS <i>{divergences}</i></span><div className="root-hdr-right"><button type="button" onClick={onRefresh}>{refreshing?'ACTUALIZANDO':'ACTUALIZAR'}</button><span>{actorLabel} · {accessMode==='sovereign'?'SOVEREIGN':'OBSERVER'}</span><time>{clock.toLocaleTimeString('es-MX')}</time></div></header>
    <aside className="root-side"><small>TOPOLOGÍA</small>{(['all','I','II','III'] as const).map(t=><button key={t} className={filter===t?'active':''} onClick={()=>setFilter(t)}>{t==='all'?'Ø':t}</button>)}<small>MÓDULOS</small>{MODULES.map(([id,label])=><button key={id} onClick={()=>jump(`mod-${id}`)}>{id}<span>{label}</span></button>)}<small>SUPERFICIES</small><Link href="/root/institutionalization" title="Institutionalization">IN</Link><Link href="/root/reports" title="Reportes de agentes">RP</Link><Link href="/field">FD</Link><Link href="/field/map">FM</Link><Link href="/studio">ST</Link><Link href="/interface/observatory">OB</Link><Link href="/library">LB</Link></aside>
    <main className="root-observatory-main">{warning?<div className="root-warning">{warning}</div>:null}
      <section className={`topology-row ${focus('I')?'':'dim'}`}><header><b>I</b><strong>{TOPOLOGIES.I.title}</strong><em>{TOPOLOGIES.I.question}</em></header><div className="panel-strip">
        <Panel id="mod-01" module="01 · ESTADO INSTITUCIONAL" label="ΦSFI · interpretación" status={phiFact?.status??'missing'} source={phiFact?.source} width="l" onOpen={()=>phiFact&&onSelect(sel({kind:'institutional-fact',id:phiFact.id,title:phiFact.label,source:phiFact.source,observedAt:phiFact.observedAt,evidenceIds:phiFact.evidenceIds,warning:phiFact.warning,data:phiFact}))}><div className="phi-live"><strong>{phi}</strong><span>{state.interpretation.headline}</span><small>{sourceOk}/{sources.length} fuentes sin error · {when(state.generatedAt)}</small></div></Panel>
        <Panel id="mod-02" module="02 · SISTEMA" label="Salud de superficies" status={state.system.error?'degraded':state.system.dataClass} source={state.system.source}><Rows rows={state.system.data.matrix.map(m=>({name:m.label,sub:m.openItems.value===null?undefined:`${m.openItems.value} abiertos`,status:m.state.status,onClick:()=>onSelect(sel({kind:'system-item',id:m.id,title:m.label,source:m.state.source,observedAt:m.state.observedAt,evidenceIds:m.state.evidenceIds,warning:m.state.warning,data:m}))}))}/></Panel>
        <Panel id="mod-03" module="03 · IDENTIDAD" label="Sesión / autoridad" status="observed" source="server user context"><Rows rows={[{name:actorLabel,sub:accessMode==='sovereign'?'ROOT · SOVEREIGN':'ROOT · OBSERVER',status:'observed'}]}/></Panel>
        <Panel id="mod-institution" module="01a · INSTITUCIONALIZACIÓN" label="Founder dependency / transferencia" status="declared" source="FEP-01 + Cognitive Twin memory" width="l"><div className="intake-live"><p>Observa dónde SFI todavía depende del fundador, separa criterio transferible de autoridad reservada y exige reproducción antes de declarar capacidad institucional.</p><Link href="/root/institutionalization">ABRIR INSTITUTIONALIZATION →</Link><Link href="/root/reports">LEER REPORTES DE AGENTES →</Link></div></Panel>
        <Panel id="mod-04-intake" module="04a · EVIDENCIA" label="Evidence Intake" status="observed" source="root_evidence_entries" width="l"><div className="intake-live"><p>Captura evidencia con procedencia explícita. El contenido no se autopromueve a CANONICAL.</p><Link href="/root/evidence/intake">REGISTRAR / VINCULAR EVIDENCIA →</Link></div></Panel>
        <Panel id="mod-10" module="10 · GOBERNANZA" label="Capacidades ejecutables" status={state.execution.error?'degraded':state.execution.dataClass} source={state.execution.source} width="l"><div className="cap-groups">{[...byFamily.entries()].map(([f,items])=><div key={f}><b>{f}</b>{items.map(c=><button key={c.id} type="button" data-tone={tone(c.state)} onClick={e=>{e.stopPropagation();onAction({id:c.id,label:c.label,effect:c.description,target:c.endpoint??c.id,endpoint:c.endpoint,method:'POST'})}}>{c.label}<i>{c.state}</i></button>)}</div>)}</div></Panel>
      </div></section>
      <section className={`topology-row ${focus('II')?'':'dim'}`}><header><b>II</b><strong>{TOPOLOGIES.II.title}</strong><em>{TOPOLOGIES.II.question}</em></header><div className="panel-strip">
        <Panel id="mod-04" module="04 · EVIDENCIA" label="Grafo de evidencia" status={graphStatus} source={state.evidence.source} width="l"><EvidenceGraph state={state} onSelect={onSelect}/></Panel>
        <Panel id="mod-05" module="05 · RUNTIME" label={`${agents.length} agentes`} status={state.cognitiveRuntime.data.status} source={state.cognitiveRuntime.source} width="l"><Rows rows={agents.map(a=>({name:a.name,sub:`${a.layer} · ${a.domain}`,status:a.status,onClick:()=>onSelect(sel({kind:'agent',id:a.id,title:a.name,source:state.cognitiveRuntime.source,observedAt:state.cognitiveRuntime.observedAt,evidenceIds:agentEvidenceIds(a.id),data:a}))}))}/></Panel>
        <Panel id="mod-06" module="06 · COGNITIVE TWIN" label="Hipótesis / contradicciones" status={hypotheses.length?'derived':'missing'} source={state.predictions.source}><Rows rows={hypotheses.slice(0,20).map((r,i)=>({name:text(r.title??r.hypothesis??r.status,`Hipótesis ${i+1}`),sub:text(r.learning_state??r.status,''),status:text(r.epistemic_class??r.status,'derived'),onClick:()=>onSelect(sel({kind:'hypothesis',id:rid(r,`hyp-${i}`),title:text(r.title??r.hypothesis,`Hipótesis ${i+1}`),source:state.predictions.source,observedAt:rowDate(r),evidenceIds:strings(r.evidence_refs),data:r}))}))}/></Panel>
        <Panel id="mod-07" module="07 · PROYECCIÓN" label="Predicción / outcome" status={state.predictions.error?'degraded':state.predictions.dataClass} source={state.predictions.source}><div className="metric-cluster"><b>{state.predictions.data.runs.length+state.predictions.data.legacyEntries.length}<small>PREDICCIONES</small></b><b>{state.predictions.data.outcomes.length}<small>OUTCOMES</small></b><b>{state.predictions.data.learningEvents.length}<small>LEARNING</small></b></div></Panel>
        <Panel id="mod-08" module="08 · ATRACTORES" label="Campo institucional" status={attractor?text(attractor.status,'declared'):'missing'} source={state.amv.source} width="xl"><AttractorField state={state} onSelect={onSelect}/></Panel>
      </div></section>
      <section className={`topology-row ${focus('III')?'':'dim'}`}><header><b>III</b><strong>{TOPOLOGIES.III.title}</strong><em>{TOPOLOGIES.III.question}</em></header><div className="panel-strip">
        <Panel id="mod-09" module="09 · TRAYECTORIA" label="Evidencia → aprendizaje" status={trajectory.length?'derived':'missing'} source="evidence + prediction + outcome + learning + audit" width="xl"><div className="trajectory-live">{trajectory.map((it,i)=><button key={`${it.kind}-${rid(it.row,String(i))}`} type="button" onClick={e=>{e.stopPropagation();onSelect(sel({kind:it.kind,id:rid(it.row,`${it.kind}-${i}`),title:text(it.row.title??it.row.event_name??it.row.action??it.row.status,it.kind),source:it.kind,observedAt:rowDate(it.row),evidenceIds:strings(it.row.evidence_refs),data:it.row}))}}><time>{when(rowDate(it.row))}</time><i>{it.kind}</i><span>{text(it.row.title??it.row.event_name??it.row.action??it.row.status??it.row.learning_state,it.kind)}</span></button>)}</div></Panel>
        <Panel id="mod-09-memory" module="09 · MEMORIA" label="AMV / MIHM" status={state.amv.error?'degraded':state.amv.dataClass} source={state.amv.source}><div className="metric-cluster"><b>{state.amv.data.memories.length}<small>AMV MEMORY</small></b><b>{state.predictions.data.learningEvents.length}<small>LEARNING EVENTS</small></b><b>{state.governance.data.audits.length}<small>AUDITED ACTIONS</small></b></div></Panel>
        <Panel id="mod-10-log" module="10 · GOBERNANZA" label="Bitácora / eventos cognitivos" status={state.governance.error?'degraded':state.governance.dataClass} source={state.governance.source} width="l"><Rows rows={[...recentEvents.map(e=>({name:e.eventName,sub:`${when(e.occurredAt)} · ${e.sourceId??'runtime'}`,status:e.epistemicClass,onClick:()=>onSelect(sel({kind:'cognitive-event',id:e.eventId,title:e.eventName,source:e.sourceId??state.cognitiveRuntime.source,observedAt:e.occurredAt,data:e}))})),...state.governance.data.audits.slice(0,10).map((r,i)=>({name:text(r.action,`audit ${i+1}`),sub:when(rowDate(r)),status:'observed',onClick:()=>onSelect(sel({kind:'audit',id:rid(r,`audit-${i}`),title:text(r.action,'Audit'),source:state.governance.source,observedAt:rowDate(r),data:r}))}))]}/></Panel>
        <Panel id="mod-10-div" module="10 · GOBERNANZA" label="Divergencias" status={divergences?'degraded':'observed'} source="institutional interpretation"><Rows rows={state.interpretation.divergences.map(d=>({name:d.title,sub:d.observation,status:d.status,onClick:()=>onSelect(sel({kind:'divergence',id:d.id,title:d.title,source:d.source,data:d}))}))}/></Panel>
      </div></section>
    </main></div>
}